### ISSUE TITLE
Don't use _ubuntu-colors.scss variables outside of _colors.scss

### ISSUE THREAD

**Issue by IcyEyeG** [ubuntu/yaru#1001]
The rationale behind this is that it will make code more consistent, makes sure the color pallet difference between the light and dark variant is only dictated by _colors.scss and makes it easier to change theme colors without affecting its behaviour.

**Comment by clobrano** [comment]
I am unsure about this. I see _ubuntu_colors.scss as an extention more than a replacement.

However, I had a rapid look at how we use those colors and many times they're use in the same place (e.g. inkstone is often used as border), so this proposal is actually a possibility. I see it as an extensive code review and refactoring.

**Comment by IcyEyeG** [comment]
In case anyone wants to test this out the changes I made to the variables of _common.scss and _drawing.scss in my fork [ReactPlusYaru](/IcyEyeG/ReactPlusYaru), I made [this branch](/IcyEyeG/yaru/tree/fix-color-variables).

I didn't make a pull request since this is kind of a proof of concept than anything else.

@clobrano First time I read the code as an outsider, since I wanted to make yaru-derivated themes, I saw _ubuntu-colors.scss as the main palette of the theme, hence my proposal.

In that sense, another change to add to this would be to move Terminal colors and Widget colors to _colors.scss and leave something like `$aubergine: #300A24;` and `$grey: #2B2929;` in _ubuntu-colors.scss, to be called by `$terminal_bg_color` and `$headerbar_bg_color`. respectively, in _colors.sccs.

**Comment by clobrano** [comment]
`_colors.scss` comes from upstream. I think that initially we wanted to reduce the amount of changes, this is why `_ubuntu_colors` has been made (I guess).

> n case anyone wants to test this out the changes I made to the variables of _common.scss and _drawing.scss in my fork ReactPlusYaru, I made this branch.

I see many problems in this branch. For example,  $inkstone (`#3D3D3D`) is replaced by $headerbar_bg_color (`#2B2929`), but they are different colors, and the same I saw for other replacement you've made

`#2B2929` is not the color I would call grey.

**Comment by IcyEyeG** [comment]
> _colors.scss comes from upstream. I think that initially we wanted to reduce the amount of changes, this is why _ubuntu_colors has been made (I guess).

Ah, interesting, that makes a ton of sense in hindisght.

>I see many problems in this branch. For example, $inkstone (#3D3D3D) is replaced by $headerbar_bg_color (#2B2929), but they are different colors, and the same I saw for other replacement you've made

I know, that's why I didn't dare to make a pull request, I'm just showing the variables that would need replacing.

>#2B2929 is not the color I would call grey.

True, I was just giving an example of a variable. I wasn't quite sure what to name it.

**Comment by Feichtmeier** [comment]
Removing code out of apps is surely a target and we don't like to put code there. Sometimes it's sadly need as we also fixed code that mitigates wrong placement of elements which padding or margin is baked into the app. There is a new gnome terminal UI in the next version so we can eventually drop the whole code for this one. Nautilus code can also be dropped but I'm not sure.

**Comment by Feichtmeier** [comment]
Hmhm thought about this for a while.
I think carlo is right. When we use all the ubuntu colors, it is pretty clear what those are. If you use vscode ctrl+middle-click on the variable and it jumps into _ubuntu_colors
This would be only needed if we would support more distributions like for example mate.

Also it would sometimes need to introduce even more variables to colors. For example the headerbar border is $inkstone. There is no other color in _colors which uses inkstone in light and dark theme, but the headerbar is the same in light and dark theme. Thus we would need an additional color for the headerbar_border.

Sure it is possible but - without any offense or negative intention - this should be done by either carlo, aaron or me, since we know how the theme should look. I fear that even one of us could produce some color regressions when we introduce some new colors in _colors and or use existing colors and try to imitate some of the ubuntucolors with lighten()/darken()

I'd say we can keep it open but from my point of view this is rather a low-prio.

**Comment by clobrano** [comment]
The rational is clear and I agree with it, however it is basically a code review + refactoring request which does not need a ticket opened to be remembered/done.
@IcyEyeG, any PR in this direction is well accepted of course, but might require some time to be analyzed due to the importance of the change.

Closing this now
