### ISSUE TITLE
emblem-shared.svg is missing

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1039]
![image](https://user-images.githubusercontent.com/15329494/49882768-97e4b180-fe31-11e8-957c-50e96ce0b834.png)

![peek 2018-12-12 17-14](https://user-images.githubusercontent.com/15329494/49882789-9dda9280-fe31-11e8-9e8c-2493b4d1396c.gif)

![image](https://user-images.githubusercontent.com/15329494/49882812-a7fc9100-fe31-11e8-83a0-cde429e05cc2.png)

It currently falls back to Humanity

There is a symbolic icon though, maybe we could take this as a first start?
![image](https://user-images.githubusercontent.com/15329494/49883088-3a049980-fe32-11e8-9ba2-0b274852a453.png)

**Comment by ubuntujaggers** [comment]
Just to check I understand this behaviour correctly:

- You have a folder called "public" which already has the "shared" symbol on it (I'll call that symbol "<");
- You edit the properties on that folder to enable sharing;
- A full colour emblem appears on the folder to show that it's now being shared ("⇄") but it's from Humanity, because this full colour emblem doesn't exist in Suru

?

If we use the symbolic emblem in this context, will that result in "<" appearing twice on the same folder?  Once because it's already on the folder, and again when it appears (instead of the "⇄") when you actually enable sharing for this folder?

If we do a full colour version of "<" to use as the emblem that appears, I wonder if we should then change the "places" symbol for folder-publicshare so it isn't also a "<".

Alternatively, we could just do a more Suru version of "⇄" to avoid clash?  That would be very easy, just two flat arrows in Suru red and Suru green.

Lastly, is there another missing icon in properties, when you tab onto "local network share"?

I'll start with a Suru version of "⇄" because it's the most minimal change from current behaviour and see how that looks.

**Comment by Feichtmeier** [comment]
![screenshot_20190105-093849_samsung internet](https://user-images.githubusercontent.com/15329494/50722334-cd498b80-10cd-11e9-825a-8b5b79eb6a4d.jpg)

@ubuntujaggers like this
