### ISSUE TITLE
Refusal of small icons

### ISSUE THREAD

**Issue by eaglersdeveloper** [ubuntu/yaru#1040]
In Unity 8, only one application icon was used. And now are 12 icons of different sizes. What if we refuse small icons?

Firstly, less expensive for developers.
Secondly, possibility of using vector icons.
Thirdly, looks better.

On the left is 256x256 icons.
On the right is 48x48 icons.

![Снимок экрана от 2018-12-10 14-48-34|67x585](https://ubuntucommunity.s3-us-east-2.amazonaws.com/original/2X/5/5aa01bb4978715537abe342243571e2ee6fd9e52.png) ![Снимок экрана от 2018-12-10 14-48-01|66x579](https://ubuntucommunity.s3-us-east-2.amazonaws.com/original/2X/e/ef350c50a7f9a9c91ad07bf8b7fbb7f7529e22e6.png)

P.S. I posted the same thing on Ubuntu Discourse, but no one responded: https://discourse.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/2041?u=eaglers

**Comment by clobrano** [comment]
Icons are used also in other places than dock and dash. Some notifications for example uses it and might makes the notification bubble too big if there isn't the proper size available

**Comment by eaglersdeveloper** [comment]
Then refuse 48x48 icons?

**Comment by clobrano** [comment]
I don't think this would be an improvement, the adoption of .svg depends on the support available in gtk, not in the given icon and "looks better", well it depends on the application it is using the icon, I don't see a strong documentation of this, only one specific case in which this happen.

**Comment by Feichtmeier** [comment]
I think we should not make a rushed decision here. Better look at upstream Suru and GTK/GNOME here. I think there is something on the horizon for dropping that folder structure and rendering the smaller sizes automatically to have less detail, but I don't know the development status of that. Thus, I will close this here. We should stick to the convention as long as it is the standard

**Comment by eaglersdeveloper** [comment]
I don't understand what you are talking about.

**Comment by eaglersdeveloper** [comment]
GNOME has already refused small icons.

**Comment by Feichtmeier** [comment]
No, they didn't (at least not completely)

https://gitlab.gnome.org/GNOME/adwaita-icon-theme/tree/master/Adwaita

https://gitlab.gnome.org/GNOME/adwaita-icon-theme/blob/master/Adwaita/22x22/places/folder-documents.png

**Comment by eaglersdeveloper** [comment]
What about refusal of small **application** icons? And what about creating a single vector icon for export to a few raster icons?

**Comment by Feichtmeier** [comment]
I guess that would need to be changed int that render script. I bet that upstream suru will do this at a certain point by its own to adapt to the new gnome script so why don't we just wait for that? I think the difference is very minimal and the additional highlights in the smaller sizes are not that dramatic

**Comment by eaglersdeveloper** [comment]
[Sam's repository](https://github.com/snwh/suru-icon-theme) hasn't been updated for a long time.
Plus, I know a little Python.

**Comment by eaglersdeveloper** [comment]
It is important to act now. Otherwise, some developer will make an application icon for Ubuntu in accordance with the current guidelines. And one more developer. And one more. And more.

**Comment by clobrano** [comment]
I don't see any hurry actually. GNOME is still using the same structure we
are using, that's it.

> Otherwise, some developer will make an application icon for Ubuntu in
accordance with the current guidelines.

which is totally fine

**Comment by eaglersdeveloper** [comment]
GNOME core applications use single vector icon.

https://gitlab.gnome.org/GNOME/nautilus/blob/master/data/icons/hicolor/scalable/apps/org.gnome.Nautilus.svg

**Comment by Feichtmeier** [comment]
Yes I realized this, too
So they have the adwaita icon with all the different sizes and as PNGs
And also they make icons for all the gnome applications which are then installed in /usr/share/icons/fullcolor or inside the app itself if it is flatpaked
But does Suru work with just scaling them down?
Adwaita+gnome icons can do this because they have a symbolic icon for EVERY app. We don't have that. (that was a reason to remove symbolic icons from the app menu in gnome shell's top bar, message tray and notifications)
Also, since we are discussing here, could you please answer on the other places I have pinged you? It is a a bit awkward

**Comment by clobrano** [comment]
> GNOME core applications use single vector icon.
> 
> https://gitlab.gnome.org/GNOME/nautilus/blob/master/data/icons/hicolor/scalable/apps/org.gnome.Nautilus.svg

This is a strong indication about the direction taken, I agree with you. What it's still unknown is how many apps and use cases need old png icons, which is probably the same reason gnome still has them

**Comment by clobrano** [comment]
I think the best thing is to ask gnome devs about the plan for this

**Comment by clobrano** [comment]
Gnome devs replied positively, scaled pngs are not necessary, but we must adhere to these [guidelines](https://developer.gnome.org/hig/stable/icons-and-artwork.html.en). I didn't check them, so I don't know if we're ready for this yet

**Comment by eaglersdeveloper** [comment]
> but we must adhere to these guidelines

What kind?

**Comment by clobrano** [comment]
There is a link to the guidelines...

**Comment by eaglersdeveloper** [comment]
But these are GNOME's guidelines

**Comment by eaglersdeveloper** [comment]
You about this?

> Full-color icons are colorful and detailed, and are optimized for larger sizes. They are defined as 128×128px SVGs, and are sharpest when scaled up in multiples of 128 (such as 256✕256 and 512✕512).The design of full-color icons also allows them to be rendered sharp at 64×64px and 32×32px, but is not advised to make them any smaller.

**Comment by ubuntujaggers** [comment]
For me, the time-consuming bit of the different icons is actually re-drawing the icon at different sizes to make it as clear as possible, which I do with mixed success.

Having one graphic and scaling it to the different sizes is certainly easier.  But, if we're happy with that approach, then making the different sizes in Inkscape would become thirty seconds of a job anyway, because we'd just be resizing the graphic rather than changing it.

So, the main question for me is whether it looks better to optimise the icons at different sizes.  If not, then it doesn't really matter to me whether I quickly resize the icon in Inkscape and stick it on five different squircles, or let the desktop environment take care of it.  If it _does_ look better to optimise/change the icon for the different sizes then I'm happy to carry on doing it.

In Suru, I do think the difference between the 256 and the 48 icons is an assett, it's the others I find a bit fiddly  :)

**Comment by eaglersdeveloper** [comment]
For me, creating small icons takes 15-30 minutes. And this is not only moving a pictogram, but also creating folds. And this all applies to application icons. Difficult to imagine a device icon creating.

**Comment by ubuntujaggers** [comment]
@eaglersdeveloper

"For me, creating small icons takes 15-30 minutes. And this is not only moving a pictogram, but also creating folds. And this all applies to application icons. Difficult to imagine a device icon creating."

Oh yeah, it takes me ages lol, it's my least favourite bit :) but I think that's because we're taking a bit of care to make each size look as good/pixel-clear as it can do?

Possibly we could just draw a 256px that will look good when scaled to each size, but, in that case, if you want a nice clear line that's 1px when shown as a 16px icon, then the same line will be very thick in the larger sizes.  If you want a less chunky line in the larger sizes, then it will be <1px and not crisp in the smaller sizes. It might be recognisable but maybe not as great as it could be? So really I guess the question is how happy people are for the smallest icons to be a bit blurry (like the "person" glyph is in your example).

**Comment by ubuntujaggers** [comment]
Here's a comparison of a few randomly-chosen icons - left is the existing 16px version, right is the full size icon simply scaled down to 16px:

![image](https://user-images.githubusercontent.com/38893390/50548735-eb386b80-0c49-11e9-92ae-d95ef6a30ad3.png) ![image](https://user-images.githubusercontent.com/38893390/50548737-f5f30080-0c49-11e9-90e8-6aaaab983fad.png)

![image](https://user-images.githubusercontent.com/38893390/50548776-5c781e80-0c4a-11e9-8ec2-09e5161a81b0.png) ![image](https://user-images.githubusercontent.com/38893390/50548762-45d1c780-0c4a-11e9-8ac4-e5a038339aa3.png)

![image](https://user-images.githubusercontent.com/38893390/50548799-a3feaa80-0c4a-11e9-9d44-2654dffb4b0f.png) ![image](https://user-images.githubusercontent.com/38893390/50548792-8cbfbd00-0c4a-11e9-9bcb-690cef923970.png)

![image](https://user-images.githubusercontent.com/38893390/50548875-ef658880-0c4b-11e9-9643-43c16a157727.png) ![image](https://user-images.githubusercontent.com/38893390/50548876-f391a600-0c4b-11e9-84b2-fa87dd25d708.png)

![image](https://user-images.githubusercontent.com/38893390/50548830-3a32d080-0c4b-11e9-949f-ea663bcbb434.png) ![image](https://user-images.githubusercontent.com/38893390/50548831-40c14800-0c4b-11e9-9aa9-d9c3dc1694c9.png)

![image](https://user-images.githubusercontent.com/38893390/50548859-a7defc80-0c4b-11e9-9b86-63a5ac5b52a7.png) ![image](https://user-images.githubusercontent.com/38893390/50548860-b0cfce00-0c4b-11e9-9555-d18c5f337da4.png)

Looking at them side-by-side, I think the main advantage of having a separate 16px icon isn't actually the clearness of the pictogram (which is only a little clearer in the current icons), but the nice crisp 1px border around the squircles.  If this was the same graphic scaled to different sizes, then that same border would have to be really chunky at the larger sizes to exist at the smallest one - something like:

![image](https://user-images.githubusercontent.com/38893390/50548947-e4f7be80-0c4c-11e9-9924-4b6a31e616ef.png)

**Comment by eaglersdeveloper** [comment]
I want the same icons everywhere, not different.

**Comment by clobrano** [comment]
I must say I've mixed feelings. I do see that it seems unnecessary now to use many PNGs and I see that might be a burden (more o less) for the developer. At the same time, @ubuntujaggers comparison is quite clear, as of today, some icons need adaptation to small sizes. Of course, we know that Gnome direction is to get rid of PNGs and to use SVG directly, but my point here is different, **are we supposed to push for this transition just now?**

It is possible that the new Adwaita icon set is made in a way that smaller sizes are as good as big ones in svg, but as @ubuntujaggers shown, it is not the same for Suru at the moment.

One last point, what happens if we simply start providing only the SVG version for new icons only? I expect the system to use the SVG version, am I right?

**Comment by eaglersdeveloper** [comment]
> One last point, what happens if we simply start providing only the SVG version for new icons only? I expect the system to use the SVG version, am I right?

No. Only new icons will be vector.

**Comment by Feichtmeier** [comment]
So upstream does kind of the same https://gitlab.gnome.org/GNOME/Initiatives/issues/2#description

> Developers making applications for GNOME should not have to undertake more work to target our platform than they do others (Windows, macOS, iOS, Android, etc.) by having to provide extra icon assets for small, low-resolution icon sizes. **As such, to avoid developers having to put in the effort on them, the 16x16, 24x24, 32x32 & 48x48 icon sizes will be deprecatedin favour of symbolic icons and a single, scalable, high resolution application icon.**  These new application icons will be in vector (SVG) format to better suit scalability.

So they are just avoiding that small full color icons everywhere and replace them with symbolic icons + make what @eaglersdeveloper desires for the bigger icons

Is this what you did in your PR @eaglersdeveloper ?

**Comment by Feichtmeier** [comment]
The problem I see is 18.04 support

After my latest icon request fail for printers, I realized that GNOME 3.30 started to replace many icons with symbolic icons. 
We could just provide the humanity icon fallback as always and dodge a branch change again

**Comment by ubuntujaggers** [comment]
Do I understand the quoted text correctly: where the full colour 48px icon is used currently, in future it will be the symbolic version that's used in those contexts?

If so, that will have a big (IMHO undesirable) impact on Ubuntu's visual identity, if Ubuntu falls 100% in line with Gnome, because the 48px version is the one that's used by default on the launcher. I don't think a launcher of monochrome symbols would look very Ubuntu...? I think the full size icon only routinely appears in the app grid.

**Comment by Feichtmeier** [comment]
No :)
App icons will be replaced with SVGs in full color
But gtk 3.30 apps exchange all the small icon occurences with symbolic icons by enforcing the toolkit to use symbolic icons
like in the printer example

**Comment by Feichtmeier** [comment]
But this would also mean, that we need to work on these:


![image](https://user-images.githubusercontent.com/15329494/50574383-0ccf5980-0de8-11e9-8fc0-aa41fe4c6594.png)

So I'd say, before those aren't matching our fullcolor apps (regarding completness) I'd say, let's get this fixed first

Since their idea is that the small full color icons become obsolete when small icons are all symbolic :bulb:

**Comment by ubuntujaggers** [comment]
@Feichtmeier 

"So I'd say, before those aren't matching our fullcolor apps (regarding completness) I'd say let's not overreact and rush something"

And from #1053:

"There are other more important things to do for you two guys :) like symbolic icons of all our all icons / update them"

Aha, now I think I understand - so to keep pace we need to make a symbolic version of every app icon that exists in Suru?

Looking at the existing app symbols, am I correct in thinking that the symbolic version of an app should only represent the pictogram (e.g., music, app store), unless the squircle is necessary (e.g., terminal)?  Or do we want all the app symbolic icons to be squircles like terminal and calculator currrently are?

**Comment by ubuntujaggers** [comment]
@Feichtmeier @clobrano @madsrh 

To make the transition properly, should we go as far as making symbolic versions of apps like:

![image](https://user-images.githubusercontent.com/38893390/50636176-027aa000-0f4d-11e9-8612-0d05a6c27f63.png)

??

**Comment by ubuntujaggers** [comment]
I'm guessing they will also replace the 16x16px at the top left of the desktop, that would mean we see an awful lot of the symbols if so:

![image](https://user-images.githubusercontent.com/38893390/50640289-517c0180-0f5c-11e9-9c3b-f9b94081efc8.png)

For starters I've had a go at making the notepad symbol match the Suru icon:

![image](https://user-images.githubusercontent.com/38893390/50640355-8be59e80-0f5c-11e9-9674-250f5ac90187.png)

![image](https://user-images.githubusercontent.com/38893390/50640375-9ef86e80-0f5c-11e9-9495-840884816934.png)

**Comment by Feichtmeier** [comment]
That is currently disabled, but we could switch it back to symbolic.

And wow you are fast! :)

**Comment by ubuntujaggers** [comment]
I think if Yaru is going to switch to one full colour svg + one symbolic svg for each app, then it might be a good idea to switch the top bar back to the symbolic, simply because the symbolic is optimised for 16x16px and the full colour svg won't always scale very clearly to such a small size.  E.g., notepad is one of the apps in the comparison above, and I think the new symbolic version is clearer than the full colour one at 16px?

**Comment by Feichtmeier** [comment]
Yes totally. I think it was a semi good idea to remove the symbolic icons in the app menu and the message tray
If @clobrano and @madsrh agree I can fix that right away
(Reminder: we disabled the symbolic icons because third party apps mostly not support them thus having some apps symbolic and some apps full colour. But imho that's not a strong argument against symbolic icons for pre installed apps)

**Comment by eaglersdeveloper** [comment]
I saw, symbolic icons isn't needed. They are boring, monochrome. Colored is visible in small size.

**Comment by Feichtmeier** [comment]
Ehhh, I don't agree.
Also we are still a GNOME project and thus won't do anything against their decisions. There isn't much room for discussion in this case.
We need the symbolic icons.

**Comment by ubuntujaggers** [comment]
I don't have a strong feeling about whether full colour or symbol looks best at 16x16px, but I do enjoy doing the symbolic icons so it's all good from my point of view  :)

I think once you get down that small, though, it's slightly better to have an icon that's optimised for 16px (whether it's colour or not) rather than just scaling a large icon down.

This is how far I've got with the symbolic icons...  here you can see the revised notepad symbol, the LibreOffice symbols, and also I've started working through the apps in alphabetical order, so you can see symbolic versions of accessories-character-map, addressbook-app, amazon-store, and aptdaemon-download which are faithful to the full colour versions in Suru.

This is 1:1 size:

![image](https://user-images.githubusercontent.com/38893390/50668478-1955dc80-0fb7-11e9-96ee-2dc22b003c3b.png)

...and this is zoomed in:

![image](https://user-images.githubusercontent.com/38893390/50668520-6639b300-0fb7-11e9-83b7-b6d8e633db77.png)

Because all the symbols go in source-symbolic.svg, if more than one person wants to work on these, we'll have to coordinate PRs carefully, because otherwise we might accidentally remove each other's changes (e.g., if person A edits icon X while I'm adding icon Y, and person A does the pull request before me, I might accidentally revert icon X when I do mine).

**Comment by eaglersdeveloper** [comment]
> Also we are still a GNOME project

We are a Canonical project

**Comment by ubuntujaggers** [comment]
I'm now up to letter C.  Here we see symbolic versions of the Suru icons for backups-app, calendar-app, camera-app, clock-app and configurator app at the real size:

![image](https://user-images.githubusercontent.com/38893390/50692095-a8e8a300-102a-11e9-82f8-4d7f9d88af08.png)

And here, zoomed in:

![image](https://user-images.githubusercontent.com/38893390/50692149-d7667e00-102a-11e9-8e5e-975422342539.png)

If these are of a good enough standard I believe I can do symbolic versions of all the Suru app icons in a reasonable timeframe, working at a rate of a couple a night on average.

**Comment by clobrano** [comment]
Awesome work :)

**Comment by ubuntujaggers** [comment]
A run of cute ones:

![image](https://user-images.githubusercontent.com/38893390/50703601-a0a15f80-104c-11e9-91f4-1d23e7631f79.png)

![image](https://user-images.githubusercontent.com/38893390/50703579-89627200-104c-11e9-94a2-741f4bbc7bbf.png)

![image](https://user-images.githubusercontent.com/38893390/50703660-c595d280-104c-11e9-9f39-02b512a3e56c.png)

**Comment by Feichtmeier** [comment]
seeing your awesome symbolic icons  I wonder if we could do suru full color icons without the squircle in every icon :O Kinda offtopic

Really awesome what you are doing there!

**Comment by ubuntujaggers** [comment]
Okay, I've been through the apps icon folder, and I think I've now got a symbolic icon for everything under apps!  Having said which, I'm sure I must have missed one or two.  I certainly left the software ones because we can do those when Eaglers pushes the new ones in full colour.

![image](https://user-images.githubusercontent.com/38893390/50727160-ab242d80-110e-11e9-9461-68a95bca3139.png)

Zoomed in:

![image](https://user-images.githubusercontent.com/38893390/50727172-2259c180-110f-11e9-9d93-3f27d28a3b57.png)

**A few of these possibly need further some work/improvement,** but I think it's a solid start and good to have a work in progress at least for every app.

A small number of them are simply existing symbols used elsewhere.  IMO, if we don't want the clash, we should use a different motif for one of the things that clashes.  For instance: network-wireless-hotspot and podcasts-app both have a mast/circles motif, so I copied the network icon for podcasts.  If we don't like that, I feel we should probably change one of the things to have a different motif, rather than differentiating between them by drawing the same motif two slightly different ways at 16x16px (which feels a bit random and arbitrary?).  Just a thought.

**Comment by Feichtmeier** [comment]
Awesome! :clap: 

We could merge this right away after you finished the select-all symbol (it is the same file, thus creating git conflicts)
Or you could cancel your other PR and include the "adwaita-ish" select-all symbol in "the new PR" including all these new babies + the select-all

I think you are right: if we find further improvements of this or that icon, we can make this in follow-up-PRs

**Comment by Feichtmeier** [comment]
just realized that we need to change 4 lines in the index file to achieve the same thing: use the icons with the big highlights only icons < 34px
![screenshot from 2019-01-09 17-11-21](https://user-images.githubusercontent.com/15329494/50912099-9c50ba00-1431-11e9-8b64-dee69c84c689.png)

If you agree I can make a PR with that soon and we will close the SVG only idea for "now"/the next months @madsrh @clobrano

**Comment by eaglersdeveloper** [comment]
I propose to remove only 48, 32 and 24px and leave 256 and 16px fullcolor icons.

**Comment by clobrano** [comment]
Sorry, I replied on the other ticket. 48px is the most troublesome size. It's the dock size and not a multiple of the size used for designing the icons

**Comment by eaglersdeveloper** [comment]
Explain in more detail, please.

**Comment by eaglersdeveloper** [comment]
I can create PR with some removed PNGs.

**Comment by clobrano** [comment]
The new Gnome guidelines requires the icon to be designed for a size (I remember 256px), this means that resized at 128, 64, 32 they will keep the same pixel perfect shape, but not at 48, which is instead the size we need to use for the dock. @ubuntujaggers explained this better than me in another issue, which at the moment I can't remember.

**Comment by Feichtmeier** [comment]
After agreement with @ubuntujaggers we close this issue, since we do not plan to go this road for the next cycles.
If the dock ever changes it's default size, we could eventually look into this again but then in a different better structured issue.
