### ISSUE TITLE
window and headerbar border problems

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1049]
![image](https://user-images.githubusercontent.com/15329494/50082652-c081f800-01f1-11e9-808c-c28c8c82cb80.png)

![image_2018-12-17_11-43-45](https://user-images.githubusercontent.com/15329494/50082674-ced01400-01f1-11e9-9653-d0c50287b9e8.png)

![image](https://user-images.githubusercontent.com/15329494/50082715-e909f200-01f1-11e9-8e9f-bab3b3ae40ee.png)

The headerbars, titlebars and menus have a border but the rest of the window does not have a border or a visible border-color.
It is more visible in the backdrop and even more visible in the backdrop of the darktheme but it is present always.

It creates this little glitch where 1 pixel is ahead of he other so I think the border is there but it is just transparent (didn't look it up yet).

Adwaita looks like this (just for reference):

![image](https://user-images.githubusercontent.com/15329494/50083038-cf1cdf00-01f2-11e9-8e16-42f8b9c43b4d.png)

![image](https://user-images.githubusercontent.com/15329494/50083086-ecea4400-01f2-11e9-95b6-d81f00b0eb60.png)

**Comment by clobrano** [comment]
It's actually a optic effect, since the headerbar border is dark while the window's one is bright or just brighter in case of dark variant.

e.g. gnome-tweaks with a dark bg, it looks like there's 1px of difference
![image](https://user-images.githubusercontent.com/2883614/50103802-c6470000-0228-11e9-95ba-8c0a8ff70556.png)

same window, but on brighter bg, makes the real border line more evident
![image](https://user-images.githubusercontent.com/2883614/50103858-e4acfb80-0228-11e9-8933-c18cc6ec6ab1.png)

Nonetheless, I admit it might look weird

**Comment by Feichtmeier** [comment]
We could make the border-color headerbar_bg_color and the border-top-color inkstone

**Comment by Feichtmeier** [comment]
Also - as discussed on telegram (and forgotten in here by me : D ) 
the left border is sometimes not colored like the right border

![image](https://user-images.githubusercontent.com/15329494/50115346-5f850f00-0247-11e9-8f5c-78cf4d7d32e2.png)

**Comment by clobrano** [comment]
Ok, I'll propose something in PR
