### ISSUE TITLE
insert-text and edit-select-all are hard to distinguish 

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1073]
![image](https://user-images.githubusercontent.com/15329494/50574430-e3fb9400-0de8-11e9-882f-a109e7160e4e.png)

![image](https://user-images.githubusercontent.com/15329494/50574445-02fa2600-0de9-11e9-8ccb-0c9ed06fdeb5.png)

![image](https://user-images.githubusercontent.com/15329494/50574446-0d1c2480-0de9-11e9-9274-cf4733676f90.png)

@ubuntujaggers could you take a look at edit-select-all ? I think adwaita got it a bit more right, maybe we can just copy this one and make it thinner? Or just copy it I don't know
![image](https://user-images.githubusercontent.com/15329494/50574455-45236780-0de9-11e9-91ca-4ba000d5e607.png)
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/blob/master/src/symbolic/gnome-stencils.svg

**Comment by ubuntujaggers** [comment]
I started off trying to clone the Adwaita one with a squircle boundary instead of a hard square.  16x16px is an even number which doesn't lend itself well to central dividers (there are two in the Adwaita design) because it means they have to be 2px wide (which looks too big), or not quite central.

Looking at Adwaita, they've got round this by making the whole icon slightly off-centre, which I didn't know was allowed.  So the icon is 16x16px but the actual graphic fills 13x13px (the following shows the graphic relative to the icon boundary):

![image](https://user-images.githubusercontent.com/38893390/50588500-4badef80-0e7a-11e9-8786-0e5f4cf8fae6.png)

Before I realised what Adwaita was doing I tried a different glyph to represent "everything" that didn't use central divisions:

![image](https://user-images.githubusercontent.com/38893390/50588643-e8708d00-0e7a-11e9-82a3-6cb33f78d294.png)

![image](https://user-images.githubusercontent.com/38893390/50588670-050cc500-0e7b-11e9-8414-d723d39a049a.png)

I actually quite like this, because having a stack of two things to represent "all" resembles other action icons like copy, paste, open.  However, is it intuitive (well - at least as intuitive as the Adwaita icon)?

So, two options;

- Use the above "stack" glyph
- Copy Adwaita and also have a slightly off-centre graphic that includes 1px central divisions in the glyph

I tried a third option ("Copy Adwaita and have 2px central divisions") but it didn't look good at all IMO.  I will do some mockups of the other two options.

**Comment by Feichtmeier** [comment]
Nice! I'd prefer your glyph :)

**Comment by ubuntujaggers** [comment]
Ah, super - I've also done the Adwaita approach so here it is for comparison:

![image](https://user-images.githubusercontent.com/38893390/50589204-a7c64300-0e7d-11e9-911f-459e42f0717f.png)

![image](https://user-images.githubusercontent.com/38893390/50589222-ba407c80-0e7d-11e9-9356-d03647fa35ef.png)

**Comment by Feichtmeier** [comment]
This looks also nice :) you decide!
