### ISSUE TITLE
Missing auth-fingerprint icon

### ISSUE THREAD

**Issue by eaglersdeveloper** [ubuntu/yaru#1108]
In Adwaita:

![auth-fingerprint-symbolic](https://user-images.githubusercontent.com/40228953/51075891-1c358900-16ab-11e9-8121-3827ac3a642d.png)

**Comment by madsrh** [comment]
@eaglersdeveloper Why change this? Does it look out of style in Yaru? Perhaps post a screenshot for reference.
IMO the Adwaita icon look fine because I have no idea how a suru style fingerprint icon look.

**Comment by Feichtmeier** [comment]
We could make it less thick. Adwaita symbolic icons are always very thick, no idea why

**Comment by eaglersdeveloper** [comment]
> no idea why

This is the corporate GNOME's style

**Comment by taciturasa** [comment]
> no idea why

adwaita has been focused much more on the most functional implementations rather than ones with stylistic flair for a while (until the new upcoming revamp). as such, through their experimentation and research, they found that thick symbolics were important for low resolution screens or other places where thin line weights would be more unreadable.

**Comment by Feichtmeier** [comment]
Yeah but it doesn't really fit into the other thin Suru styled symbolic icons

Which come from Ubuntu touch as a little reminder and work pretty well on the Ubuntu phone ;)

I don't really understand why thick icons are good for LOW resolution screens but it doesn't really matter after all since this issue is about the missing icon and yes it's missing.
So feel free to provide it @eaglersdeveloper or @ubuntujaggers

(General disclaimer that will be a sticky on the hub soon: if you want a pure gnome experience install gnome-session which includes unmodified gtk, shell and icon themes)

**Comment by ubuntujaggers** [comment]
I had a go at drawing a fingerprint in the Yaru style in case I could beat the feature freeze but no luck yet. Doesn't mean it's impossible, just haven't succeeded so far :) I wondered if a hand like this 👆 with something emphasising the finger would do?

**Comment by madsrh** [comment]
>  I wondered if a hand like this 👆 with something emphasising the finger would do?

Perhaps something like this:

![image](https://user-images.githubusercontent.com/3986894/64892403-9cfeb780-d674-11e9-997b-c230cd678fbb.png)


I also like the first one below similar to our scanner icon:
![image](https://user-images.githubusercontent.com/3986894/64892476-c61f4800-d674-11e9-83e3-42399aba5f2d.png)

**Comment by madsrh** [comment]
> We could make it less thick. Adwaita symbolic icons are always very thick

Did you already do this @Feichtmeier ?

**Comment by Feichtmeier** [comment]
I did it some days ago, but I can't find the icon anymore. Let me try again
