### ISSUE TITLE
GTK2 theming has some glitches

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#112]
I marked the regions which seem to be a bit messed up in the screenshots, I hope you can use this information :) Freaking awesome theme!

Gimp and Inkscape have some strange shadows in most widgets
And intellij IDEA, which uses swing for it's gui, which can use gtk2 theming, has a weird menu bar (grey on black)

![bildschirmfoto von 2018-01-23 08-38-06](https://user-images.githubusercontent.com/15329494/35472485-4ad95af6-0370-11e8-8454-e4ede29b6bcc.png)
![bildschirmfoto von 2018-01-23 08-42-48](https://user-images.githubusercontent.com/15329494/35472486-4b00a35e-0370-11e8-8dba-4355d72f7766.png)

![bildschirmfoto vom 2018-01-23 00-20-19](https://user-images.githubusercontent.com/15329494/35472482-42956466-0370-11e8-9e27-c4e26550e2cd.png)

**Comment by Feichtmeier** [comment]
The gimp and inkscape issues went away after installing:

sudo apt-get install gtk2-engines-pixbuf

The intellij menubar is still dark on black background though

**Comment by ya-d** [comment]
Installing pixbuf engine fixes most severe theming issues. Without it most buttons are not themed at all, so it should there by default.
Without pixbuf menu bar entries have a solid orange background and arrows are too big. With pixbuf installed menu bar entries have the brighter white font but are not always underlined (they are in Audacity but not in Scribus (maybe because of qt underlines letters for shortcuts?)). Arrows are all right now but e.g. check marks are still not themed.

**Comment by giovannicaligaris** [comment]
I think gtk2-engines-pixbuf should a dependencie when installing communitheme.

**Comment by clobrano** [comment]
@ya-d is the problem fixed installing pixbuf engine? Or there are other main issues?

**Comment by Feichtmeier** [comment]
There are several buttons missing + some menu bars have a wrong foreground color. Pasting details later

**Comment by Feichtmeier** [comment]
I found two more issues in the GTK2 java swing theming:

1) the orange highlight color is very hard to see with that dark grey foreground:
![screenshot from 2018-03-02 13-35-54](https://user-images.githubusercontent.com/15329494/36899357-02ed076e-1e1f-11e8-80e7-572c48c593e1.png)
2) The textfields look somehow unthemed
![screenshot-20180302115419-433x221](https://user-images.githubusercontent.com/15329494/36899363-0caacbe2-1e1f-11e8-9091-4778ab52389f.png)

**Comment by ya-d** [comment]
Looks much more complete with the latest updates! 👍 Great to see how far you've come, keep it up guys!

Some very minor glitches (not sure which of those can be themed anyway):
* radio button has check mark instead of point
* spinner isn't themed
* most focus rings are lacking: entry fields with connected buttons aren't closed on the right; buttons have inner grey ring instead of outer orange one; for check/radio buttons only the text label is highlighted in grey; links, sliders, cells, lists, tabs are grey
* toggled button lacks 3d effect (and only being darker doesn't indicate toggled state to me)
* disabled entry fields have lighter border which is also squared and blurry (especially noticeable for entry fields connected with dropdown list or up/down arrows)
* Are QT-apps related to gtk2? Scribus shows only check marks without border in its menu bars which makes them hard to recognize as toggles.

<img width="801" alt="gtk2 widget factory" src="https://user-images.githubusercontent.com/30781876/36915037-8c3bb896-1e4f-11e8-87ac-a63e8da0ade0.png">
<img width="128" alt="gtk2 focus" src="https://user-images.githubusercontent.com/30781876/36915085-b3d7ce62-1e4f-11e8-86c4-450a33805bc3.png">

![qt check marks in menu bar](https://user-images.githubusercontent.com/30781876/36915134-f2b29892-1e4f-11e8-88b6-2ee85672ce77.png)

**Comment by Feichtmeier** [comment]
I have found one more issue in GTK2 file open dialog. There are 0 lines between the elements or any seperation. Really hard to spot anything @clobrano 

![screenshot from 2018-03-07 16-25-04](https://user-images.githubusercontent.com/15329494/37100823-3d6d79ba-2224-11e8-9d84-cbcd8b3d661f.png)

**Comment by clobrano** [comment]
@Feichtmeier is this 17.10 or 18.04?

**Comment by Feichtmeier** [comment]
18.04
I recently updated because you talked about updating on the ubuntu forums =)

**Comment by clobrano** [comment]
@didrocks talked about updating some dependencies, but I don't think that happened yet. That's might be a problem, I need a VM for working on both :cry:

**Comment by Feichtmeier** [comment]
Hm or just announce that it will only support 18.04 soon? In the end 17.10 won't have a long support anyways.

**Comment by didrocks** [comment]
Just be aware that once we do the switch, the packages won't work on artful anymore (both Shell and GTK).

The Shell project may break as well due to missing styles on artful (didn't test, but the OSK classes have been renamed).

**Comment by pojntfx** [comment]
![screenshot from 2018-03-08 14-48-59](https://user-images.githubusercontent.com/28832235/37154336-f4e4f1a2-22df-11e8-99ff-90d8d1f8853f.png)
Had this problem on Bionic before as well, but it seems to be fixed after I've updated today. The new button design however only seems to be applied to the GTK3 theme, but I can't help but just love the new grey accent in the GTK2 theme now. Also, the low contrast headerbars have been fixed (VSCode)!

**Comment by madsrh** [comment]
In Bionic:

![untitled-1](https://user-images.githubusercontent.com/3986894/37584293-3660e4c4-2b55-11e8-9d97-ee533fe38a7a.jpg)

**Comment by godlyranchdressing** [comment]
> The new button design however only seems to be applied to the GTK3 theme

@pojntfx Sorry about that. After the button overhaul I just figured it'd be best to wait till the GTK3 theme gets the final signoff.

**Comment by Feichtmeier** [comment]
![screenshot from 2018-06-25 00-14-48](https://user-images.githubusercontent.com/15329494/41824203-f3fe6b06-780c-11e8-8a5c-f3e4276334aa.png)

We miss the round corners for the bottom edge for none csd menus and all four round corners for CSD menus. And is a shadow possible like in the gtk3 theme? @godlyranchdressing  @CDrummond

**Comment by CDrummond** [comment]
@Feichtmeier sorry, I'm no Gtk2 expert, my previous Gtk2 'fix' for Qt scrollbars was just a quick hack. To be honest, I'm not sure if Gtk2 can have rounded menus. Seeing as Gtk is advancing to Gtk4, I personally think its not worth spending lots of time with Gtk2. Just make it good enough - an exact 1:1 with Gtk3 is just not possible (e.g. scrollbars)

**Comment by Feichtmeier** [comment]
@Paz-it could you check this issue and see if you can do anything about it?

The worst part of gtk2 is that it even looks differently from application to application!

Java swing uses some engine that others don't use? :man_shrugging: 

If it would be only gimp and inkscape I'd say "forget it" since they switch to gtk3 soon but the java swing and Qt theming which takes the gtk2 theming ... that's kind of important.

If you take intellij as an example... ambiance just looks perfectly! with intellij. Perfet in terms of "consistent" and no bugs

**Comment by Feichtmeier** [comment]
@flexiondotorg 

We have still a problem with the Java swing gtk2 theming here. Could you take a look into it? Especially the menu bar on Java swing applications that use the gtk2 theme. I don't even know which theme engine Java uses but you can try it in Intellij's IDEA

**Comment by Feichtmeier** [comment]
i will close this one and make a more precise issue
