### ISSUE TITLE
Missing 2048 icon

### ISSUE THREAD

**Issue by eaglersdeveloper** [ubuntu/yaru#1124]
What about this icon?

![2048](https://user-images.githubusercontent.com/40228953/51322787-d9472d00-1a7f-11e9-9072-1b0b1213a833.png)

**Comment by jbicha** [comment]
There isn't a a Snap yet, but I might make one.

@kenvandine Why does [quadrapassel](https://bazaar.launchpad.net/~ubuntu-desktop/quadrapassel/snap/view/head:/snapcraft.yaml) hard-code the icon path but [gnome-calculator](https://bazaar.launchpad.net/~ubuntu-desktop/gnome-calculator/snap/view/head:/snapcraft.yaml) doesn't?

**Comment by jbicha** [comment]
The proposed new upstream gnome-2048 icon is interesting too.

If you click _View File_ next to `data/icons/org.gnome.TwentyFortyEight.svg` at https://gitlab.gnome.org/GNOME/gnome-2048/merge_requests/5/diffs , it's easy to see a preview.

**Comment by Feichtmeier** [comment]
Currently this whole topic is being discussed.
If we end up with moving away from the uniform squircle baseplate this Suru icon will not be needed. Same for inkscape, Firefox and so on

Let's keep it opened for a while since nothing is set in stone yet but it looks like we move away from providing Suru icons for non-core apps

**Comment by Feichtmeier** [comment]
Closing this since the recent direction of out icon theme :)
Current progress can be seen here: https://github.com/ubuntu/yaru/issues/1180
and here: https://github.com/ubuntu/yaru/pull/1209
