### ISSUE TITLE
Dark theme: entered text not visible in PFD form in evince

### ISSUE THREAD

**Issue by chrisjbillington** [ubuntu/yaru#1133]
I've encountered an issue with the dark theme, with unreadable text when typing into a PDF form using evince.

## Expected Behavior

I should be able to read text typed into a PDF form using evince in the dark theme.

## Actual Behavior

It looks like this, with the text in the form white-on-white (slightly different whites but not visible). There is text being entered in the "First name and initial" field, but it is blank. Once I leave the field, evince renders it as blue text and it is readable. But during editing it looks like this:

![image](https://user-images.githubusercontent.com/1044087/51510065-8ba52a00-1dc9-11e9-8f70-0279b9f917b9.png)

If the window is not focused then the text become visible, with the text entry widget getting a dark background.

![image](https://user-images.githubusercontent.com/1044087/51510109-bc855f00-1dc9-11e9-94da-4ce53e038448.png)

If I put evince in dark mode then the text is white on black:

![image](https://user-images.githubusercontent.com/1044087/51510344-b348c200-1dca-11e9-8c20-ebcf2c3821c3.png)

However, in evince dark-mode and Yaru *light*, the text is also not super visible, though it is not too bad:

![image](https://user-images.githubusercontent.com/1044087/51510409-eab76e80-1dca-11e9-9ce8-a438eb9ae77a.png)

## Steps to Reproduce the Problem

  1. Use Yaru-dark
  1. Open a PDF with an editable form like [this tax form](https://www.irs.gov/pub/irs-pdf/f1040nr.pdf) in evince.
  1. Type something into a field

## Specifications

I've installed Yaru from the Arch Linux AUR and updated it to current git master, git describe in the package build dir gives `r27-35-gf36189f4`

Software that presents the issue:
- Name: Evince/Gnome Document viewer
- Version: 3.30.2

**Comment by clobrano** [comment]
Hey @chrisjbillington, thanks for taking time to help us. Bug is confirmed on Disco as well

**Comment by clobrano** [comment]
I just double checked, the issue is reproducible in Adwaita as well and I believe it's something we can't avoid. The problem is that Evince does not take into account theme variant.

- in theme dark mode, it keeps the pdf white, but it still takes the theme text color, which is of course brighter than in light mode, and so we have white on white.
- in theme light mode, Evince can be still set in its own dark mode, which does the opposite: set the pdf to black, but keeps theme's text color which is dark and so we have dark on dark

This means that whatever we do, we (as well as Adwaita) end up in a misbehavior without knowing in which mode is Evince set.

Best would be to explain the problem to Evince's maintainers and see what they think about it.

**Comment by chrisjbillington** [comment]
Looks like this issue is known to Evince devs, and was fixed very recently:

https://gitlab.gnome.org/GNOME/evince/issues/687

I can't test the fix, but if I understand the problem correctly, it looks like the fix should apply well to all themes both in Evince's light and dark modes.
