### ISSUE TITLE
Style drag in Archive Manager

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1153]
I really don't find the pure white background with black border to fit with the beautiful Yaru theme.
![image](https://user-images.githubusercontent.com/3986894/52243847-41e53500-28db-11e9-9efa-23631b350769.png)

Is this possible to style? Perhaps something like this would fit better:
![image](https://user-images.githubusercontent.com/3986894/52243917-8e307500-28db-11e9-823d-276de769df88.png)

**Comment by clobrano** [comment]
I am afraid this would require a patch to the archive manager itself or in gtk. I inspected the CSS while dragging the row and none of the nodes showed a special state or class I can use to style it :( 
I have not lost any hope only because the row inside treeviews are not visible in gtkinspector in any case, so inspecting the code I might find something more.

**Comment by madsrh** [comment]
I'm closing this because it isn't possible and it's more of a wish than an issue
