### ISSUE TITLE
Theme parsing error: gtk-dark.css

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/yaru#1190]
snap info communitheme
name:      communitheme
summary:   The next Ubuntu theme built by the community.
publisher: Didier Roche (didrocks)
license:   unset
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the community. Yaru will
  become the default Ubuntu theme in Ubuntu 18.10. This package allows you to try out the theme on
  Ubuntu 18.04 LTS.
  
  To try out the theme, install this package on Ubuntu 18.04 LTS, restart your computer and select
  the "Ubuntu with communitheme snap" session from the login screen.
  
  More information is available at
  https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     edge
refresh-date: yesterday at 23:33 IST
channels:
  stable:    0.1 2019-02-05 (1593) 19MB -
  candidate: ↑                          
  beta:      ↑                          
  edge:      0.1 2019-02-15 (1653) 19MB -
installed:   0.1            (1653) 19MB -

Screenshot better then words :smile: 
![screenshot from 2019-02-16 01-12-04](https://user-images.githubusercontent.com/37431503/52889497-f3f8e880-3188-11e9-940c-445e0d17c6a6.png)
I didn't check light theme...

**Comment by Feichtmeier** [comment]
Thank you @Paz-it for your :eagle: :eyes: !

**Comment by clobrano** [comment]
This is a side effect of #1188

**Comment by clobrano** [comment]
The original issue that #1188 addressed, is due to this line in `%jet_popover_button`

https://github.com/ubuntu/yaru/blob/ba2f5d078f43ed1bab7fc5bd908dc70b7793df69/gtk/src/light/gtk-3.20/_common.scss#L1101

since it prevents `.emoji-section` to set the `box-shadow`

I am trying to find and alternative fix in this `wildcard` section for dark theme, but no luck so far. Also consider that #1188 does not fix the issue, gjs simply does not parses that line and cannot apply `extends %jet_popover_button` to anything.

So, popover buttons seems perfectly fine even without this line

https://github.com/ubuntu/yaru/blob/ba2f5d078f43ed1bab7fc5bd908dc70b7793df69/gtk/src/light/gtk-3.20/_common.scss#L2424

does anyone remember why it is necessary?

Similar question, does anybody remember why this line is necessary?

https://github.com/ubuntu/yaru/blob/ba2f5d078f43ed1bab7fc5bd908dc70b7793df69/gtk/src/light/gtk-3.20/_common.scss#L1101

**Comment by Feichtmeier** [comment]
Just remove that :not(button.emoji-section) then. It's nothing mandatory but that parsing error sucks. I can work it out later then

**Comment by clobrano** [comment]
> If dark then wildcard of death to popover buttons thus destroying the orange box shadow

exactly. As said above this is due to this precise line

https://github.com/ubuntu/yaru/blob/ba2f5d078f43ed1bab7fc5bd908dc70b7793df69/gtk/src/light/gtk-3.20/_common.scss#L1101

**Comment by clobrano** [comment]
Maybe I wasn't clear. What I wanted to say is that a possibile solution for both this issue and #1188 is:

1. revert #1188
2. remove the line in `%jet_popover_button` that sets box-shadow to none

I tried this change for a while and I couldn't find any regression so far

**Comment by Feichtmeier** [comment]
I do the 1. 
But I am really not sure about the 2.
