### ISSUE TITLE
Tilix yaru scheme

### ISSUE THREAD

**Issue by 3v1n0** [ubuntu/yaru#1270]
Hey, anyone would like to create a yaru scheme for Termix?

https://github.com/gnunn1/tilix/tree/master/data/schemes :)

**Comment by madsrh** [comment]
Yes! ...but I don't know how to create a PR for that.

Thanks to [this handy tool](https://github.com/clobrano/raffaello) by @clobrano this is what I've got: 

```
{
    "name": "Yaru",
    "comment": "Yaru Color Scheme",
    "use-theme-colors": false,
    "foreground-color": "#ffffff",
    "background-color": "#300a24",
    "palette": [
        "#2E3436",
        "#CC0000",
        "#4E9A06",
        "#C4A000",
        "#3465A4",
        "#75507B",
        "#06989A",
        "#D3D7CF",
        "#555753",
        "#EF2929",
        "#8AE234",
        "#FCE94F",
        "#729FCF",
        "#AD7FA8",
        "#34E2E2",
        "#EEEEEC"
    ]
}
```

**Comment by clobrano** [comment]
Nice :+1: 

![image](https://user-images.githubusercontent.com/2883614/54498953-3559f080-490d-11e9-982c-172ebd7e2183.png)

I think I can make the PR for you, if you like. Otherwise those are the steps

1. Fork tilix repo (it will make a copy in your github page)

![image](https://user-images.githubusercontent.com/2883614/54498979-6f2af700-490d-11e9-8565-35827d54f4a8.png)

2. clone your copy
3. add the schema file to your copy
4. commit the change

at this point, in your repository will appear the button "Make a PR"

**Comment by madsrh** [comment]
Upstream PR merged :tada:

**Comment by yerbestpal** [comment]
This theme doesn't seem to be present in the build available from the Ubuntu repositories.
![bug](https://user-images.githubusercontent.com/15250241/88468088-82bd7900-ced6-11ea-9a1b-6cbf5304c54a.jpg)

**Comment by clobrano** [comment]
Hi @yerbestpal, yes indeed. According to Tilix commit history @madsrh's yaru scheme was added to Tilix 1.9.3, while Ubuntu repos still have 1.9.1. I don't know why it hasn't been updated

**Comment by clobrano** [comment]
With the help of Ubuntu team, we saw that:
1. Tilix version is actually 1.9.3, they just forgot to update the number inside Tilix source code
2. Yaru color scheme is ignored by Tilix build script, we can propose a PR for that on Tilix project

Thanks @yerbestpal to point this out!
