### ISSUE TITLE
Missing icons: categories

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1311]
![image](https://user-images.githubusercontent.com/15329494/56680287-498ccc80-66c7-11e9-9feb-bfa1984515fc.png)

Our categories:
![Screenshot_20191105-091836_Samsung Internet](https://user-images.githubusercontent.com/15329494/68190424-a7bb3600-ffad-11e9-8311-a50758815e77.jpg)

Adwaita's categoties, including emoji categories:
![image](https://user-images.githubusercontent.com/15329494/56680626-e5b6d380-66c7-11e9-8911-f46315aa3853.png)

All icons not viewable in gnome-software are pretty optional and kind of "bonus" if you have time @ubuntujaggers :)

(+ "-symbolic" excluded)
- [x] preferences-system
- [x] system-help
- [x] applications-utilities
- [x] applications-science
- [x] applications-engineering
- [x] preferences-other
- [x] applications-games
- [x] applications-graphics
- [x] applications-multimedia

Edit: removed emojis from the list as this is pointless to redraw

**Comment by ubuntujaggers** [comment]
There are a few oddities here - the glyphs in the software store categories come from a mix of places (e.g. the communication/news symbol is taken from "status" and the productivity one is taken from "apps").  In my working branch, I've got them all showing as Yaru designs now:

![image](https://user-images.githubusercontent.com/38893390/56776118-622ddd00-67c2-11e9-8ddb-0aafa4e0b713.png)

...but I welcome thoughts on whether this represents an improvement here, because the 1px grey lines look a bit insubstantial next to the bold dark text.

Also: I was going to change the cog under "categories" to match the one we have in apps for settings, but I think the categories one actually looks better in the shell.  So I changed the apps one to match the categories one instead.

Current cog in the shell:

![image](https://user-images.githubusercontent.com/38893390/56776182-b20ca400-67c2-11e9-9d09-9e254a774109.png)

...and this is what it looks like if we make the settings-app symbol the same as the cog under categories:

![image](https://user-images.githubusercontent.com/38893390/56776195-cea8dc00-67c2-11e9-8706-30ab68bb0b2d.png)

Again, I welcome thoughts on this change!

**Comment by clobrano** [comment]
New symbols in software look very nice, good work!

> ...but I welcome thoughts on whether this represents an improvement here, because the 1px grey lines look a bit insubstantial next to the bold dark text.

From my point of view, those thick colored lines look bad in any case, but we can't change them :)

**Comment by Feichtmeier** [comment]
@ubuntujaggers awesome work btw!

For some reason in 18.04 (which becomes less and less important ofc) the addons icon is still the old one:

![image](https://user-images.githubusercontent.com/15329494/56951284-ad841a80-6b37-11e9-86af-f22ed20bc810.png)

**Comment by ubuntujaggers** [comment]
Education and Science was already picking that icon up from Yaru, I'd definitely prefer a test tube if we can work out how to do it without making Help a test tube too!

**Comment by Feichtmeier** [comment]
@ubuntujaggers 
found some more in the new snap store which is some gnome-software variant by ubuntu only for snaps
![grafik](https://user-images.githubusercontent.com/15329494/58666613-1d9edf80-8334-11e9-9b24-da6334b4722b.png)

**Comment by ubuntujaggers** [comment]
👍 

I will do these tomorrow evening  :)  and from that point on I'll be back in business.

**Comment by Feichtmeier** [comment]
@jhenstridge hi could you give us a hint why the snap store has some icons missing?

**Comment by Feichtmeier** [comment]
@ubuntujaggers updated the screenshot from our current master. There are still some categories icons missing I think just from counting the little pictures xD.
(Excluding emojis)

**Comment by ubuntujaggers** [comment]
Hmm, I had some problems last time I tried to do this issue, but it really needs finishing... thanks for the investigation 👍 and I'll start looking at this again tonight.

**Comment by ubuntujaggers** [comment]
How about this for utilities/Swiss army knife:

![image](https://user-images.githubusercontent.com/38893390/70559673-082a2e00-1b7f-11ea-95c0-9370a99b4d2d.png)

I'll do a PR as soon as we're done with the batteries to avoid conflicts.

**Comment by ubuntujaggers** [comment]
And maybe something as simple as this for preferences-other?

![image](https://user-images.githubusercontent.com/38893390/70562139-b932c780-1b83-11ea-826c-dcf45320552b.png)
