### ISSUE TITLE
Yaru-dark - can't see ratings in Ubuntu Software

### ISSUE THREAD

**Issue by alanpaulprice** [ubuntu/yaru#1367]
I'm trying to view package ratings in Ubuntu Software.
It is difficult to see the ratings, as the empty and full stars are very similar in colour.

![yaru-dark-issue](https://user-images.githubusercontent.com/23743415/57929249-adf81180-78aa-11e9-8bb7-cb2714c3357f.png)

**Comment by Feichtmeier** [comment]
I remember that we've chosen this weird way to style the stars because their colour was hardcoded
Could be wrong though
I'll check it again

**Comment by madsrh** [comment]
Just a crazy and maybe hacky idea; If only the stars are hardcoded but not the white background, maybe we could change the background color to match the color of the inactive star. Not sure if this is an improvement though 😄 


![image](https://user-images.githubusercontent.com/3986894/58290590-98a74980-7dba-11e9-8601-bd8b3ae785a3.png)

**Comment by clobrano** [comment]
Yes, it is an hadcoded color, more than image
![image](https://user-images.githubusercontent.com/2883614/58309260-0deb3c80-7e04-11e9-90f0-79365af3ac33.png)

adwaita-dark does something similar to @madsrh suggested
![image](https://user-images.githubusercontent.com/2883614/58309323-33784600-7e04-11e9-95e8-afa340f66193.png)

**Comment by Feichtmeier** [comment]
Oh man they can't be serious... Can't we open an issue on gitlab about this? Why would you hardcode such a star colour? :D

**Comment by Feichtmeier** [comment]
You can change it in the gtk inspector to for example white
![Screenshot from 2019-05-25 13-07-17](https://user-images.githubusercontent.com/15329494/58368493-220b6880-7eee-11e9-9db1-c2c904a2d9ae.png)

but not in the real css file

@madsrh idea could work, but we need to exclude disabled star boxes otherwise it is just a bar
![Screenshot from 2019-05-25 13-18-05](https://user-images.githubusercontent.com/15329494/58368618-998dc780-7eef-11e9-8ab2-9e310efd062f.png)

**Comment by Feichtmeier** [comment]
Now after upstream refresh we need to fix that in gnome software upstream. They hard code the star colour

**Comment by Feichtmeier** [comment]
Does not happen anymore after rebasing master from upstream:

![image](https://user-images.githubusercontent.com/15329494/63252342-ede6e000-c26f-11e9-9ad1-456bc4fb836a.png)
