### ISSUE TITLE
Provide a 'dark' and a 'light' color $variant

### ISSUE THREAD

**Issue by memeplex** [ubuntu/yaru#1391]
Shell popups (for example, confirmation to shutdown the system) are not consistent with the dark variant of Yaru. This is a minor issue but still notorious.

## Expected Behavior

Consistent colors both for gtk widgets and gnome shell components.

## Actual Behavior

Some gnome shell components are still light and, in fact, there is no dark variant for the shell theme (only for gtk).

**Comment by Feichtmeier** [comment]
This "inconsistency" It is actually this way by design, because dark notifications look bad on dark headerbars :)

HOWEVER! We are currently using the $variant: 'dark'

With the next gnome shell theme upstream version there will be also a $variant: 'light'
We will follow this trend and provide both versions, but it looks like we still need to decide on which we use by default, because currently there is no way to toggle the variant.

**Comment by Feichtmeier** [comment]
Would be great to get the others involved

@madsrh @clobrano @ubuntujaggers 
Currently we are using in the code the 'dark' variant of the shell theme, like current upstream master does.
But then we are painting the notifications and dialogues to be bright because it looks better this way (many threads about this, those interested could read up the whole repo xD)
Upstream plans to get both variants ready to be used and you can switch between a light and a dark shell by changing the $variant to be 'dark' or 'light' and there isn't yet a GUI way to do it.
Being ready in Yaru for this is no problem but then we need to decide which version should be the standard for Ubuntu? A dark shell or a light shell? OSD would stay dark by the way (also in upstream)

**Comment by madsrh** [comment]
We spent a lot of time testing the options - they both look good. Wouldn't it make sense to just follow upstream here? 🤔 I don't have a strong opinion about this (for now 😁 )

**Comment by memeplex** [comment]
For Adwaita they provide both variants but, since there is no GUI to toggle between them, they just add an Adwaita-dark stub that gets listed in the theme drop-down in Tweaks.

**Comment by Feichtmeier** [comment]
yes. we also have yaru-dark. but I thought this issue is about the shell? no?

**Comment by memeplex** [comment]
Yes, I was suggesting to do that for the shell since there is no toggle for the variant. Maybe it makes no sense, I don't know.

**Comment by clobrano** [comment]
> For Adwaita they provide both variants but, since there is no GUI to toggle between them, they just add an Adwaita-dark stub that gets listed in the theme drop-down in Tweaks.

Correct, but what you can tweak in Tweaks is only the part that affects how applications look like, not Shell elements like notifications and dropdown menus.

The only actual improvement (except look&feel I mean) of a bright Shell, is that notifications are way more visible now. I tend to not notice them on adwaita shell. As Mads said of course dark shell looks good too.

**Comment by memeplex** [comment]
You can tweak the shell theme with the User theme extension, which is rather "official".

**Comment by Feichtmeier** [comment]
Alright so I finish my upstream shell theme contribution and then base our next theme on that work (ofc exchanging colors, boder-radii and other stuff we designed in the past cycles) so we will then have a full dark theme and a full light theme.
Then we can still decide if we want to hardcode the bright notifications even in the dark theme :)

**Comment by Feichtmeier** [comment]
Done with new master upstream refresh! Thanks for reporting

(There is just no dark/light theme toggle currently implemented in the shell - but the theme is ready and uses the light shell theme by default now)
