### ISSUE TITLE
Yaru Dark Theme: Transparent input boxes have the same color as background

### ISSUE THREAD

**Issue by dawoodjee** [ubuntu/yaru#1411]
## Expected Behavior

Yaru Light shows properly:

![image](https://user-images.githubusercontent.com/7912989/59765795-203f8580-929f-11e9-9b4a-29367f640354.png)

## Actual Behavior
Same text is hidden in Yaru Dark:

![image](https://user-images.githubusercontent.com/7912989/59765908-61d03080-929f-11e9-897a-766b8e8183a9.png)

## Steps to Reproduce the Problem

Ubuntu 19.04 (Maybe 18 as well)
  1. Using Ubuntu tweaks > Appearance > Application: Select Yaru Dark
  2. Open Firefox and any page with input field with transparent background, e.g Search bar on https://keep.google.com
  

## Specifications

Software that presents the issue:
- OS Ubuntu 19.04
- Name: Firefox (default)
- Version: 67.0

Note
- The issue is independent of the browser Theme used.

**Comment by clobrano** [comment]
Hi @dawoodjee, 
thank you for contributing to Yaru! I just have a try with Adwaita-dark and some other dark variants and the problem is the same.
In this regard is Firefox wrongly picking the colors from our palette, using a custom background color for the entry, but not a custom color for the text as well.
