### ISSUE TITLE
Tabs in use are not visible in Libre office with Yaru-Dark

### ISSUE THREAD

**Issue by Watchstoptime** [ubuntu/yaru#1445]
Hello I don't really know where to sned my request or my "bug report" either here or either to Livre Office Community . I've tried the last version of LO 6.3 with the communitheme or Yaru theme on my Ubuntu 18.04. 
I've noticed a slight display bug while using it with the Yaru dark theme. 
As you can see below (3 screenshots) on the white version you can see that the I'm using the tab "insert" (insérer in French). The tab in use in a bit more emphasized or underlined that the others to show that the tab is in use. 
If we check the same set but with the dark-yaru we could see that this difference is not anymore visible, thought we don't see anymore the difference between idles tabs and the used tab. 
I do think that this issue is link to the theme and not the the distro because when I do the same with the Adwaita-dark theme the tab in use is more visible and we can see more clearly the buttons on the bar. 

Screeshots : 
(1) LO with the default Yaru theme (light grey or white)
[http://pix.toile-libre.org/upload/thumb/1565474109.png](url)
(2) LO with Yaru-dark
[http://pix.toile-libre.org/?img=1565474175.png](url)
(3) LO with Adwaita-dark
[http://pix.toile-libre.org/?img=1565474175.png](url)
Does anybody know how to fix that? thank you so much.

Thank you for your help.

**Comment by clobrano** [comment]
Hi @Watchstoptime,

thanks for reporting this here as well. I am referring to the post on the Ubuntu discourse forum https://discourse.ubuntu.com/t/yaru-next-move/12155/15 because the links above do not bring to the actual pictures. You can simply paste the pics in the message https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests

So, from the pics in the Ubuntu discourse, Adwaita-dark and Yaru-dark looks the same and probably because they are the same, in some old releases yaru-dark was not shipped and adwaita-dark was used instead. Under Adwaita, the tab is show with a blue underline, as it seems in the pics you posted. We proposed our tab style upstream, but the adoption is still under discussion so this "underlined tab" will be the next future in Yaru as well (but orange, not blue)
