### ISSUE TITLE
WIP: Missing humanity/ubuntu-mono-dark icons

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1468]
- [ ] 1) List all the icons with exact names and a note of they are a file or a symlink, link symlinks to the files
- [ ] 2) Provide the missing icons

**Comment by Feichtmeier** [comment]
After looking at the amount of icons and/or symlinks needed for this we agreed on not doing this.

Those legacy icons are only use for legacy apps or apps that use legacy design. Thus those need to take the legacy icon set then!
Sorry!

**Comment by madsrh** [comment]
Hello @ubuntujaggers @gusbemacbe @friendlyapple @wfpaisa

I would anyone be willing to take on the HUGE task of updating legacy icons???

Yesterday I was looking into replacing the `zoom-in` icon that we inherit from Adwaita. Suru++ uses the symbolic icon which look great but that the downsides that it's monochrome and that it isn't visible in the dark theme.

**Inkscape with Yaru icon theme that fallsback to Adwaita:**
![image](https://user-images.githubusercontent.com/3986894/74588111-20dd1700-4ffa-11ea-8229-ec6be155ecfc.png)

**Suru++**
![image](https://user-images.githubusercontent.com/3986894/74588143-571a9680-4ffa-11ea-8883-e6af0a917bee.png)

**Suru++ in dark theme:**
![image](https://user-images.githubusercontent.com/3986894/74588219-eaec6280-4ffa-11ea-84b7-91314d952140.png)

**Numix icon theme:** Some are fixed but not all icon
![image](https://user-images.githubusercontent.com/3986894/74588253-10796c00-4ffb-11ea-94c0-dcfc29256e46.png)

**Papirus icon theme has a dedicated dark icon set:**
![image](https://user-images.githubusercontent.com/3986894/74588496-5a635180-4ffd-11ea-8206-4387a2b56025.png)


Of course I'm not just keen to fix the zoom but as many icons as possible and I know that it's a tremendously task and that these are considered legacy BUT there's a ton of popular applications using these.

I know that there's a few Suru / Yaru icon theme derivatives and because these would benefit from us adding these icons, perhaps _(I'm hoping/wishing)_ they will be interested in collaborating and fixing this here in Yaru so it can float downstream. What do you think @gusbemacbe?

**Comment by Feichtmeier** [comment]
Would be great if you could start with an exact list of the missing icons @madsrh :angel:

**Comment by Feichtmeier** [comment]
Superseeded by #1965
