### ISSUE TITLE
The headerbar buttons lack of contrast compared to the background

### ISSUE THREAD

**Issue by seb128** [ubuntu/yaru#1477]
(Sorry if it's something discussed before but I couldn't find a reference to it.)

The action buttons in headerbars are not really easy to see (it's partially fault of the upstream design but Yaru has even less contrast between the bg and buttons than adwaita). The issue was discussed on the desktop IRC channel in the context of current eoan and gnome-control-center/display and some team members couldn't find the display/night mode selector at the top of the page, it's not specific to that panel though (the 'select image' in the background panel for example has the same issue)

Is there anything that we could do to make those more easy to spot for users?

**Comment by Feichtmeier** [comment]
Yes, we could lighten up the headerbar color for example.

**Comment by clobrano** [comment]
Hi @seb128, is the night mode selection coming from a new version of control-center? I could not see it, either because of this same issue or because I have a previous version of g-c-c :)

**Comment by seb128** [comment]
@clobrano it was moved to the headerbar in the current GNOME unstable serie so it's only in eoan, the button have a visible border/text but the bg color is pretty similar to the bg so they are not invisible just lacking contrast. I'm currently on another laptop but I will send a screenshot a bit later

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/63944281-8b60c180-ca71-11e9-8cc5-fee9f961812d.png)

![image](https://user-images.githubusercontent.com/15329494/63944319-9a477400-ca71-11e9-9916-df0357f08c8d.png)

This is 3% lighter
:man_shrugging: 
Looks less sexy, but more easy for the eyes, IMHO

**Comment by clobrano** [comment]
What's the exact color? I was testing something similar, making a palette from our base HB color #2b2929 and using a ligher one #3E3C3C (for both headebar and top panel)

![image](https://user-images.githubusercontent.com/2883614/63945113-168e8700-ca73-11e9-9ac9-a5cdb5534c7e.png)

**Comment by Feichtmeier** [comment]
The new one is

#333030

The old one is

#3d3a3a

**Comment by clobrano** [comment]
> #333030 (lighten(#3d3a3a, 3%) )

uhm, why #3D3A3A? Headerbar is #2B2929. Anyway, it would be cool to have the same g-c-c to test it locally, otherwice I can open a new PR for testing

**Comment by Feichtmeier** [comment]
It's definitely 2b2929, no idea what I had in the copy when I pasted

**Comment by seb128** [comment]
Just for reference that's a g-c-c headerbar today without change

![headerbar](https://user-images.githubusercontent.com/10974330/63954377-4f365c80-ca83-11e9-80ba-57f753d84e7c.png)

**Comment by seb128** [comment]
(oh and it does look better/more visible on the screenshot with an external screen, so probably the low quality screen of my test laptop doesn't help there...)

**Comment by clobrano** [comment]
Thanks @seb128, that's the stackswitcher button, I can test it elsewhere without installing the new g-c-c :+1:

**Comment by clobrano** [comment]
here gtk3-widget-factory with a similar stackswitcher button and proposed new hb color

![image](https://user-images.githubusercontent.com/2883614/63955829-a50c0400-ca85-11e9-9114-3e4b08a1226f.png)

**Comment by Feichtmeier** [comment]
The pressed buttons have also more detail like this. You can distinguish what's the shadow and what's the border which results in a sharper button.

**Comment by seb128** [comment]
It looks fine but what if option 1 is selected? it still feels like the selected and bg color are quite close

**Comment by clobrano** [comment]
> It looks fine but what if option 1 is selected? it still feels like the selected and bg color are quite close

![image](https://user-images.githubusercontent.com/2883614/63957350-80fdf200-ca88-11e9-90b3-83118c2e1bcd.png)

I can try to mockup a version with a different pressed button color

**Comment by seb128** [comment]
Thanks, I'm probably not the best to comment about the tweaks since I usually don't have a good eye for such details, it doesn't look obvious to me that there are buttons in the bar still but I think it's mostly GNOME's design fault for putting buttons in an usually location... I'm off next week but maybe @8none1 and @didrocks have an opinion on the topic

**Comment by 8none1** [comment]
To be brutally honest, they all kinda look the same to my eyes.  

The discovery of those buttons in the header bar isn't great, does it warrant a more significant change to make it more obvious?

**Comment by clobrano** [comment]
I am probably a bit biased, since I see them all day and I lost the "first sight" effect.
Previously the stackswitcher buttons had light borders we cannot reproduce in this version, because of the 3D effect, which is evidently too subtle with a "crazy dark" (cit.) headerbar color :)

Just to focus on the problem:
- is it hard to spot the normal buttons from the headerbar background?
- is it hard to spot the normal buttons from the pressed one?
- all the above?

**Comment by clobrano** [comment]
In the meantime, here are some mockups where I try to work on button borders, making them more visible.
It might look a bit exaggerated, but I'm trying to consider all the different light conditions and probably it'd be faster if I shot higher and then refine :)

Software center
![image](https://user-images.githubusercontent.com/2883614/64005059-d8937080-cb0f-11e9-8c20-b675b5aac2da.png)


Boxes
![image](https://user-images.githubusercontent.com/2883614/64004970-b0a40d00-cb0f-11e9-9d1a-18bf376647ad.png)

Nautilus
![image](https://user-images.githubusercontent.com/2883614/64004994-bc8fcf00-cb0f-11e9-9654-f62eeb8f4988.png)

**Comment by clobrano** [comment]
Here the new g-c-c on Eoan 

![image](https://user-images.githubusercontent.com/2883614/64016657-e3f29600-cb27-11e9-9ef4-bb7da9a7b7f2.png)

**Comment by clobrano** [comment]
To avoid messing up with the discussion, I'm collecting the mockups

here https://paper.dropbox.com/doc/Headerbar-button-review--Aj3giatD9eqflHWxVIclGzkCAg-LNYRgSOLjZpVsWfWbTOXP

**Comment by Feichtmeier** [comment]
Another option would be to drop the dark headerbar in the light theme, and rely on the upstream look for the headerbar, which drops a lot of distinctive previous yaru/ubuntu design/look, but adds great usability imo:

![Screenshot from 2019-08-31 10-18-44](https://user-images.githubusercontent.com/15329494/64061305-69824e80-cbd9-11e9-8fc1-bb3af512408c.png)

![Screenshot from 2019-08-31 10-19-50](https://user-images.githubusercontent.com/15329494/64061306-6a1ae500-cbd9-11e9-9d72-d538a104061f.png)

![Screenshot from 2019-08-31 10-20-44](https://user-images.githubusercontent.com/15329494/64061307-6a1ae500-cbd9-11e9-89ae-0d8e621a957b.png)

![Screenshot from 2019-08-31 10-24-03](https://user-images.githubusercontent.com/15329494/64061318-7c951e80-cbd9-11e9-9083-dd08115fe3e4.png)

(I need to re-add flattening of the checks/radios though)

**Comment by 8none1** [comment]
> To avoid messing up with the discussion, I'm collecting the mockups
> 
> here https://paper.dropbox.com/doc/Headerbar-button-review--Aj3giatD9eqflHWxVIclGzkCAg-LNYRgSOLjZpVsWfWbTOXP

I like version 7!
That addresses my main concerns I think.

**Comment by 8none1** [comment]
@Feichtmeier I think a dark theme with a light header bar detracts from the main point of the dark theme.  Just my 2 cents, but I don't think it works.  I like version 7 above best.  (Just my opinion)

**Comment by clobrano** [comment]
Short update after discussing with team and on  IRC, this is the latest update, on disabled button

![image](https://user-images.githubusercontent.com/2883614/64108636-9bccb100-cd7d-11e9-91c8-6f586e2a1007.png)

- no borders
- less visible label

**Comment by clobrano** [comment]
> @Feichtmeier I think a dark theme with a light header bar detracts from the main point of the dark theme. Just my 2 cents, but I don't think it works. I like version 7 above best. (Just my opinion)

I think @Feichtmeier wanted a gray headerbar on the light theme and the dark one on the dark variant

**Comment by Feichtmeier** [comment]
Yes, like upstream and elementaryOS. Fully light and fully light theme.

**Comment by Feichtmeier** [comment]
@8none1 @seb128 

Upstream uses a fully light gtk or a fully dark gtk theme.
We basically use the same files as upstream does, but make use of global variables for the sizing of the headerbar and the rounding of widgets. Those variables are inside of the upstream files and no additions. 
Yaru now uses a fully light and a fully dark gtk theme from the build we use but then also apply an inversion of colour for the headerbar for the light theme here:
https://github.com/ubuntu/yaru/blob/master/gtk/src/light/gtk-3.20/_tweaks.scss

Also other changes are applied, like removing strong text shadow or flattening the checks/radios.
Also fixes for the switches, that are drawn with scss code from https://github.com/ubuntu/yaru/blob/master/gtk/src/light/gtk-3.20/_drawing.scss#L228

_Now this following comment is my opinion alone and I don't speak for the yaru team because we strongly disagree here:_

Remember the osd styled popovers in the dark gtk theme? I loved them really. But they are broken by design (it was my idea -.-) because they are just **containers** where **everything** can be inside. And they are really starting to put everything inside popovers, including many custom widgets. 
So as soon as some fancy gtk app developer puts a new widget into it which looks up the exported colours we just talked about at guadec, it will be broken. The same thing can happen to the dark headerbar.

These are the public colors which we also use because, as already said, we use the upstream code:

https://github.com/ubuntu/yaru/blob/master/gtk/src/light/gtk-3.20/_colors-public.scss#L10

If an gtk app dev wants to look up public colors /exported colors they look up for these variables. Those variables are bound to a fully light and a fully dark theme. This means, if the system uses a light theme and we have a dark headerbar in the light theme, the app dev will make use of a text color and a background color of the light theme. Meaning basically "black text on white background". Ofc this will then be not visible inside the dark headerbar, creating basically an issue or an unthemed state.

This is ofc not directly addressing to your initial issue, but using full light and full dark themes would also help here because, as you can see from the screenshots, the upstream code already checks the contrast of buttons in the headerbar. So this would be a good opportunity to use the fully light theme, even if it does not answer our design wishes.

There are things planed for the exported / public colours. That might include headerbar colors. So when a theme has a custom widget in the headerbar (for example gnome builders big centred widget) looks up something like ```@theme_headerbar_fg_color``` it finds the correct headerbar color and not the fg color of the rest of the theme.

**Comment by Feichtmeier** [comment]
> 
> 
> Short update after discussing with team and on IRC, I will try to improve the disabled button in order to made them look less "actionable". This is a possible solution
> 
> ![image](https://user-images.githubusercontent.com/2883614/64108636-9bccb100-cd7d-11e9-91c8-6f586e2a1007.png)
> 
>     * no borders (or lighter ones)
> 
>     * less visible label

Please do not remove any borders, as this might cause issues.

**Comment by Feichtmeier** [comment]
Reminder for everyone additionally to the risk of inverting the colours: please realize that the headerbar is part of the very toolkit the rest of the apps use. So it would be probably desirable to make it look exactly like the rest of the app. It should not look alien in any way. That's the reason why drawing does not differentiate where the widget is drawn. Special casing certain widgets should be really avoided.

**Comment by ubuntujaggers** [comment]
Hi guys, sorry for delay. Here are my thoughts.

I'm a big fan of the original dark headerbars - to me they look dark and cool. I think we lose that if we lighten them to the point where they look "grey" rather than "dark". Some of the latest ideas look nice in screenshot, but when I try the branch for real it looks a bit drab. I think, if we have to lighten them that much for usability reasons, I actually prefer Frederik's fully-light headerbar concept (at least when I try the different options for real on my desktop). Also, I certainly prefer Frederik's concept to vanilla Adwaita (by a big margin), even if it's a radical change that takes some getting used to. I think it will be less jarring if we can get back to Cosmic-style transparencies for the desktop header and launcher.

This surprises me because I love the classic Yaru look and really appreciate the work Carlo is doing to try to fix this issue without abandoning the dark headerbars. So hopefully a good answer can still be found.  I just prefer all-light windows to the medium grey-ish headers after trying them both in recent days.

**Comment by Feichtmeier** [comment]
For reference, the yaru which still lives on in the bionic branch has the advantage of relatively bright gray borders - but they only really look good if you make the headerbar flat:

![grafik](https://user-images.githubusercontent.com/15329494/64233761-37ccf880-cef5-11e9-9b80-8df81435e77a.png)
![grafik](https://user-images.githubusercontent.com/15329494/64233785-44e9e780-cef5-11e9-8e07-b4bc11be6732.png)


Ambiance had the dark headerbar, too but buttons work a lot different. They are really, truely 3dish looking (which is unquestionable out of style) and the headerbar color is different:

![grafik](https://user-images.githubusercontent.com/15329494/64233635-ee7ca900-cef4-11e9-8fd4-9807221c6c57.png)

- on a sidenote, was this still a "light" theme? Wouldn't it be easier to default to yaru-dark if a dark look is wanted as default? Then we could give the yaru light look to the users who use ubuntu in a bright room or just prefer a pure light theme (aside from the risk-to-break-dodging I described above)

**Comment by Trine4** [comment]
I agree with @ubuntujaggers. The black headerbar is Yaru's identity. It would be a pity to lose it. Personally, I find that version 5 is a good compromise.
![image_preview](https://user-images.githubusercontent.com/34983829/64233955-93978180-cef5-11e9-9439-5441ff38e1e6.png)

**Comment by madsrh** [comment]
I'll give my 2 cent here too 😃 

Regarding this initial issue of this bug, I still find [version #7](https://github.com/ubuntu/yaru/issues/1477#issuecomment-527092307) to lack of contrast compared to the background (although it's much improved). I would like to see an obvious color/contrast difference between headerbar and buttons. It's not as slick as that cool, sexy, chocolate look we aimed for with Yaru, but it's good UX.

![image](https://user-images.githubusercontent.com/3986894/64235035-d0fd0e80-cef7-11e9-8383-5ef2bd503941.png)

IMHO this would fix this issues, BUT @Feichtmeier raised some very valid points. 
I agree that the dark headerbar is a big part of Ubuntus identity / recognizability (we've had a dark headerbar since 4.10!) but that's not a good reason for sacrificing usability and shipping something we know will cause bugs. The fully-light headerbar concept @Feichtmeier presented is a much safer solution, although it's a big change. Ofc the best solution would be, if upstream supported colored headerbars 😉

**Comment by Feichtmeier** [comment]
I would like to summ up my problems with the mixed theme:

1) Gtk is not ready for an inverted headerbar as described [here](https://github.com/ubuntu/yaru/issues/1477#issuecomment-527112435)
2) in a normally lightened room at day the dark headerbar is worth usability wise than a normal headerbar. That's why basically all plattforms or toolkits use a full light or a full dark version for night and day
MacOS as an example:
![osx](https://user-images.githubusercontent.com/15329494/64243868-5ee0f580-cf08-11e9-961b-676f00f7c256.png)
3) Addressing the initial issue, we need to lighten up the buttons to have a good contrast to a point where they look almost gray, what's the point then to invert the colors?
4) Looking at the history of the ubuntu theme, I've noticed that the dark **title** bar was introduced in 10.04 with the colors ambiance used until 18.04, a window without a titlebar and only with a gtk headerbar, which is basically a box which can also have titlebuttons (client side decorations)
So imho this long history of a dark headerbar is basically an illusion :)
![Bildschirmfoto-20190904114007-657x448](https://user-images.githubusercontent.com/15329494/64244438-5a690c80-cf09-11e9-94fb-025d9e141bd0.png)

Full light/dark themes could also be expected from fancy kids only using android and osx:
![darklight](https://user-images.githubusercontent.com/15329494/64244564-93a17c80-cf09-11e9-8631-c2bde312bf73.png)
![lightdark](https://user-images.githubusercontent.com/15329494/64244565-93a17c80-cf09-11e9-9942-eae5fd01a106.png)

**Comment by DarthWound** [comment]
Ah, I wanted to submit a similar issue since a long time, but thought it would be a big NO.

An optional "fully light" is really something that I miss, I like Yaru theme but the dark headerbar blends into the panel too much, I had to customize the top bar to improve contrast/efficiency by making it somewhat always transparent, but it's ugly, I don't mind dark panel `#1d1d1d` honestly it is perfect, what I need is a light GTK. And it seems that a lot of users want the same.

I understand that the dark headerbar is part of Ubuntu's identity, it's why I say "optional". But nowadays headerbars are totally part of the window, IMO it makes less sense than years ago when we had real titlebars where a separation was quite needed.

If sadly it never happens, I hope that someone will upload a light Yaru in GNOME-Look or GitHub/GitLab anyway.

PS: instead of pure grey, maybe a "sepia" tint like what we have in Adwaita could do the trick, it would look like Radiance.

**Comment by dgutov** [comment]
> In a normally lightened room at day the dark headerbar is worse usability wise than a light headerbar

Exactly.

> Full light/dark themes could also be expected from fancy kids only using android and osx

I find it annoying and rather sad that most of the "full light" themes I found on gnome-looks are copies of some OSX theme or other. Even to the point of adding Apple's logo somewhere. I don't want to see that logo. And I really hope Linux desktop can still learn from other platforms who obviously invest in usability research a lot of money.

**Comment by real-amano** [comment]
A full light theme - though not being the default - comes with every Ubuntu install. It is called Adwaita and just some mouseclicks away.

Now I have the choice between Adwaita (full bright), Yaru (rather bright) and YaruDark (well, dark). With the proposed changes I have the choice between Adwaita, something really close to Adwaita and Dark.

**Comment by Feichtmeier** [comment]
Uhm, the current theme IS already very close to adwaita. But we are inverting the headerbar color. Reasoning why this is bad design is summed up [here](https://github.com/ubuntu/yaru/issues/1477#issuecomment-527827768)

We  made some changes to the light theme, currently it looks like this (many pictures incoming):

![Screenshot from 2019-09-05 07-19-10](https://user-images.githubusercontent.com/15329494/64419062-1e00f200-d06a-11e9-9cd7-e6060a73f898.png)
![Screenshot from 2019-09-06 05-12-38](https://user-images.githubusercontent.com/15329494/64419063-1e998880-d06a-11e9-8680-d77986910b9f.png)
![Screenshot from 2019-09-06 05-14-56](https://user-images.githubusercontent.com/15329494/64419064-1e998880-d06a-11e9-8e4c-193410bb5728.png)
![Screenshot from 2019-09-06 05-16-07](https://user-images.githubusercontent.com/15329494/64419066-1e998880-d06a-11e9-8581-986bb16bc13d.png)
![Screenshot from 2019-09-06 05-16-42](https://user-images.githubusercontent.com/15329494/64419067-1e998880-d06a-11e9-9722-46b473967508.png)
![Screenshot from 2019-09-06 05-18-35](https://user-images.githubusercontent.com/15329494/64419068-1f321f00-d06a-11e9-9697-2942f947227c.png)
![Screenshot from 2019-09-06 05-20-52](https://user-images.githubusercontent.com/15329494/64419069-1f321f00-d06a-11e9-92e1-dbadcd59f559.png)
![Screenshot from 2019-09-06 05-21-54](https://user-images.githubusercontent.com/15329494/64419070-1f321f00-d06a-11e9-8f6d-890cf7976fd0.png)
![Screenshot from 2019-09-06 05-22-02](https://user-images.githubusercontent.com/15329494/64419071-1f321f00-d06a-11e9-90c4-88552f79a90c.png)
![Screenshot from 2019-09-06 05-28-54](https://user-images.githubusercontent.com/15329494/64419072-1f321f00-d06a-11e9-80e7-13a0ffa9a90b.png)
![Screenshot from 2019-09-06 05-44-32](https://user-images.githubusercontent.com/15329494/64419073-1fcab580-d06a-11e9-8d55-11ab39758966.png)
![Screenshot from 2019-09-06 05-45-01](https://user-images.githubusercontent.com/15329494/64419075-1fcab580-d06a-11e9-9575-1f947f721085.png)

While the dark yaru theme looks like this:
![Screenshot from 2019-09-06 05-42-35](https://user-images.githubusercontent.com/15329494/64419111-31ac5880-d06a-11e9-9c9d-77eb6b734b94.png)
![Screenshot from 2019-09-06 05-42-51](https://user-images.githubusercontent.com/15329494/64419112-31ac5880-d06a-11e9-9d87-55ca04ba35f5.png)
![Screenshot from 2019-09-06 05-43-05](https://user-images.githubusercontent.com/15329494/64419113-31ac5880-d06a-11e9-86b7-8be7609c211a.png)
![Screenshot from 2019-09-06 05-43-33](https://user-images.githubusercontent.com/15329494/64419114-31ac5880-d06a-11e9-9156-3620e0b7a716.png)
![Screenshot from 2019-09-06 05-43-49](https://user-images.githubusercontent.com/15329494/64419115-3244ef00-d06a-11e9-9151-d965271d4b4f.png)

**Comment by real-amano** [comment]
If preserving the most outstanding Ubuntu colors/accents is not worth it, why forking Adwaita at all? And just shipping Adwaita?

**Comment by clobrano** [comment]
> Reasoning why this is bad design is summed up here 

I wouldn't say it's "bad design", though.

**Comment by real-amano** [comment]
To be a little bit more constructive: 

If this is really going to take the bright headerbar road, can you consider putting at least a "shot" of coffee into it? To retain some of the Ubuntu feel?

**Comment by DarthWound** [comment]
Yeah, as I said a bit of "sepia" colors instead of pure grey would give a better Ubuntu feeling. Maybe playing with the [warm grey tints](https://design.ubuntu.com/brand/colour-palette/)? But I disagree that having a full light theme is the same than default Adwaita, we still have orange accent color and other stuff. I love when distros ship their own branding, especially Ubuntu, but I agree that we shouldn't go too far from upstream. And as we said, dark headerbar has some usability concerns.

And, honestly, I'm pretty sure that if Ubuntu team use a full light theme, you'll be able to download "old" Yaru forks made by people who don't like changes, as always.

Personally I can't wait for the full light theme, I use full dark at night but at day the "hybrid" is painful. If it comes in 19.10 it would be a great birthday gift haha!

**Comment by Trine4** [comment]
@Feichtmeier Wow! As much as I was not a fan of the first version but there with these subtle hues of gray, it's just beautiful!
The green buttons fit better than with the black theme and the orange colors of the sidebar become more pleasant (before it was a bit aggressive).
There is really a sense of detail when you pay attention. In short, I'm ready to leave the dark side to have this beautiful theme :)
Great job! 🎉 

These screenshots are my favorites:

![64419064-1e998880-d06a-11e9-8e4c-193410bb5728](https://user-images.githubusercontent.com/34983829/64480317-b65fb980-d1c5-11e9-9fd5-3ef976e6fbaf.png)
![64419067-1e998880-d06a-11e9-9722-46b473967508](https://user-images.githubusercontent.com/34983829/64480318-b6f85000-d1c5-11e9-85aa-0eb94016e298.png)

**Comment by 8none1** [comment]
I really like the changes in #1493.

**Comment by seb128** [comment]
Sorry for the delay commenting back since I was on holidays/offline, great work going through the options, +1 from me for the solution picked, thanks yaru team, I think that's going to be a noticable usability improvement :-)

**Comment by DarthWound** [comment]
Awesome!! Congrats and thanks, can't wait for 19.10 :)

Genuinely asking though, what about using warmer colors than pure cold grey?

**Comment by Kazhnuz** [comment]
Darn, I haven't been fast enough to talk about that before merge, but I wonder if a solution couldn't have been to have a slightly light-orange headerbar color, as a bit of a reminiscence of the "Humanity" theme ? Humanity was a theme really similar to Clearlook, but with Orange tint instead of blue, and especially on the title bar. So it could be interesting to try something kinda similar.

It would cover not inverting the color of upstream (it would just be a custom tint of the headerbar and not being "dark"), while still keeping an Ubuntu-like identity ? I can make some test of what it could look like if you want.

**Comment by real-amano** [comment]
Or a slight hue of coffee color/brown? To retain more of its "warm" identity?

**Comment by clobrano** [comment]
The old brown titlebar wasn't really appreciated if I remember correctly :D

**Comment by DarthWound** [comment]
> The old brown titlebar wasn't really appreciated if I remember correctly :D
If you talk about the Humanity era before 10.04 and Ambiance, you can't imagine how much I loved it :laughing: But yeah I don't think I would be fond of it nowadays. I just hope for a warmer tint than cold grey, but I wouldn't like orange/brown colored headerbars.

**Comment by Kazhnuz** [comment]
> If you talk about the Humanity era (brown, not orange) before 10.04 and Ambiance, you can't imagine how much I loved it laughing But yeah I don't think I would be fond of it nowadays. I just hope for a warmer tint than cold grey, but I wouldn't like colored headerbars.

Maybe for that one inspiration could be Sam Hewitt's old "Humanitary" theme ? ( https://github.com/snwh/humanitary-gtk-theme / https://www.snwh.org/humanitary ). It had a warm feeling that really bring for me that old "ubuntu" feeling, and it would be a good inspiration to brand the headerbar without going too much back to the "dark headerbar" territory.

**Comment by DarthWound** [comment]
> > If you talk about the Humanity era (brown, not orange) before 10.04 and Ambiance, you can't imagine how much I loved it laughing But yeah I don't think I would be fond of it nowadays. I just hope for a warmer tint than cold grey, but I wouldn't like colored headerbars.
> 
> Maybe for that one inspiration could be Sam Hewitt's old "Humanitary" theme ? ( https://github.com/snwh/humanitary-gtk-theme / https://www.snwh.org/humanitary ). It had a warm feeling that really bring for me that old "ubuntu" feeling, and it would be a good inspiration to brand the headerbar without going too much back to the "dark headerbar" territory.

Yeah, but it's too much imho. As I said, something like the [current Adwaita headerbar](https://oscimg.oschina.net/oscnet/dcb051e75c29adfbfaf76ae02b1a2cd2de1.jpg) is enough for me, or we could look at the [warm grey palette](https://design.ubuntu.com/brand/colour-palette/). Honestly, Adwaita with just orange accents instead of blue would be ok. But I love Yaru for sure.

**Comment by Trine4** [comment]
At first I was reluctant with the new clear theme. But the spirit of Ubuntu is still here ... modernized :) The orange color of the side menus fits perfectly with the new theme and the beautiful icons stand out better.
I'm afraid that by tinkering the headerbar, the result is too busy and does not fit well with the desktop of everyone (including wallpapers).

**Comment by madsrh** [comment]
> Or a slight hue of coffee color/brown? To retain more of its "warm" identity?

> ...Honestly, Adwaita with just orange accents instead of blue would be ok. 

We've tried with different shades of brown-ish warmer light headerbars, but always ended up with something close to Adwaita - we don't want that. I think the theme still keeps its identity although the shade we've chosen doesn't exactly scream coffee. It is IMHO very modern, lightweight, clean and unique.
We appreciate all the feedback and we know it's a controversial decision that will have fans and haters, but for now we're giving this approach a try 😃

**Comment by DarthWound** [comment]
No problem, it's almost perfect, good job :) I can't wait for 19.10!

18.04 was excellent, but 20.04 will be the best LTS since a long time.

**Comment by mateuswetah** [comment]
@madsrh and @Feichtmeier  an opinion from an intruder here:
1. I think it's a good move, but also would expect something warmer as proposed by @DarthWound or even a full white approach...
2. But now, without the dark header, I feel that sidebar selected items are "screaming" too much with that orange... I know it's something Adwatia does too, but it feels more relevant than the whole window. Possible solutions would be trying a really bright orange with dark text or a light gray there... not sure.

Anyways, good work there guys!

**Comment by memeplex** [comment]
It could only be fair if you also show in your previewing screenshots a non-headerbar app usually used in dark mode, fully maximized, with you new light theme. For a popular choice: vscode. Then people would also know how awful the new approach could look, despite all the advantages.

**Comment by DarthWound** [comment]
> It could only be fair if you also showed in your previewing screenshots a non-headerbar app usually used in dark mode, fully maximized, with you new light theme. For a popular choice: vscode. Then people would also know how awful the new approach could look, with its dark-light-dark sandwich, despite all the advantages. You might say that's legacy stuff but still that's the way Electron is now. Not to mention many other "legacy" apps.

I don't have any electron app installed, so I can't test, does this work?
`GTK_THEME=Yaru:dark vscode`

If yes, then you can create a custom .desktop file in ~/.local/share/applications/ containing the following line: `exec=env GTK_THEME=Yaru:dark vscode`

_PS: you sound a bit rude, and it's not an issue that you'll meet only in Ubuntu, all distros shipping Adwaita or other light themes are impacted I guess._

**Comment by memeplex** [comment]
It's not my intent to sound rude and I know Adwaita works like that and is shipped out-of-the-box at least by Fedora, that's why I prefer(red) Yaru over Adwaita and I have supported the choice of a mixed-theme over a fully-light one in Discourse and other places.

I also know how to set a different theme by setting the GTK_THEME environment variable.

One thing I'm not being able to do is dynamically changing the variant by setting _GTK_THEME_VARIANT using xprop. Isn't that supported by mutter?

**Comment by DarthWound** [comment]
AFAIK xprop should work, except if you use Wayland session.

If it helps, remember that an optional mixed theme should be available in 20.04 LTS. And as I said in a previous comment, I'm pretty sure that you'll be able to find the old mixed Yaru in GitHub/GitLab/GNOMELook soon because a lot of people don't like changes and will provide the former stuff, as always. You could even try to backup the current one from your PC.

**Comment by memeplex** [comment]
I use X11. It's not xprop what is not working but setting that specific property. I'm asking about this in mutter gitlab.

**Comment by clobrano** [comment]
This seems a bug not related to any theme and only incidentally the mixed theme worked as workaround. I understand the concern, and we are working on a way to provide all the choices our people might like, but this doesn't seem the right place to discuss it
