### ISSUE TITLE
Battery icon looks red, even when the battery is full

### ISSUE THREAD

**Issue by 8none1** [ubuntu/yaru#1531]
In Ubuntu 19.10 the battery icon in the top bar looks red (actually it's orange rgb(245,121,62)) even when the battery is full, e.g. 99%.

The orange colour makes it look like a warning that the battery is low.

**Comment by clobrano** [comment]
thanks @8none1!

@ubuntujaggers, I remember there was a problem for testing the new battery icons, could this be related?

**Comment by chrisjbillington** [comment]
I'm seeing this too, but it is inconsistent. Sometimes it's red, sometimes it's light grey, and one time it even alternated between the two based on whether I had my mouse over the icon or not:
![image](https://user-images.githubusercontent.com/1044087/64971368-97bc8b00-d875-11e9-94ec-29198e666f97.png)

**Comment by ElectricGestalt** [comment]
I just want to add confirmation that this exists for me too. Red color for the battery even at 84% capacity. For me it is always active though, not just on mouse over.

**Comment by Amr-Ibra** [comment]
Upstream adwaita-icon-theme pushed three fixes to the new battery icons, maybe Yaru icons have the same issues:
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/commit/b27915ec8dab2378d467fc423dc806af50c4f4cf
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/commit/9b0641cf1bb4f10d9e0bd79a832a14afbc7ade8f
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/commit/73122bcb907a66c7f0a31f519d3940dd645010f3

**Comment by ubuntujaggers** [comment]
Oh crumbs. These icons do something clever to have dynamic colouring which is a completely new one on me. I will try to understand how the new icons work and fix this straight away. The icons themselves at the higher levels have no colour, but I guess there's some property I have to add to the svg so it knows how to colour them and when.

**Comment by 8none1** [comment]
Have also confirmed that when the battery does get low, the icon is shown in red.
Good stuff!

**Comment by 8none1** [comment]
Please would you update the debian/changelog to include a reference to this LP bug:

https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1844137

e.g.

"LP: #1844137"

**Comment by clobrano** [comment]
I'll open a PR for the new changelog

**Comment by chrisjbillington** [comment]
Unfortunately I'm seeing this issue again with yaru-master (commit 5f73becd). Not sure why, when it did appear to be fixed previously. One thing that has changed is that I'm building the dark variant of the shell theme now, whereas I may not have been before. Here are some screenshots:

Battery is pretty low, but not red or orange in the tray (conflicting with it being red in the menu):

![yaru-battery](https://user-images.githubusercontent.com/1044087/65267321-c2f7e200-dae2-11e9-8991-c07991e96b6f.png)

Battery icon changing colours on mouse over:

![yaru-bat](https://user-images.githubusercontent.com/1044087/65267384-e15ddd80-dae2-11e9-97b5-87cb7d5bdcfd.gif)


Battery not changing colours on mouse over, but colour disagreeing with what's in the menu:

![yaru-battery-2](https://user-images.githubusercontent.com/1044087/65267364-d86d0c00-dae2-11e9-93da-2c92abca9b4e.png)

**Comment by ubuntujaggers** [comment]
Cheers @chrisjbillington - I'll have a look.

**Comment by ubuntujaggers** [comment]
Okay, I'm at a loss.  There aren't actually any icons that look like this in the actual svg files:

![image](https://user-images.githubusercontent.com/38893390/65344654-29a6f980-dbd0-11e9-8386-57e018c11166.png)

![image](https://user-images.githubusercontent.com/38893390/65344677-3a576f80-dbd0-11e9-9544-53fb249f59cb.png)

The corresponding icon svgs are all red (for [!]) and grey with a red level (for the almost empty one).  

![image](https://user-images.githubusercontent.com/38893390/65344816-a0dc8d80-dbd0-11e9-8b23-02c30f868ddc.png)

Normally symbols are grey in the svg but pick up the local text colour.  So, the red elements have an xml class, "alert", which tells Gnome they're meant to be red, rather than recoloured to match the local text.

The only time empty or nearly empty batteries don't have the red (or the associated xml class) is when the laptop is charging, but that's a slightly different icon with a lighting bolt beside it, rather than the colourless symbol appearing in the screenshots.

So, unless there's something else going on that I don't know about, I think there's something slightly wrong (or unreliable) with how Gnome is handling the alert xml class.  Sometimes it respects it and makes the element red, and sometimes it ignores it and colours the element the same as the local text.  Is anyone else experiencing this in master now?

I note that this is a slightly different (IMO not as serious) defect as previous.  Before, fully charged batteries were showing as red sometimes, which is completely wrong.  Now the colour is appropriate when present but occasionally the symbol renders as monochrome.  Doubly weird when hovering changes the behaviour.

One thing we could try: removing the xml error class altogether from these icons so they're consistently monochrome?  Otherwise, would be great if anyone has any ideas for what's going wrong here, because I've checked the xml class for these icons and it's definitely present (which is proven by the fact that the red is usually - but not always - used).

**Comment by ElectricGestalt** [comment]
> I note that this is a slightly different (IMO not as serious) defect as previous. Before, fully charged batteries were showing as red sometimes, which is completely wrong. Now the colour is appropriate when present but occasionally the symbol renders as monochrome. Doubly weird when hovering changes the behaviour.

It's interesting that the icons are actually correct in the pop-up menu, but not in the bar. Very strange.

**Comment by Amr-Ibra** [comment]
Upstream adjusted the 20- and 30% batteries:
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/commit/5e5fcc700aec3d23c32bd8cda700a14c8e589643
