### ISSUE TITLE
Firefox in the mixed theme: active menu items are invisible

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1548]
![grafik](https://user-images.githubusercontent.com/15329494/65772770-34ffa500-e13b-11e9-80b0-2151803700c1.png)

Not happening in normal gtk3 menus
![grafik](https://user-images.githubusercontent.com/15329494/65772807-46e14800-e13b-11e9-8794-81e6bf2db7b0.png)

Not happening with the light theme
![grafik](https://user-images.githubusercontent.com/15329494/65772845-5a8cae80-e13b-11e9-987a-f2a4656f469d.png)

We use $fg_color for the active menu items
https://github.com/ubuntu/yaru/blob/master/gtk/src/default/gtk-3.20/_tweaks.scss#L167

Firefox uses a dark menubar because the tabs fg_color is for some reasons linked to the menu here:
https://github.com/ubuntu/yaru/blob/master/gtk/src/default/gtk-3.20/_apps.scss#L423

**Comment by clobrano** [comment]
> Firefox uses a dark menubar because the tabs fg_color is for some reasons linked to the menu here:
https://github.com/ubuntu/yaru/blob/master/gtk/src/default/gtk-3.20/_apps.scss#L423

We have two concurrent problems here. If the menubar is bright (as in Yaru-light), the menus work fine, but the tabs in no-titlebar mode won't be visible, on the other side, if the menubar is dark (as in current default), tabs are fine and menus are not.

In the end, since no-titlebar mode is not the default, we should prefer to support that first. 
Planning this to 20.04 to see if we can fix both sides.

**Comment by Feichtmeier** [comment]
But it's inside #MozillaWidget so you could style the menuitems for firefox only

**Comment by clobrano** [comment]
Okay, got it
