### ISSUE TITLE
Style of toolbar icons not consistent with new icons theme.

### ISSUE THREAD

**Issue by gapplef** [ubuntu/yaru#1560]
## Expected Behavior
I expected the toolbar icons to be flatten and modernized, consistent with the new icons theme.

## Actual Behavior
The toolbar icons are still the same as previous `Ubuntu-mono` icons. Especially the open-file icon still based on the old file icon.
![Yaru](https://user-images.githubusercontent.com/5604665/66206920-07d76780-e6e4-11e9-9899-80dca9dd4980.png)

The following are examples from `Paper` icons, not perfect, but I think it's still better than current `Yaru`.
![Paper](https://user-images.githubusercontent.com/5604665/66206912-0148f000-e6e4-11e9-87b2-7fbf33feff2b.png)

## Specifications
Ubuntu 19.10
yaru-theme-icon 19.10.4

Software that presents the issue:
Zim 0.72.0
PDF Arranger 1.1.1
Transmission 2.9.4
Meld 3.20.1

**Comment by madsrh** [comment]
Hi @gapplef 
Thanks for reporting 😃 This has been discussed earlier in [this issue](https://github.com/ubuntu/yaru/issues/1468) so I'm going to close your issue here. But if you want to take on the task yourself, any contributions are welcome.

> After looking at the amount of icons and/or symlinks needed for this we agreed on not doing this.

Those legacy icons are only use for legacy apps or apps that use legacy design. Thus those need to take the legacy icon set then!
Sorry!
