### ISSUE TITLE
Thunderbird progress bar should be orange instead of blue-green

### ISSUE THREAD

**Issue by geckolinux** [ubuntu/yaru#1581]
Hi there, I really like Yaru, using the version from Ubuntu 19.10 on openSUSE Tumbleweed.

I'm a huge fan of the orange accents. On Thunderbird (version 68) the progress bar in the bottom right corner is blue-green. I think it should be orange too like all other active elements.

![Screenshot_20191021_222500](https://user-images.githubusercontent.com/2692138/67257697-ce785900-f452-11e9-8856-d82222df0127.png)

Thanks again for this nice theme!

**Comment by clobrano** [comment]
Hi @geckolinux, thank you :)

I am not sure if this is thunderbirds specific, but progress bars, as well as volume gauge are indeed blue in Yaru, because those are "indications" and not "selection", which is orange (see the [wiki](https://github.com/ubuntu/yaru/wiki/%231-Ubuntu-Theme-Refresh:-why-and-how%3F#how))

**Comment by geckolinux** [comment]
Thanks, good to know that it's the intended behavior of Yaru.

By any chance could you point me to which lines in the CSS I could change to make progress bars (and possibly volume bars) orange?

**Comment by clobrano** [comment]
CSS is built automatically from sass files, so I don't know precisely where to look at, except you can search for the hex blue value and change it to orange
