### ISSUE TITLE
A new yaru dark theme option dedicated for AMOLED screen. Pure Shiny Vivid Black.

### ISSUE THREAD

**Issue by PranavBhattarai** [ubuntu/yaru#1666]
Till now we don't have that. I think its a nice approach/concept. Our mobiles have adapted this and it looks shinier crystal clear ever than before. It make the text which are white more visible then the one with Grey theme. 

Currently Yaru creates three themes:

1. Yaru                                   _(which is white in color with black Title bar.)_
2. Yaru light                           _(which is white in color with white Title bar.)_
3. Yaru dark                           _(which is a mix of Grey & Black. Slight black in Title bar & Grey body.)_

We need to step up and make another dark theme. Like how there is 2 white theme, why not 2 dark theme.

It looks great of 4K monitors with **OLED** display panel, and even in normal **LCD** 1080p laptop.  Things will starts to look crystal clear, shiny, bright. It will be more comfortable on eyes.

I am not against **Yaru dark**. It nice and sweet. Warm. But we also need something mind-blowing & extraordinary. I think this concept heavily resides on mobile phone application. Apps like Telegram, Viber, Kiwi, etc. Most of now apps provide 2 types of darkness. One just grayish dark theme and other pure black. We should have this on Ubuntu too.

I am using **Ubuntu 19.10**. _I like Yaru dark but I don't love it. Like is not equal to love._

**Comment by clobrano** [comment]
Hi

thanks for taking time to contribute to Yaru project.

I am sorry to say that I don't support this request, this is why.


From a design point of view, I understand that pich black looks nice at first, however it has some downsides, since it does not provide enough elevation to show different planes (background, panels, buttons, etc. all look on the same level)

For example, have a look material design or dark theme https://material.io/design/color/dark-theme.html#usage in Priciples.

> Things will starts to look crystal clear, shiny, bright. It will be more comfortable on eyes.

The appropriate contrast can be obtained as well using grey and (personally) I find white on black disturbing after a while.

Finally, from a technical point of view, having 4 variants is a lot of work we cannot sustain. I cannot even be sure we will always have three variants in the future.


> I am not against Yaru dark. It nice and sweet. Warm.

I like this, warmness is one of my goals :)

**Comment by madsrh** [comment]
I think it's fantastic that you like Yaru so much that you want to see it improved @PranavBhattarai 👍 

But I'll have to agree with @clobrano that this won't happen (at least not coming from our team) for all the reasons he mentioned above.

I'm closing this issue/request on a positive note though; In the beginning there was only one Yaru theme! We've closed similar requests earlier and here we are supporting (for now) three variants 😉 

Thanks again for contributing!
