### ISSUE TITLE
Missing icon: view-refresh and symlinks

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1758]
Missing icon in `icons/Suru/scalable/action/`

**action.list:**
`view-refresh.svg gtk-refresh.svg`

![Untitled-1](https://user-images.githubusercontent.com/3986894/72572597-4ecc2000-38c3-11ea-8ee6-4434546f7c58.gif)

**Comment by Feichtmeier** [comment]
Nice catch!
But is it really taking a symbolic icon?
I fear it's such an old dialogue that it asks for a legacy action icon in colour which we miss not the scale able one

**Comment by madsrh** [comment]
> But is it really taking a symbolic icon?

Ahh, you mean that it should be a "regular" arrow in Yaru style, and not a symbolic one? The fallback path is something like `Humanity/actions/gtk-refresh.svg`

These symlinks are also killing me so if you want a new colored icon, I can easily add that - if I can draw an arrow ofc.

**Comment by Feichtmeier** [comment]
I think that still not existing full colour arrow should be in the legacy actions folder. The same folder where Stuart added the nice document icons and the new vanilla check mark in the green circle. Sorry currently at the phone

**Comment by madsrh** [comment]
I'll be back... (shouldn't do this late at night)

**Comment by Feichtmeier** [comment]
Nooo why do you close it :D just rename the issue it's totally valid!
It is called
```view-refresh``` 
Symlinks to
- stock_refresh
- reload
- reload3
- reload_all
- reload_page
- gtk-refresh

That's the place 
![image](https://user-images.githubusercontent.com/15329494/72604209-5a930300-3912-11ea-99ad-107f7a635a9c.png)

**Comment by madsrh** [comment]
A non symbolic Yaru arrow can be found in the LivePatch icon, but I don't know if this works and if it should be green.

![image](https://user-images.githubusercontent.com/3986894/72609336-e1e97200-3924-11ea-8463-771049bd138b.png)

These symlinks are driving me crazy! 😵 I really don't understand them.

**Comment by Feichtmeier** [comment]
The first step is to create the " view-refresh" icon. After that we need to add all of the symlinks listed above to the full color symlinks list file for actions. After that we can run the symlink script which then automatically creates symlinks in all of the suru actions/SIZEXYZ directories (but stuart knows all this shizzle - just in case you want to do it :) )

If you really want to understand symbolic links you need to understand references in programming languages or to be concrete pointers in C :) 
Otherwise just imagine you open your letter box and the postman did not put the real newspaper into it but instead a little note "your newspaper can now we only found in the letterbox of your neighbour" :)

**Comment by madsrh** [comment]
Thanks @Feichtmeier 😃 I understand how they should work, but it doesn't work that way.

I added them to the `actions.list` and ran the script, but the they are broken.

**Comment by madsrh** [comment]
Adding `dialog-warning` to the list.

![image](https://user-images.githubusercontent.com/3986894/74071873-59329300-4a05-11ea-8cd6-52a09c24c3c9.png)

**Comment by Feichtmeier** [comment]
Fixed with #2002 
![grafik](https://user-images.githubusercontent.com/15329494/76417506-43661400-639d-11ea-8dc3-d8f336de57b5.png)
