### ISSUE TITLE
Offset input cursor

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#1795]
## Expected Behavior

Click on an input with some text, between two letter, cursor is put exactly in this place.

## Actual Behavior

![out](https://user-images.githubusercontent.com/36476595/73096731-c7476800-3ee5-11ea-95b1-3c498a373288.gif)
Very annoying when you want to go fast 😋
## Software that presents the issue

I think every Gtk2 apps have this issue.
Tested on Ubuntu 18.04 (snap), 19.10 and 20.04

**Comment by Feichtmeier** [comment]
This only with the yaru gtk2 theme, right?

**Comment by Jupiter007-43** [comment]
I notice it only on gtk2 : gimp 2.10, dia, ...
Never noticed on gtk3 or qt apps.
That's why I think it only affects gtk2.

**Comment by madsrh** [comment]
@Jupiter007-43 could you try with the Adwaita theme?

**Comment by Jupiter007-43** [comment]
Same issue...

**Comment by madsrh** [comment]
@Jupiter007-43 Thanks

I just try it and I can recreate the issue.

This is GIMP 2.1 (dark theme) with Adwaita
![Peek 2020-01-25 08-27](https://user-images.githubusercontent.com/3986894/73124148-cac20a00-3f4c-11ea-89ab-6f4c8ee5abdf.gif)

I'll close the bug here because it isn't caused by Yaru. Sorry we couldn't fix this but thanks for taking the time to report it. You'll have to report this upstream https://gitlab.gnome.org/GNOME/gtk

**Comment by Jupiter007-43** [comment]
Ok, thank you 😃

**Comment by Jupiter007-43** [comment]
https://gitlab.gnome.org/GNOME/gtk/issues/2393

**Comment by Jupiter007-43** [comment]
https://gitlab.gnome.org/GNOME/gtk/issues/2393#note_694927
> The theme has no influence at all on this

> different font could influence this, maybe the font has broken metrics somehow.
> the rest of the theme should be entirely irrelevant
