### ISSUE TITLE
Inconsistent ejected usb key icon 

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#1859]
Another gnome-disk issue this time with USB key icon !

## Actual Behavior

Mounted :
![Capture d’écran du 2020-02-05 19-57-16](https://user-images.githubusercontent.com/36476595/73873735-71ae7c00-4852-11ea-838e-cfbf78d25e1b.png)

Unmounted :
![disques](https://user-images.githubusercontent.com/36476595/73873739-73783f80-4852-11ea-8522-d7a1d6c68ab2.png)

## Adwaita

Mounted :
![Capture d’écran du 2020-02-05 20-04-15](https://user-images.githubusercontent.com/36476595/73873919-d5d14000-4852-11ea-8d97-c1c2b4842cdc.png)

Unmounted :
![Capture d’écran du 2020-02-05 20-03-59](https://user-images.githubusercontent.com/36476595/73873912-d36ee600-4852-11ea-8b1a-93991f42311a.png)

**Comment by Feichtmeier** [comment]
We definitely have a full color icon for this, I guess only the symlink is missing :)
Thank you very much for the nice reports!

**Comment by madsrh** [comment]
But it seems the unmounted icon (which I can't reproduce) is different from the mounted. Do you mean we have a unmounted icon @Feichtmeier ? I think other theme use an eject button :man_shrugging: 

It's the removable-media.svg

**Comment by Feichtmeier** [comment]
I mean the usb stick full color icon :)
https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/devices/drive-removable-media-usb.svg

**Comment by madsrh** [comment]
> I mean the usb stick full color icon :)

The USB stick works fine 👇 

![image](https://user-images.githubusercontent.com/3986894/73891486-9c113100-4874-11ea-84dc-5b09899d4fb4.png)

@Jupiter007-43 what kind of device is that exactly you are inserting?

**Comment by ubuntujaggers** [comment]
Looking at the first screenshot in the first post, whatever device it is, Gnome is choosing to represent it with drive-harddisk-usb, which is a plain drive icon with the USB symbol on it.

https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/devices/drive-harddisk-usb.svg

However, in the second screenshot, it's showing as the symbolic version of drive-removable-media, which is modelled on a thumb stick.  I note there's nothing in this symbol that represents "ejected".

https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/devices/drive-removable-media-usb.svg

So if we symlink the missing full colour icon to _either_ of these, potentially we end up with inconsistent behaviour where the same device flips icon as you eject it.

Out of the two inconsistent scenarios, I think a thumb drive becoming a generic USB drive device when it's ejected is less weird, because thumb drives are a subset of USB devices, and it sort of "makes sense" that the desktop would present less detail about an ejected device.  Whereas a USB hard disk turning into a (wrong) thumb stick at the moment you eject it has no logic.

So if we go for a symlink approach I recommend we symlink the missing full colour icon to this:

![image](https://user-images.githubusercontent.com/38893390/73920907-43ff1c80-48be-11ea-83b2-003d0444bd54.png)

Alternatively we could have a version of the above which reflects unmounted - maybe with a fainter or pale version of the glyph?  That would be v easy to do once we know the icon name and I could push it tonight.

**However,** my preference would be to use emblems for mounted versus unmounted.  We have no way of doing that in the icon theme without pasting emblems into icons, which we've moved away from, because it can lead to unpredictable results if the desktop then adds an emblem too, so let's not do that  :)  I'm guessing only upstream could do this with emblems?

**Comment by meetdilip** [comment]
I think it should indicate " Safely remove " in some manner.

**Comment by meetdilip** [comment]
>  I note there's nothing in this symbol that represents "ejected".

![yaru green](https://user-images.githubusercontent.com/6965443/73924326-4b401d80-48f2-11ea-80e0-6da010154fb8.png)
![yaru blue](https://user-images.githubusercontent.com/6965443/73924332-4ed3a480-48f2-11ea-8780-fb2de14b9c0c.png)

**Comment by meetdilip** [comment]
Or very clear visual suggestion to remove the drive

![usb green](https://user-images.githubusercontent.com/6965443/73927174-e804ba00-48f6-11ea-8f4d-4fcc6d6ff4ec.png)
![yaru eject](https://user-images.githubusercontent.com/6965443/73927181-ea671400-48f6-11ea-8e04-ae8c62ce395c.png)
![usb eject blue](https://user-images.githubusercontent.com/6965443/73927185-eb984100-48f6-11ea-9100-7f30d1df0088.png)

**Comment by meetdilip** [comment]
Or something like this which says it is time to get the USB drive out

![usb hot](https://user-images.githubusercontent.com/6965443/73927324-2c905580-48f7-11ea-96c3-90cfb46bf6b3.png)

**Comment by Jupiter007-43** [comment]
@madsrh sorry, I forgot to specify how to reproduce :
- connect an USB key
- unmounted it from nautilus (not from gnome-disk, if unmounted from disk, the key disappear)
- icon should be wrong (see my first post)

By the way, the mounted key icon looks like an USB hard disk...

**Comment by meetdilip** [comment]
Looks like red is better than other colours

![usb red](https://user-images.githubusercontent.com/6965443/73953771-e7841780-4926-11ea-9bb5-0be4bd8e8e6d.png)

**Comment by meetdilip** [comment]
Added a white outline to the red circle

![usb ejected](https://user-images.githubusercontent.com/6965443/73954286-99bbdf00-4927-11ea-88b6-1a40eb68b92e.png)

**Comment by ubuntujaggers** [comment]
> ![yaru green](https://user-images.githubusercontent.com/6965443/73924326-4b401d80-48f2-11ea-80e0-6da010154fb8.png)

So unfortunately this is an example of making an emblem part of the icon, which we try to avoid, because the desktop sometimes superimposes emblems on icons too, and we've got in a mess before when we had an emblem ending up on top of an emblem  :)  We try to avoid "something overlapping the main icon" in general (e.g., we experimented with designs that included a representation of a half-full status bar over an icon, and then a real bar got put on the same icon by the desktop).

Regardless of where we put it - using a positive, tick style symbol is fine if this icon will always be telling you it's safe to remove the device and nothing else.  We should use something more neutral (not a "value judgement") if it just generally represents an unmounted device.  If you actually want to access files on an unmounted device it's not a green tick situation, for instance.  So any more info on when this icon might be presented is helpful, I never see it  :(

@feichtmeier had a good idea for a disconnect in the USB glyph, I'll give that a whirl and see if it works for everyone.

**Comment by ubuntujaggers** [comment]
@Jupiter007-43 Can you please change to humanity icon set and show us what the unmounted drive looks like?  That set has various "unmount" icons, so if we know which one gets used, we can probably work out what the missing icon is called.

**Comment by meetdilip** [comment]
I simply tried to use the " standard " `tick` icon on the USB. Later I realised that red will be the one to say " take it away ". Keeping icon standalone is always good. I was just giving options.

**Comment by meetdilip** [comment]
> @Feichtmeier had a good idea for a disconnect in the USB glyph, I'll give that a whirl and see if it works for everyone.

Would love to see that one :)

**Comment by ubuntujaggers** [comment]
@Feichtmeier 

![unmounted](https://user-images.githubusercontent.com/38893390/73958958-8fd2b580-4900-11ea-9dca-63835d82f96c.png)

?

**Comment by meetdilip** [comment]
>  it just generally represents an unmounted device.

Would tilting work ?

**Comment by Jupiter007-43** [comment]
@ubuntujaggers here is :

Mounted
![Capture d’écran du 2020-02-06 18-09-36](https://user-images.githubusercontent.com/36476595/73960986-19d44b80-490c-11ea-8887-ff65d231cd63.png)

And unmounted
![Capture d’écran du 2020-02-06 18-09-48](https://user-images.githubusercontent.com/36476595/73961022-26f13a80-490c-11ea-93ad-ed1bf4688c0b.png)

Same as Adwaita...

🤔 I remember that this icon seemed strange to me before (when Humanity was the default theme with Unity RIP).

**Comment by Feichtmeier** [comment]
I think the logic of
Unmounted -> showing the real device (usb flash drive)
Mounted -> now the device is part of your filesystem

But it's too abstract. Whatever idea we go with, it should make sense in other applications too

@ubuntujaggers thanks for trying. Do you think it works? I'm not sure :D

**Comment by ubuntujaggers** [comment]
> @ubuntujaggers thanks for trying. Do you think it works? I'm not sure :D

![image](https://user-images.githubusercontent.com/38893390/73968165-20b18d00-4911-11ea-8407-3d42bd0b3d06.png) ![image](https://user-images.githubusercontent.com/38893390/73968211-33c45d00-4911-11ea-9ed2-76822620c76b.png)

Not sure.  Might be worth simply making the glyph faint without putting the break in?

**Comment by ubuntujaggers** [comment]
It looks like it's falling back to a legacy Adwaita icon called media-removable.  I guess this is why it shows both an SD card and a thumb drive rather than something specific.  The safest thing would be to do a full colour icon that can represent any removable media...  if that's used strangely in a particular context then that's probably an upstream problem?

**Comment by Feichtmeier** [comment]
> The safest thing would be to do a full colour icon that can represent any removable media...

I agree if there were maaany things users could insert nowadays.
But I think it breaks down to four things:

- usb stick
- sd card
- phone
- camera

Sorry I am no real help here. I think it's rather confusing because we don't know where gnome app dudes place those icons on.

What happens if you mount an SD card and then unmount it? What icon is shown?

**Comment by meetdilip** [comment]
I don't want to force it on you, but won't a red version indicate that it is not available

![usb not mounted](https://user-images.githubusercontent.com/6965443/73994779-c3ebbc00-497c-11ea-81e4-342c7dfe7f2f.png)

**Comment by Jupiter007-43** [comment]
@Feichtmeier Sorry I haven't got a sd card reader directly on my pc, just an USB stick for read them.

Mounted
![Capture d’écran du 2020-02-07 12-19-49](https://user-images.githubusercontent.com/36476595/74025816-150fa600-49a5-11ea-8a9b-97f5a7fc327a.png)

Unmounted
![Capture d’écran du 2020-02-07 12-20-11](https://user-images.githubusercontent.com/36476595/74025821-1640d300-49a5-11ea-9b7a-56f1e3a3db52.png)

I think the icon displayed form each device is a little strange:

- USB key -> USB hard disk
- USB key unmounted -> USB hard disk or [icon from Adwaita](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/blob/master/src/fullcolor/legacy/media-removable.svg)
- SD USB reader key -> USB key
- USB hard disk -> USB hard disk (the only good)

**Comment by ubuntujaggers** [comment]
> I don't want to force it on you, but won't a red version indicate that it is not available

Yes, but I guess my point is that the icon isn't called media-removable-unavailable or -unmounted (as far as I can tell) - it's just called media-removable.

If an app is using an icon weirdly and we fix that by having an icon that's called one thing but visually represents something else, that might have unexpected behaviour elsewhere.  I guess the risk is some other app uses the icon to stand for all removable media and we make it look like everything is safe to eject.

**Comment by meetdilip** [comment]
Do we have a representation for `unmounted` then ? When Google, I see only the eject button.

**Comment by ubuntujaggers** [comment]
> Do we have a representation for `unmounted` then ? When Google, I see only the eject button.

Good question ☺️ it may be that there IS the option to provide an icon with a more specific name and then it looks for media-removable as Plan B. A bit more diagnosis required. We should symlink media-removable to our existing icon in the meantime so it's at least not using a symbolic icon. Will do as soon as I get chance 👍

**Comment by meetdilip** [comment]
Good luck. Eagerly waiting.
