### ISSUE TITLE
dconf Editor icon should be changed or reverted to default

### ISSUE THREAD

**Issue by Electw** [ubuntu/yaru#1864]
The icon for dconf Editor is very different from the original so it's difficult to recognize easily, as well it looks rather disturbing. The icon should be changed to the original magnifying glass and red checkmark, or something that looks like it.

## Software that presents the issue

- Name: dconf Editor
- Version: 3.34.3

## Yaru version

19.10.5-276-g94e283f9

## Icon Request

Icon name from .desktop file: ```ca.desrt.dconf-editor.png```

![dconf-editor](https://user-images.githubusercontent.com/55963122/73968941-59c90d80-48cf-11ea-93db-b75d19df052d.png)

**Comment by Feichtmeier** [comment]
Okay, why exactly?
Tweaks -> an app to toggle some settings -> some toggles
Dconf editor -> an app to toggle maaaany settings -> many toggles
Simple as that

**Comment by madsrh** [comment]
> ..is very different from the original so it's difficult to recognize easily...

It's a fair point, but as we've discussed earlier (the Nautilus issue), we don't have to use the same metaphor as upstream. 

@Feichtmeier I gave this a 👍 because I don't think the current icon is Yaru at it's best. 

I do think something simpler could work better. This isn't it 😄 (It looks like there's danger approaching - but you get the point)

![image](https://user-images.githubusercontent.com/3986894/73978374-8101f800-492c-11ea-8c64-d78294d7d462.png)

Perhaps @ubuntujaggers can create something like this?
![image](https://user-images.githubusercontent.com/3986894/73979123-e4405a00-492d-11ea-9fa8-f5ce30306279.png)

**Comment by Electw** [comment]
It's quite different from the original dconf editor icon, which has red, white, and black, although I do agree the logic behind it is sound.
Regarding my comment about it being disturbing, it resembles some trypophobic content. I would think that Linux for human beings would not induce such thoughts, although this may just be me and not representative of the majority of users.

**Comment by ubuntujaggers** [comment]
We inherited this one from Suru and just desquirclified it, happy to try to Yaru the upstream design?

**Comment by ubuntujaggers** [comment]
Although actually as far as a Yaru version goes I like what Mads has done...

**Comment by madsrh** [comment]
> ...happy to try to Yaru the upstream design?

That would be awesome!

**Comment by Feichtmeier** [comment]
Mads icon is very simple and I think good. Might check that highlights and shadows and whatnot.
Being delicate with upstream is always a good idea ;) :)

**Comment by madsrh** [comment]
https://github.com/Bonandry/suru-plus-ubuntu/blob/master/icone%20generiche/colorito/configurazione.svg
