### ISSUE TITLE
Dark theme not applied to Notifications and Modal dialogs

### ISSUE THREAD

**Issue by martinRenou** [ubuntu/yaru#1899]
## Expected Behavior

The dark theme should be applied to Notifications and Modal dialogs?

## Actual Behavior

The dark theme is not applied to Notifications and Modal dialogs (like the Network selection dialog).

## Software that presents the issue

- Name: Communitheme
- Version: 0.1 (installed on Ubuntu 18.04 through `apt`)

Thanks!

**Comment by clobrano** [comment]
Hi @martinRenou, thanks for taking time to give your feedback.

In Gnome the interface is provided by two different parts, the dark theme you refer to is one part (called gtk), the notifications and modal dialogs belong to the other (named shell) and they can't change accordingly due to some limitations. You can still change the shell to dark as well, but in that case you also need to install gnome-tweaks and an extension called "User themes".

Thanks!

**Comment by martinRenou** [comment]
Oh ok, thanks for the explanation!
