### ISSUE TITLE
Sync icontheme, gtk2, gtk3, and shell checkmark assets

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1939]
1. Sync the colors (aubergine, golden focus rings)
2. Sync the checkmark assets

TODO:

- [ ] https://github.com/ubuntu/yaru/blob/master/icons/src/scalable/source-symbolic.svg checkmark icon

- [ ]  https://github.com/ubuntu/yaru/blob/master/gnome-shell/src/checkbox.svg + the others, already started with this in #1746 

- [x] https://github.com/ubuntu/yaru/blob/master/gtk/src/default/gtk-3.20/assets.svg -> render -> real assets -> https://github.com/ubuntu/yaru/issues/1730

- [x] https://github.com/ubuntu/yaru/blob/master/gtk/src/default/gtk-2.0/assets.svg -> https://github.com/ubuntu/yaru/issues/1730

**Comment by clobrano** [comment]
I'm sorry, but I can't fix the shapes of 

- https://github.com/ubuntu/yaru/blob/master/icons/src/scalable/source-symbolic.svg checkmark icon
- https://github.com/ubuntu/yaru/blob/master/gnome-shell/src/checkbox.svg + the others, already started with this in #1746

the other two items are already covered by #1730 and fixed in #1963

**Comment by Feichtmeier** [comment]
I can fix the shell for sure. No idea about the source-symbolic thing. That's prbly better something for @ubuntujaggers
