### ISSUE TITLE
Missing icon for game controller

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#1951]
## Actual Behavior

![Capture d’écran du 2020-02-20 11-09-09](https://user-images.githubusercontent.com/36476595/74923636-6c643c00-53d1-11ea-8404-e119afffdcd3.png)

## Adwaita

![Capture d’écran du 2020-02-20 11-04-01](https://user-images.githubusercontent.com/36476595/74923661-7ab25800-53d1-11ea-922b-b365ccc42555.png)

Super Nintendo colors 😋

## Steps to Reproduce the Problem

  1. Open Gnome-settings
  1. Go to Bluetooth
  1. Connect a game controller (I connected a Nintendo Switch Pro controller)

**Comment by meetdilip** [comment]
Gave it a try

![game controller yaru](https://user-images.githubusercontent.com/6965443/74930988-badefe00-5404-11ea-80a3-6e76544b3d79.png)

**Comment by Feichtmeier** [comment]
I think we have a gnome-games icon, maybe we can use that one

**Comment by rvz420** [comment]
> I think we have a gnome-games icon, maybe we can use that one
![gnome-games icon](https://github.com/ubuntu/yaru/blob/master/icons/Suru/256x256/apps/games-app.png?raw=true )

[https://github.com/ubuntu/yaru/blob/master/icons/Suru/256x256/apps/games-app.png](url)

**Comment by Jupiter007-43** [comment]
It looks too much like a Gameboy and not a game controller ! 😋

What about something like this :

![path931-8](https://user-images.githubusercontent.com/36476595/74970899-7dd43500-541f-11ea-8ef9-3b58fcc22fd3.png)

**Comment by meetdilip** [comment]
I took out the colours for now


![game controller yaru white](https://user-images.githubusercontent.com/6965443/74994762-ebf71700-5474-11ea-8ffe-592c7e4f31df.png)

**Comment by meetdilip** [comment]
> It looks too much like a Gameboy and not a game controller ! yum
> 
> What about something like this :
> 
> ![path931-8](https://user-images.githubusercontent.com/36476595/74970899-7dd43500-541f-11ea-8ef9-3b58fcc22fd3.png)

Looks cute. But does it imply a game controller ?

**Comment by clobrano** [comment]
> It looks too much like a Gameboy and not a game controller ! yum
> 
> What about something like this :
> 
> ![path931-8](https://user-images.githubusercontent.com/36476595/74970899-7dd43500-541f-11ea-8ef9-3b58fcc22fd3.png)

I love this!

**Comment by Feichtmeier** [comment]
> It looks too much like a Gameboy and not a game controller ! 😋
> 
> What about something like this :
> 
> ![path931-8](https://user-images.githubusercontent.com/36476595/74970899-7dd43500-541f-11ea-8ef9-3b58fcc22fd3.png)

if you would add two more red dots beneath (like on a SNES controller), that'd be nice 💃

**Comment by Jupiter007-43** [comment]
@Feichtmeier Et voila !

![controller](https://user-images.githubusercontent.com/36476595/75026621-95520300-549d-11ea-8c68-3962a09a9a14.png)


I reversed the colors to not look too much like the SNES controller.

> Looks cute. But does it imply a game controller ?

Yes! You have the directional cross, the start and select buttons and finally A, B, X and Y buttons.

**Comment by Feichtmeier** [comment]
Nice! 
Maybe even remove those two gray thingies at the bottom, and shrink the height of the controller to fit the cross and the dots? : D

**Comment by Jupiter007-43** [comment]
Like this :
 
![controller](https://user-images.githubusercontent.com/36476595/75028910-72295280-54a1-11ea-9485-3a5d3850e573.png)

But what! A game controller without start and select! How can I pause? 😆

**Comment by Jupiter007-43** [comment]
And with two little buttons

![controller](https://user-images.githubusercontent.com/36476595/75030027-8a01d600-54a3-11ea-9369-c8ea6ec2b213.png)

**Comment by clobrano** [comment]
the gameboy-ish one looks a bit cleaner :)

**Comment by Jupiter007-43** [comment]
And like this (reworked shadows) ?

![game](https://user-images.githubusercontent.com/36476595/75036003-bb30d500-54a8-11ea-94c3-d4069f87c4f7.png)

**Comment by clobrano** [comment]
Better indeed :+1:

**Comment by Jupiter007-43** [comment]
Good! In fact, there are just quick test, so I didn't take the time to work on them properly.😉

**Comment by Feichtmeier** [comment]
Nice!
Are those colours from our palette?

**Comment by Jupiter007-43** [comment]
Random!

These colors? https://github.com/ubuntu/yaru/blob/master/gtk/src/default/gtk-3.20/_ubuntu-colors.scss

**Comment by Feichtmeier** [comment]
Yes that'd be nice :) sorry for asking so many questions

**Comment by Jupiter007-43** [comment]
![game](https://user-images.githubusercontent.com/36476595/75039940-030c2800-54ba-11ea-950f-48ece8933dd8.png)

**Comment by Feichtmeier** [comment]
Nice, if the others agree we're looking forward for your PR :)

**Comment by Jupiter007-43** [comment]
And I'd work it much better!

**Comment by ubuntujaggers** [comment]
> It looks too much like a Gameboy and not a game controller ! 
> 
> What about something like this :
> 
> ![path931-8](https://user-images.githubusercontent.com/36476595/74970899-7dd43500-541f-11ea-8ef9-3b58fcc22fd3.png)

This is almost perfect Yaru - we just need to resize the backplate in a way that doesn't distort the contour of the corners 👍

**Comment by ubuntujaggers** [comment]
> I took out the colours for now
> 
> ![game controller yaru white](https://user-images.githubusercontent.com/6965443/74994762-ebf71700-5474-11ea-8ffe-592c7e4f31df.png)

This backplate is a nice shape, but we would have to reuse the buttons from the Gameboy icon rather than redrawing slightly different versions of the same objects.

**Comment by Jupiter007-43** [comment]
> Edit: I love the version with the coloured buttons, just got to make sure the style of the shadows matches other icons.

In fact by dint of modifying I've I deformed the shadow...
I'm of course going to redo everything cleanly 😉

**Comment by ubuntujaggers** [comment]
> In fact by dint of modifying I've I deformed the shadow...
> I'm of course going to redo everything cleanly

:)

Couple of tips for "maximum Yaru" ( = consistency):

- See if there's an existing icon with a backplate that has the right proportions (keyboard is probably closest)
- If there isn't any that's quite right, start with [the horizontal oblong template](https://github.com/ubuntu/yaru/pull/1920/commits/94c93920db47aec3d475b06cd154e982a17ff7e8#diff-89660b729cdd4da6b13349e61341b99f) from the draft PR with the new templates
- Save a copy of it
- Make the baseplate layer visible, padlock it so you don't accidentally edit it, and press # for grid:
![image](https://user-images.githubusercontent.com/38893390/75063861-b1759480-54dd-11ea-80d7-c3958d278fa9.png)
- Ctrl-A to "select all" and then click edit paths by node:
![image](https://user-images.githubusercontent.com/38893390/75063922-d66a0780-54dd-11ea-992e-162d26168728.png)
- When the nodes appear, click/drag a box to select all the nodes that make the top two corners of the baseplate only, which will also pick up the shadow:
![image](https://user-images.githubusercontent.com/38893390/75064068-23e67480-54de-11ea-802e-28206249f15a.png)
- You can now press the down key repeatedly to lower the top of the baseplate _without_ deforming (squashing) the curve of the corners
- Make sure the top edge is still aligned with the grid (two presses of the down key = one whole grid square lower - so do a number that's a multiple of two)
- Repeat the process on the nodes of the bottom edge, moving it up by the same amount so the baseplate is centred
- If any elements get left behind (like the pale highlight on the top edge and the dark lowlight on the bottom edge) click them individually and use the arrow key to move them precisely back onto the baseplate
- You now have a baseplate that's your chosen dimensions, with the corners having exactly the right curves and the drop shadow exactly right for the theme:
![image](https://user-images.githubusercontent.com/38893390/75064458-eafacf80-54de-11ea-8ac5-1db2edd7bcee.png)
- And you can edit the gradient and add your buttons, etc., in the pictogram layer  :)

**Comment by ubuntujaggers** [comment]
@meetdilip, drawing a completely new backplate shape is possible, just harder  :)  We copy the styling of the existing backplates so the new shape fits in.  The full size version has these features:

![image](https://user-images.githubusercontent.com/38893390/75066232-57c39900-54e2-11ea-8159-5aaa58bd0824.png)

The smaller sizes have these features (note pixel grid):

![image](https://user-images.githubusercontent.com/38893390/75065967-db30ba80-54e1-11ea-9128-0e15ec46e94e.png)

Having the backplate under the outline, but slighter smaller, does nice things when the icon renders at 100% size on the desktop :)

**Comment by meetdilip** [comment]
Thanks for explaining. At some point, I tend to think that these template based drawings are too much for me. I will try to use them though. :)

**Comment by meetdilip** [comment]
I tried and here is the output. But I can't figure out how to make the white border inside the image.

![u3](https://user-images.githubusercontent.com/6965443/75089948-f522d980-5583-11ea-8305-9ecde8e2199c.png)

**Comment by rvz420** [comment]
> > It looks too much like a Gameboy and not a game controller ! yum
> > What about something like this :
> > ![path931-8](https://user-images.githubusercontent.com/36476595/74970899-7dd43500-541f-11ea-8ef9-3b58fcc22fd3.png)
> 
> Looks cute. But does it imply a game controller ?

Yes! Nes controller was like this 😋

**Comment by ubuntujaggers** [comment]
> I tried and here is the output. But I can't figure out how to make the white border inside the image.
> 
> ![u4](https://user-images.githubusercontent.com/6965443/75090012-94e06780-5584-11ea-98a2-d1928954e936.png)

Getting there!  First, here are the detailed instructions for making the 256px background in a new shape - I will do the smaller icons next.

First of all, load an icon template, make the baseplate layer visible, and delete the 256px background.  Then draw the shape you want centred in the 256px canvas.  It's important that this is a single object, so, if you make it out of multiple objects (I used two circles and a rectangle), select them all and do Path --> Union before you continue:

![image](https://user-images.githubusercontent.com/38893390/75111489-63be7080-5632-11ea-94c9-63134b91f4b8.png)

Now make the baseplate layer invisible and add a gradient.  Ideally nick the gradient from an existing icon.  Here, I've used the gradient from the keyboard device icon.  The darker bit should be at the top:

![image](https://user-images.githubusercontent.com/38893390/75111508-a2542b00-5632-11ea-8672-86290c60cf02.png)

Next we add the top highlight.  Copy your shape, turn the copy to white with opacity 30, and put it exactly on top of your shape:

![image](https://user-images.githubusercontent.com/38893390/75111541-f0692e80-5632-11ea-8eb2-f4bb3a8d25b1.png)

Copy the white opacity 30 shape and put it on top of that, then use the down key to move it 2px down:

![image](https://user-images.githubusercontent.com/38893390/75111550-1989bf00-5633-11ea-8a3c-a9098474bdf6.png)

Hold the shift key so you can select both of your white opacity 30 shapes:

![image](https://user-images.githubusercontent.com/38893390/75111565-4fc73e80-5633-11ea-9715-09e5b90ccf5f.png)

Then do Path --> Difference.  The second shape will delete the part of the first shape that it overlaps, leaving a 2px highlight that follows the contour of your controller:

![image](https://user-images.githubusercontent.com/38893390/75111571-5ce42d80-5633-11ea-82d6-550cf9529f6c.png)

Now you repeat the highlight process at the bottom, with some differences.  Instead of making shapes that are white opacity 30, you make two shapes that are _black_ opacity _20_.  Instead of pressing the down key, you press the up key.  When you do the Path --> Difference function, it will make the 2px lowlight along the bottom:

![image](https://user-images.githubusercontent.com/38893390/75111596-c19f8800-5633-11ea-960d-cd806e822dd1.png)

Now you just need to add the subtle drop shadow.  Copy your background shape **twice**, put both copies on top of the background, and make them black.

Now use the pixel controls at the top of Inkscape to move both of them down by 1px (you can't use the down key for this because each press of the down key is 2px).

Make the first black shape blur 1, opacity 10.  Then, with it selected, press the "End" key to move it to the back of the layer, so it's behind the controller.  Make the second black shape blur 4, opacity 20 and press the "End" key on that as well.  Both shadow elements are now behind the controller.

Voila!  You've turned your new shape into a 256px Suru background:

![image](https://user-images.githubusercontent.com/38893390/75111637-2eb31d80-5634-11ea-8d13-cfc5124d2ef4.png)
