### ISSUE TITLE
Provide legacy, full color action icons

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1965]
Those icons are visible in Inkscape, they are ofc visible somewhere else, but since it is such a popular app, I think this is a very solid goal and the actual icons to draw are not so many:

![image](https://user-images.githubusercontent.com/15329494/75099215-561bd300-55bf-11ea-90ff-1a076848d7e2.png)
- [x] **edit-redo (icon)**
- [ ] redo (symlink)
- [ ] gtk-redo-ltr (symlink)
- [ ] stock_redo (symlink)

__________________________________________________

![image](https://user-images.githubusercontent.com/15329494/75099227-7186de00-55bf-11ea-8277-ce8fe083c0dd.png)
- [x] **edit-undo (icon)**
- [ ] undo (symlink)
- [ ] gtk-undo-ltr (symlink)
- [ ] stock_undo (symlink)

__________________________________________________

![image](https://user-images.githubusercontent.com/15329494/75099275-fa057e80-55bf-11ea-98f5-f7d6ddb307cc.png)
- [x] **go-up (icon)**
- [ ] up (symlink)
- [ ] gtk-go-up (symlink)
- [ ] stock_up (symlink)

__________________________________________________

![image](https://user-images.githubusercontent.com/15329494/75099285-2c16e080-55c0-11ea-8635-de3b705e26a5.png)
- [x] **go-down (icon)**
- [ ] down (symlink)
- [ ] gtk-go-down (symlink)
- [ ] stock_down (symlink)

__________________________________________________

![image](https://user-images.githubusercontent.com/15329494/75099328-a8a9bf00-55c0-11ea-9da0-e72e9543a20c.png)
- [x] **go-bottom (icon)**
- [ ] bottom (symlink)
- [ ] gtk-goto-bottom (symlink)
- [ ] stock_bottom (symlink)

__________________________________________________

![image](https://user-images.githubusercontent.com/15329494/75099355-0dfdb000-55c1-11ea-8d96-3c4e8b494a16.png)
- [x] **go-top (icon)**
- [ ] top (symlink)
- [ ] gtk-goto-top (symlink)
- [ ] stock_top (symlink)

__________________________________________________

![image](https://user-images.githubusercontent.com/15329494/75099388-6b91fc80-55c1-11ea-8658-11e0076b3042.png)
- [x] **edit-copy (icon)**
- [ ] editcopy (symlink)
- [ ] gtk-copy (symlink)
- [ ] stock_copy (symlink)

__________________________________________________

![image](https://user-images.githubusercontent.com/15329494/75099396-79e01880-55c1-11ea-8ea4-96e5f9a2e598.png)
- [x] **edit-paste (icon)**
- [ ] editpaste (symlink)
- [ ] gtk-paste (symlink)
- [ ] stock_paste (symlink)

__________________________________________________

![image](https://user-images.githubusercontent.com/15329494/75099415-b3b11f00-55c1-11ea-9daf-74534f3758c2.png)
- [x] **edit-cut (icon)**
- [ ] editcut (symlink)
- [ ] gtk-cut (symlink)
- [ ] stock_cut (symlink)

__________________________________________________

![image](https://user-images.githubusercontent.com/15329494/75099451-1c000080-55c2-11ea-9654-075c757681d5.png)
- [x] **document-properties (icon)**
- [ ] gtk-properties (symlink)
- [ ] stock_file-properties (symlink)
- [ ] stock_properties (symlink)

__________________________________________________

![image](https://user-images.githubusercontent.com/15329494/75099661-7e5a0080-55c4-11ea-898a-9b492eeb97c6.png)
- [ ] **gconf-editor (icon)**
- [ ] gconfeditor (symlink)
- [ ] administration (symlink)
- [ ] control-center2 (symlink)
- [ ] drakconf (symlink)
- [ ] gkdebconf (symlink)
- [ ] gkdebconf-icon (symlink)
- [ ] gnome-desktop-config (symlink)
- [ ] paprefs (symlink)

__________________________________________________

![image](https://user-images.githubusercontent.com/15329494/75111408-bcddd280-5639-11ea-84cb-3bfe565cf7dd.png)
- [ ] **rotate (icon)**
- [x] **object-rotate-left (icon)**
- [x] **object-rotate-right (icon)**

__________________________________________________

![image](https://user-images.githubusercontent.com/15329494/75111424-f1ea2500-5639-11ea-94e7-1a6d61110832.png)
- [x] **object-flip-vertical (icon)**
- [x] **object-flip-horizontal (icon)**
__________________________________________________

![image](https://user-images.githubusercontent.com/15329494/75111547-6f626500-563b-11ea-9889-0a0a1b007f34.png)

- [x] **zoom-in (icon)**
- [x] **zoom-out (icon)**
- [x] **zoom-fit-best (icon)**
- [x] **zoom-original (icon)**

**Comment by madsrh** [comment]
Do you still think the arrows should be orange? 🤔 

IMHO the zoom icons are a higher priority since the[ Adwaita decided to update](https://github.com/GNOME/adwaita-icon-theme/blob/mainline/src/fullcolor/legacy/zoom.svg) only 4 of the zoom icons. This adwaita doesn't fit well with Humanity or Yaru. Also the Humanity 🔍 magnifier icon isn't great in the dark theme.

![image](https://user-images.githubusercontent.com/3986894/75100591-0e517780-55d0-11ea-9569-91ce8f78076f.png)

**Comment by Feichtmeier** [comment]
I'll add them to the list. 
You can prioritize them as you want, since I can not help drawing. :)
I also found other rotate icons which I will add to the list.

**Comment by gusbemacbe** [comment]
Hello everybody!

Sorry for my long absence. Since my grandparents travelled, I have been overcharged with homeworks as feeding and taking care of their pet, cleaning and taking care of their house. 

@Bonandry redesigned some legacy icons I was analysing in his beta repository. 

@Bonandry, hai tempo per ridisegnare le icone legate? Guarda alle icone sopra.

**Comment by Feichtmeier** [comment]
Hi @gusbemacbe 
That would be very cool!

We would love to see them colored though, since the gnome toolkit requests them to be full colored, or better: they don't expect them to be symbolic icons. Would this be possible for you two guys?

**Comment by gusbemacbe** [comment]
Yes, he did coloured legacy icons, I will show his icons.

**Comment by gusbemacbe** [comment]
Hey, everybody, @Bonandy is doing these icons now. We must be waiting.

**Comment by gusbemacbe** [comment]
Here are the previews of legacy icons in some apps which are using legacy icons, made by @Bonandry, and check Evolution, Inkscape and Transmission

- Solitary
![Solitario](https://user-images.githubusercontent.com/2257024/75113793-81d6a180-562f-11ea-96a2-9819645a4cc3.png)

- Asunder
![imageAsunder](https://user-images.githubusercontent.com/2257024/75113804-9e72d980-562f-11ea-83da-8c8ea1f3fa6c.png)

- Evolution

![Evolution](https://user-images.githubusercontent.com/2257024/75113818-bf3b2f00-562f-11ea-9e6a-5698abef0822.png)

- Evolution Send

![Evolution Send](https://user-images.githubusercontent.com/2257024/75113829-d8dc7680-562f-11ea-985b-033f4de2b49c.png)

- Bleachbit

![Bleachbit](https://user-images.githubusercontent.com/2257024/75113836-f27dbe00-562f-11ea-8bfa-858c315121ce.png)

- GParted

![GParted](https://user-images.githubusercontent.com/2257024/75113919-b8f98280-5630-11ea-8bb4-e1d0f13a2a9c.png)

- Inkscape

![Inkscape](https://user-images.githubusercontent.com/2257024/75113928-c9116200-5630-11ea-9a3d-a93a87874341.png)

- Keepass

![Keepass](https://user-images.githubusercontent.com/2257024/75113910-a67f4900-5630-11ea-9073-297f36c21398.png)


- Meld

![Meld](https://user-images.githubusercontent.com/2257024/75113877-691abb80-5630-11ea-9a19-f86d5fa72fa1.png)

- Synpatic

![SYnpatic](https://user-images.githubusercontent.com/2257024/75113895-91a2b580-5630-11ea-9dd1-9632226246cd.png)

- Transmission

![Transmission](https://user-images.githubusercontent.com/2257024/75113889-818ad600-5630-11ea-89a3-082d66f37e3d.png)

**Comment by Feichtmeier** [comment]
Awesome! We're looking forward to this. Do you guys need help with the pull requests?

**Comment by gusbemacbe** [comment]
@Bonandry does not know anything about GitHub. Only I know. He will send the pack to me and I will reconfigure it. But if you want his ready pack, we will send to you.

**Comment by gusbemacbe** [comment]
Hello @Feichtmeier and @madsrh 

Here is his pack: 
[legacy-icons.zip](https://github.com/ubuntu/yaru/files/4241773/legacy-icons.zip)

@Bonandry forgot some icons. I will send some missed icons to him.

**Comment by gusbemacbe** [comment]
@Feichtmeier and @madsrh 

Here are missed legacy icons: 
[missed-legacy-icons.zip](https://github.com/ubuntu/yaru/files/4241903/missed-legacy-icons.zip)

**Comment by gusbemacbe** [comment]
Hello @Feichtmeier and @madsrh again !

Here is another alternative icon of legacy zoom icons: [alternative-legacy-zoom.zip](https://github.com/ubuntu/yaru/files/4242231/alternative-legacy-zoom.zip)

**Comment by Feichtmeier** [comment]
@gusbemacbe @Bonandry absolutely amazing thank you :tada: 

"We" try to get them in for 20.04 - and will ofc credit to you guys! Thank you very much!

**Comment by ubuntujaggers** [comment]
@gusbemacbe @Bonandry Thanks very much for these, this is a heroic effort!

Unfortunately we've decided to back away from providing full colour legacy actions in the theme (including removing the small number of ones we already had).

Basically, these icons were originally out of scope for Yaru, but we encountered a problem where some of the buttons in older apps were getting replaced by a similarly named but wrong Yaru icon (example: various document-* buttons, like "save" and "new", all getting replaced by the same generic document from Yaru).

We responded by providing Yaru icons with the correct legacy name and a suitable metaphor, although ours weren't brilliant.  We've now worked out how to make it so the Yaru icons don't replace the Humanity ones in the first place.

If we include our own icons here, the likely result will be a mix of styles in apps like Inkscape (because the Inkscape-specific buttons will have the old style and ones that are common across apps, like document-new, document-save, will have a different one).  Now we can make the original problem go away, it's safer for Yaru to just leave the legacy actions alone.  Luckily people still have the option of Yaru++ :+1:

Thanks for sharing these files and I'm looking forward to your future contributions (e.g., don't hold back if you can suggest improvements to our existing icons!).

**Comment by gusbemacbe** [comment]
Hello @ubuntujaggers!

> @gusbemacbe @Bonandry Thanks very much for these, this is a heroic effort!

You are welcome

> Unfortunately we've decided to back away from providing full colour legacy actions in the theme (including removing the small number of ones we already had).

> Now we can make the original problem go away, it's safer for Yaru to just leave the legacy actions alone. Luckily people still have the option of Yaru++ :+1:

Too bad, no problems. Yaru++ will include the modern and new legacy icons. @Bonandry redesigned the Inkscape tools icons:

![Inkscape ](https://user-images.githubusercontent.com/2257024/75234515-7e5f2980-5799-11ea-8f7d-9987a10cc628.png)

Hey @madsrh 

I am sorry for bringing your attention, because @Bonandry has been talking with me yesterday. He said he would like to be credited as he is author of some icons as Evolution, Sound Recorder and Totem, and of some mimetypes. Sorry for bringing it. He is sad for not being credited.

**Comment by meetdilip** [comment]
@gusbemacbe If you have made almost the full palette of icons, consider releasing them as Inkscape icon pack. That way Inkscape users will have another option and your hard work will be put into use as well.

**Comment by Feichtmeier** [comment]
@gusbemacbe did he really made the full set of inkscape icons? Could you share a new, complete zip?

**Comment by gusbemacbe** [comment]
@meetdilip, great tip!

@Feichtmeier, no, but here are some icons:  
[inkscape.zip](https://github.com/ubuntu/yaru/files/4251180/inkscape.zip)

**Comment by madsrh** [comment]
As much as we all love Inkscape and know that it really could use some more modern icons, I don't think we should change these, because Inkscape ships with Adwaita icons on the Windows (and OSX I think) version. 
IMO the best solution would be to approach upstream and ask if they would be interested in a dedicated Inkscape theme :man_shrugging:

**Comment by meetdilip** [comment]
They allow it. Even have a showcase for it. But yes, a word with them will be nice.

https://inkscape.org/gallery/=inkscape-gui-icon-set/

I think I posted this and it got deleted. Or it is 12 am and I am too sleepy.

**Comment by Feichtmeier** [comment]
Nice!

https://inkscape.org/~m1981/%E2%98%85icons-inkscape+2
"An iconset to revamp Inkscape main tools."

Future is bright! Okay, then I think we can close this issue here.
But I still think we should keep at least the folder icon, the :heavy_check_mark:  for Ubitquity - WDYT @ubuntujaggers ?

**Comment by ubuntujaggers** [comment]
> Nice!
> 
> https://inkscape.org/~m1981/%E2%98%85icons-inkscape+2
> "An iconset to revamp Inkscape main tools."
> 
> Future is bright! Okay, then I think we can close this issue here.
> But I still think we should keep at least the folder icon, the  for Ubitquity - WDYT @ubuntujaggers ?

Is the folder icon also used in Ubiquity?

**Comment by Feichtmeier** [comment]
No but everywhere else in gtk2 or old gtk3 apps. Otherwise there is an orange folder showing up

**Comment by Feichtmeier** [comment]
Keeping this opened to check if we've have all icons and see if we could optimize it with symlinks even if #2002 has been merged
Thanks  to @ubuntujaggers for raging through the icons and thanks to @gusbemacbe and @Bonandry for providing us a very solid foundation!

**Comment by Feichtmeier** [comment]
Status update: we decided to drop those for 20.04 because they were incomplete.
I think no decision has been made here yet, let's see.

**Comment by Feichtmeier** [comment]
@Jupiter007-43  could you reuse any of the many libre office full colour icons you've made for this full colour action icons here?

**Comment by Jupiter007-43** [comment]
> @Jupiter007-43 could you reuse any of the many libre office full colour icons you've made for this full colour action icons here?

Of course. Which icons are missing?

**Comment by Feichtmeier** [comment]
The list is at the top but I'm not sure if it's complete and I'm not sure which of those icons are handled in @ubuntujaggers 's new PR :) I guess only Stuart knows
