### ISSUE TITLE
Red fill the search stop icon

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1980]
Forwarded from https://bugs.launchpad.net/nautilus/+bug/1857869

It might be better if the search stop icon was red filled. Similar to a stop sign.

**Comment by madsrh** [comment]
WDYT @clobrano (related to https://github.com/ubuntu/yaru/pull/711 )

Would red and more red in hover, be better?

**Comment by clobrano** [comment]
I noticed the change, but I didn't react just because it was an upstream
change. Indeed it was better red, at least on hover, but I think that
reporting it upstream was the right move. Not so much he used a non-adwaita
picture :D
I will update upstream ticket :), and we can keep this open as reference,
what do you think?

**Comment by madsrh** [comment]
Sounds good.

To me, it isn't obvious that the white shape is a button (or a stop sign)

**Comment by clobrano** [comment]
Indeed, and a red color on hover would be easier to understand

**Comment by clobrano** [comment]
green light for the change https://gitlab.gnome.org/GNOME/nautilus/issues/1375#note_722795

(actually the very first time a gnome dev says we can change the theme :D)
