### ISSUE TITLE
20.04 Inconsistent Nautilus icon

### ISSUE THREAD

**Issue by memeplex** [ubuntu/yaru#2130]
I refer to a recent discussion in Discourse:

https://discourse.ubuntu.com/t/yaru-folder-icon-doesnt-match-others-in-ubuntu-20-04/14943

I see two issues here:

* The icon is the only one with a background
* The folder style grossly mismatches the new folder icons in 20.04

I consider this to be a regression from 19.10, it's a subjective opinion but both points above are objective.

![image](https://user-images.githubusercontent.com/2845433/78399118-b6dcf900-75ca-11ea-9996-c7a2ba4810f8.png)

**Comment by Feichtmeier** [comment]
It's not the only icon with a background. It should not match the folder icon because it's not a folder but an icon for an app. In fact the icons you've shown in this example all work the same way except ubiquity and libre office
Baseplate + a white piece of paper glyph on top of it. 
It feels like the millions time we talk about this and please look up the other discussion about this. Thanks for contributing
