### ISSUE TITLE
Use dark background on input on lock screen \ gdm

### ISSUE THREAD

**Issue by otavioschwanck** [ubuntu/yaru#2147]
The white input background make the design inconsistent.  The vanilla gnome has black background and its very beautiful.

Vanilla:
![image](https://user-images.githubusercontent.com/9551316/79177371-9ac32e00-7dfa-11ea-8edb-5ad867295c47.png)

Yaru:
![image](https://user-images.githubusercontent.com/9551316/79177423-af072b00-7dfa-11ea-97a1-42079d23f380.png)

**Comment by clobrano** [comment]
Hi @otavioschwanck, thank you for taking time to contribute.
We discussed this detail quite a lot (and it's indeed a bit under discussion, yet). I think that white is still more flexible though.

For example, this entry is used as well in the lock screen, where the background can have different colours, since it comes from the blurred wallpaper, and a dark entry with light (or simply a non-dark wallpaper) is less pleasant than a white entry on a dark background, IMHO.

**Comment by otavioschwanck** [comment]
@clobrano maybe a little blurry transparent input, its not possible ?  It will match the background

**Comment by clobrano** [comment]
Blurry is not possible, and little transparent would make it harder to see the text on bright backgrounds I think
