### ISSUE TITLE
tab bar background missing in guake

### ISSUE THREAD

**Issue by marhkb** [ubuntu/yaru#2149]
## Expected Behavior
Tab bar background has some opaque colour when setting gtk theme to yaru-{dark} in dropdown terminal guake.

## Actual Behavior
Tab bar background is totally transparent.

## Steps to Reproduce the Problem

  1. Install guake
  2. select "yaru-{dark}" as gtk theme in guake settings

## Software that presents the issue

- Name: guake
- Version: 3.7.0

## Yaru version

20.04.5-1 from Arch Linux AUR

![guake-yaru](https://user-images.githubusercontent.com/3630213/79354697-09a8a000-7f3d-11ea-8c31-31a4d18c003f.png)

**Comment by ad3luc** [comment]
Also in my Ubuntu 18.04 machine using the dark theme the the tab bar is transparent

As you can see we can read the chrome title name in center when guake is open

![image](https://user-images.githubusercontent.com/12545775/80340215-881c1080-8860-11ea-8297-351501dfffcd.png)
-------------------------------------------------------------------
### OS
Os: Ubuntu 18.04.4 LTS
Shell: GNOME Shell 3.28.4

### Guake
Guake Terminal: 3.7.0
VTE: 0.52.2
VTE runtime: 0.52.2
Gtk: 3.22.30

### Theme
Version: 29.187
installed via snap

**Comment by Feichtmeier** [comment]
Damn, yeah this is caused by setting tabs bg to transparent, pretending that every app uses them in a sane way, yet I am always surprised how weird the combinations can be.
We can fix this by giving them back a background but need to be careful with giving them the correct background for all possible combinations (prbly only $base_color for all but $bg_color for nautilus because we have switched the colors there for **some** reason *looking at @madsrh and @clobrano 😍 👀 )

**Comment by Feichtmeier** [comment]
@marhkb where did you get that neat monochrome telegram indicator from btw? 😄

**Comment by marhkb** [comment]
Its from Papirus Icon Theme
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme

To apply it on indicators I use
https://github.com/bilelmoussaoui/Hardcode-Tray

and execute
`sudo hardcode-tray --size 22 --theme Papirus --apply`

**Comment by clobrano** [comment]
Not reproducible in 20.04.8. 
Consider that the switch from yaru/yaru-light to yaru-dark requires guake restart.

**Comment by mfonville** [comment]
For me this very same bug is happening again on Ubuntu 21.10 with Guake 3.8.0 and higher

**Comment by andrea-de** [comment]
I'm also having this problem with `guake_3.8.1-1~ppa~focal0_all`

**Comment by mfonville** [comment]
@Davidy22 and @mlouielu are you aware of this issue too?

**Comment by Davidy22** [comment]
No changes were made to tab bar style interpretation in Guake from 3.7 to 3.8. What you might be noticing instead is the new tab bar hide behavior that by default hides the tab bar if there is only one tab, which can be toggled off in the preferences menu.

**Comment by Davidy22** [comment]
Didn't have any idea of how this could have regressed, but something just came to me so I'm back. From Guake 3.8 onwards a checkbox was added labelled "Use system default theme," which will attempt to detect and use the system default theme. It was set to be enabled by default. If you uncheck that box and fiddle with themes, do you notice the issue persisting? And if it only happens for some themes, which ones does it happen for?

**Comment by mfonville** [comment]
@Davidy22 Yes I have fiddled already with that checkbox and various options in the drop down. The issue always happens with Yaru-dark or Yaru in dark-mode, but it e.g. also happens with the Radiance theme. All other themes (including the light version of Yaru) seem to be working correctly.

**Comment by fernandonavajas** [comment]
I'm also having this problem
![bar tab transparent](https://user-images.githubusercontent.com/23393394/141199739-f6b31850-15cf-46d4-8443-ee2f4eaf4a67.gif)
I dont see the tab labels :C

**Comment by Davidy22** [comment]
So there's two things going on I believe. When this issue was "fixed," Guake was actually just not using the Yaru theme. When the "Use system default theme" option was added and made default, this issue resurfaced because Guake started using the system Yaru theme again for people who have it set, and the underlying issue wasn't actually dealt with so this issue returned.

Just spitballing because I'm using a DE without a Yaru option and can't actually try it out, but I suspect this happens because guake is drawn as just a GTK notebook widget with no window decorations or anything underneath, and if I'm reading @Feichtmeier's comment right yaru sets the tab bar in a GTK notebook to be transparent so it looks transparent because we have nothing drawn behind it. Given that Yaru is in the minority of themes this happens for, one solution would be for Yaru to make like the other themes and also color in the tab bar, even if it'll be the same color as what would normally be under it. I've incidentally been looking for a way to get a window decoration in GTK without the titlebar that doesn't mess with our positioning for unrelated cosmetic reasons, and if I eventually find a solution for that in the documentation that may just incidentally fix this as well, been stumped on that one for a little while though.

**Comment by Jupi007** [comment]
I can confirm the problem on 21.10 using guake 3.8 from the ppa.
I also found a way to fix it. I'll make a patch very soon.

**Comment by Jupi007** [comment]
This need to be backported, but honestly I don't know exactly how to do this.
I'll try to find a solution because we also have some more patch to backport.

**Comment by erichlf** [comment]
I switched to the Yaru them and then back to the system default and this resoved the issue for me.
