### ISSUE TITLE
nemo: renaming file on icon-view has wrong highlight color

### ISSUE THREAD

**Issue by fcastilloec** [ubuntu/yaru#2183]
## Expected Behavior

I'm trying to rename a file while on icon-view, and the highlighted text (filename) should be a distinctive one.
Here's a GIF on how it looks on list-view, where the highlighted text is working correctly in nemo:
![list](https://user-images.githubusercontent.com/1280530/81338425-7822de80-9061-11ea-95b7-f233a1f467ac.gif)

## Actual Behavior

The highlighted text is not apparent. It feels like nothing was highlighted; if looking carefully, it seems like it's in bold at most.
![icon](https://user-images.githubusercontent.com/1280530/81338455-8244dd00-9061-11ea-9da5-dff03c57e760.gif)

## Steps to Reproduce the Problem

  1. Make sure nemo is set as icon view.
  1. Rename a file (either by pressing F2, or from a menu)

## Software that presents the issue

- Name: nemo
- Version: 4.4.2

## Yaru version

Official version from Ubuntu repositories: `v20.04.6`

**Comment by Feichtmeier** [comment]
We hardly support Nemo, but since there is some Nemo code inside yaru, we could eventually fix it.

**Comment by rddunphy** [comment]
There is a fix for this issue in Nemo, as well as a related issue where the background of split screen panels is shaded incorrectly: https://github.com/linuxmint/nemo/issues/1173. The fallback CSS with the fix is only applied to themes that don't support Nemo, which, if I've understood correctly, it determines by searching for the string "nemo" in the theme's code, so it's not applied to Yaru. Adding [this](https://raw.githubusercontent.com/linuxmint/nemo/master/gresources/nemo-style-fallback-mandatory.css) to `gtk.css` fixes both issues for me. (The same is the case for the default, light, and dark themes.)

**Comment by clobrano** [comment]
thanks @rddunphy!
