### ISSUE TITLE
Non-core app icon overrides

### ISSUE THREAD

**Issue by bertob** [ubuntu/yaru#2196]
## Expected Behavior

Only GNOME core apps or pre-installed apps have themed icons.

## Actual Behavior

It was brought to my attention that Transmission's icon is being overridden by Yaru. That's a bit odd, because it's very far from being a core app and not pre-installed (as far as I know). I had a quick look at the repository and found a few other apps in the same situation:

Edit by @Feichtmeier :
- ~~Transmission~~ --> Got OK from the devs
- [ ] Remove Games symlink
- [ ] Remove Podcasts symlink
- [ ] Remove Notes/Bijiben symlink
- [ ] Remove Books symlink
- [ ] Remove Evolution symlink
- ~~Remove Todo symlink~~ --> Preinstalled
- ~~Rhythmbox~~ --> Preinstalled
- ~~Tweaks~~ --> I think we need to keep this, because it's an elemental app for the desktop, yet not pre-installed

If any of these come pre-installed on Ubuntu feel free to ignore, but for the others it would be good if Yaru wouldn't override their icons. I'm aware that the definition of what is and isn't a core app can be unclear in some cases, but hopefully [this initiative](https://discourse.gnome.org/t/official-proposal-how-we-define-gnome-software/3371) will help improve this in the future.

**Comment by clobrano** [comment]
Hi @bertob, thanks for reaching out directly to us for this.
We do not theme non-core apps unless agreed with the maintainer, which is what  happened with Transmission https://github.com/ubuntu/yaru/pull/1426

I am not 100% sure about the others instead, because I usually do a minimal install, which has no applications, but I remember Rhythmbox being a default one (at least some time ago). I will double check for the others :+1:

**Comment by Feichtmeier** [comment]
Yup transmission people agreed on our icon as carlo already linked
Rhythmbox and ToDo were not explicitely asked but they are indeed pre-installed in Ubuntu, so we would probably prefer to keep those icons. 
We can def. remove the rest since they are not pre-installed 👍 (just symlinks to be removed)

**Comment by bertob** [comment]
Sounds good, thanks!

**Comment by bertob** [comment]
> Tweaks --> I think we need to keep this, because it's an elemental app for the desktop, yet not pre-installed

I don't think that makes sense. Tweaks was always an unofficial thing and has been unmaintained/on its way out for years.

**Comment by Feichtmeier** [comment]
It's still installed on many ubuntu machines. And pretty generic if you ask me... Is this really hurting your gnome brands? :thinking:

**Comment by ubuntujaggers** [comment]
If Tweaks is unmaintained and on its way out, sounds like the icon doesn't matter either way 🤷
