### ISSUE TITLE
application-apk icon is misleading

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#2251]
Since the Android APK mime type icon uses the zipper, it is associated with a compressed file.
IMHO it would be more correct to use the package metaphor (although a package is also an archive).

This issue is just a reminder to revisit the icon and align the design with Flatpacks, Snaps and the likes, once some design guidelines are in place.

**Comment by Feichtmeier** [comment]
I think those archives for packages are generally a good idea. But I agree that one should understand what's inside. How does it currently look compared to .jar or .Deb ?

**Comment by avil25** [comment]
What do you think about something like this
![application-apk-2](https://user-images.githubusercontent.com/40562410/87229624-2ed76e00-c3c7-11ea-86ea-8030db6e204c.png)

or something similar to the one we already have for .deb files
![application-apk](https://user-images.githubusercontent.com/40562410/87229637-54647780-c3c7-11ea-9e33-6b2457fcde3f.png)

Sorry I am not really good at designing but trying to give some ideas.

Jar icon is similar to the one we have for the archive. Snap and flatpacks have a simple file icon with there logo in the middle.
similarly, windows icon also look misleading and unrecognizable(but I think we can't use the windows logo that's why it's like that)

**Comment by madsrh** [comment]
I personally prefer your second suggestion.

> similarly, windows icon also look misleading and unrecognizable(but I think we can't use the windows logo that's why it's like that)

We cannot use the official Windows logo

**Comment by ubuntujaggers** [comment]
That little robot in the bottom right is going to be indistinguishable at normal sizes, but I like the concepts :+1:

**Comment by Muqtxdir** [comment]
Hi,
What about this, too simple and boring right?
![apk](https://user-images.githubusercontent.com/54065734/87244317-f896fe80-c459-11ea-8a3c-3ea1b33a228c.png)

Thanks!

**Comment by Feichtmeier** [comment]
The thing what I like about that Zipper metaphor, is that it correctly says what that file is. 
A jar can be run by a java runtime but it also contains other files, compressed. If you remove the zipper from the icon this metaphor goes away

**Comment by madsrh** [comment]
This one also looks good @Muqtxdir 😄

> The thing what I like about that Zipper metaphor, is that it correctly says what that file is...

IMHO we should not merge a new design before we've decided on some kind of guidelines. I will try to come up with a suggestion soon.

And thank you so much for contributing! We love feedback but we lloooooovvvveeee contributions ♥️

**Comment by avil25** [comment]
So few ideas for guidelines.
we can divide packages into two halves 
1. The one that can be extracted easily like deb, jar, rpm, apk, etc for them we can use some kind of archive icon that tells its archive  files and also the icon that tells they can be installed 
2. the packages that are not easy to extract like snap flatpack, exe, etc for them we can use similar icon without the archive icon

One idea I can think of is we can use the belt icon for the first one instead of the zipper icon that IMO denotes that they are packed instead of zipped. For 2 cases we can exchange them belt with tape symbol(similar to the one in our deb icon). Example of the belt icon(although I do not know how to make it yaruish).

![zip-rar-computer-icons-computer-file-file-format-winrar-thumb](https://user-images.githubusercontent.com/40562410/87382185-f6e14e00-c5b3-11ea-9f0f-b8c4679087f5.jpg)

**Comment by clobrano** [comment]
I like the idea do show both nature of the file, but I agree as well that there must be coherence.
I downloaded a couple of files to compare:

- jar: zip + jar label
- apk: zip + android icon
- deb: package format + debian icon
- flatpak: flatpak icon
- snap: snap icon

As far as I know, jar and apk cannot be installed (at least not like the other formats), so I think the representation is right, the only thing you can do normally from Nautilus is open them as archive, but for this, from my POV, we can either use the zip or the package icon (like debs)

snap and flatpak are not meant to be opened (I never saw a flatpak or snap file in my hd), not sure if you can do much with them, other than install them. I'd like the snap mimetype to be as colorful as the flatpak one btw :smile:

Debian file is in the middle, one can both install it and open it with double click

**Comment by Feichtmeier** [comment]
@clobrano agree :+1: 
Additional info: You can run specific jar files as if they were binaries (still archives) with the java command (java -jar), and I think we even have a specific mimetype for those "executable jars"

**Comment by avil25** [comment]
@clobrano you are absolutely correct. We can not install apk and the only thing we can do is open them as an archive but its still packaging format and not an archive format. Also, snap and flatpak can not be viewed as an archive in an easy way but still, they are packaging format currently their icon looks like a normal file icon not as something that can be installed. Although if this is not going to happen then +1 for a more colorful snap icon.

**Comment by Feichtmeier** [comment]
Are .snap and .flatpak files the real container images or are they only some kind of config file their runtimes know how to handle with some URL's to the real images inside?
If they are "just" a text file with some lines in it, I think the current icon is okay. Otherwise probably not

**Comment by avil25** [comment]
.snap are not a config file they are real container files.
You can verify this by 
`snap download firefox`
It will download around 250mb of .snap file and .asset file (which is a config file)
For Flatpak .flatpakref is a config file and .flatpak is an image( I guess this by what I read. I don't use Flatpak  so I am not sure)
You can also export Flatpak app as .flatpak file by the instruction on this page [Single-file bundles](https://docs.flatpak.org/en/latest/single-file-bundles.html)

But it's not that easy to download and install snap and flatpak from a file( at least not as easy like to download and install exe file)
so not sure if many people will see these files ever.

**Comment by Feichtmeier** [comment]
So, we kind of agree that we leave it as it is? Or? What is the outcome ? ^^

**Comment by madsrh** [comment]
> So, we kind of agree that we leave it as it is? Or? What is the outcome ? ^^

Yes, let's leave the _application-apk_ but I don't know if other icons need a revisit? 🤔 I seems that packages / archives / containers is where the rules aren't clear, but let's continue that in a dedicated issue 😃
