### ISSUE TITLE
gnome-web preferences page tabs are too close

### ISSUE THREAD

**Issue by Muqtxdir** [ubuntu/yaru#2364]
Hi,
The new GNOME-Web preferences page is not compatible with Yaru theme

**GNOME-Web (3.38) on Yaru:**
![yaru-web](https://user-images.githubusercontent.com/54065734/93791852-5f9f1380-fc52-11ea-8786-2c9f6c91c76f.png)

**GNOME-Web (3.38) on Adwaita:**
![adwaita-web](https://user-images.githubusercontent.com/54065734/93792044-9ffe9180-fc52-11ea-9331-fc4f7774ae43.png)

Thanks!

**Comment by Feichtmeier** [comment]
I thought this could be fixed by adwaia padding alone, but after a quick look at gnome web, it looks like they have kind of an own army of scss files specifically for adwaita.... This is kinda embarassing but let's see what we can do. What I would like not to do is to include this big load of custom css into _apps.scss
The best thing would be if they would put Yaru on their supported themes list. Because look look, adwaita is not the only one, they also provide eOS theming
