### ISSUE TITLE
Icons: Humanity inheritance?

### ISSUE THREAD

**Issue by barmadrid** [ubuntu/yaru#2635]
This is more of a question than a bug!

I understand that Yaru icon theme inherits Humanity icons. Does this mean it also depends on the Humanity icons package (the package _must_ be installed along Yaru)?

Thanks!

**Comment by Feichtmeier** [comment]
I think not. But @ubuntujaggers might have an opinion

**Comment by ubuntujaggers** [comment]
Good question, and I don't actually know what would happen if you didn't have Humanity installed...?

**Comment by barmadrid** [comment]
I did not notice anything when Humanity was not installed, but I'm not an expert in this!

Is it okay for us to remove Humanity from Yaru's inherit list?

**Comment by chrisjbillington** [comment]
If you remove humanity, then you've got no fallback - the remaining "hicolor" isn't a theme per se, it's where apps put their custom icons to ensure they're part of the fallback for any other theme.

So by removing it you're declaring Yaru to be comprehensive and not require any fallback.

I am 70% I still see humanity fallback icons in some apps when running Yaru. Will try to find an example, perhaps it's no longer true.

**Comment by Feichtmeier** [comment]
We could inherit Adwaita instead but I'm not sure if this would make the situation and better

**Comment by barmadrid** [comment]
I really like the Adwaita suggestion! @Feichtmeier 

For me, it will be one less package installed on the system (Humanity) and Adwaita is actively maintained and a dependency of gtk in many distros anyway!

**Comment by trwired** [comment]
Humanity still seems to be used as a fallback for quite many icons, among them actions and mimetypes. For example if you run Audacious in stock Ubuntu, most of the icons shown in the application's default UI will come from Humanity.

**Comment by Amr-Ibra** [comment]
Humanity is used by all apps that require coloured action icons that don't exist in Yaru, and by some old apps like the Synaptic package manager. If Humanity is not installed, Adwaita will be used if installed. If Adwaita is not installed, the apps would look broken.

I don't recommend inheriting from Adwaita because their coloured action icons, in my opinion, look worse than Humanity and are basically dead in terms of development since many years. They treat their coloured action icons as "legacy" and not used anywhere in a GNOME system.

**Comment by Feichtmeier** [comment]
Ok - let's just continue to fill the gabs with Humanity until we've successfully replaced all free desktop icons with Yaru icons.
See #2669
