### ISSUE TITLE
x/y ratio, wrong icons appearance in app grid icons

### ISSUE THREAD

**Issue by fthx** [ubuntu/yaru#2734]
Hi,

I do use Ubuntu Focal, here with Ubuntu (X or Wayland) session.
I installed Hirsute's latest 21.04.1 Yaru package. I know it's bad. :-)
But I like very much the changes, especially the black menus instead of white and the huge icons set comparing to 20.04.10.

Well, everything *seems* ok but one thing, in app grid:

![image](https://user-images.githubusercontent.com/23138504/111813189-2aaa0b80-88d9-11eb-8a21-6ecbd237b2af.png)

Is that due to my Focal experiment or is that a bug?

**Comment by fthx** [comment]
Note that icons positioning is wrong too in app grid folders:

![image](https://user-images.githubusercontent.com/23138504/111813463-870d2b00-88d9-11eb-9de3-3dbda88221cd.png)

**Comment by Feichtmeier** [comment]
Hi there @fthx 
You should not install hirsute yaru shell on focal really. It will def. break and so it did :D 
The css part is matched to JS parts in the shell and the JS parts change constantly with every gnome shell major release. 
Eventually we try to backport the recent design changes to focal, but most likely only when the whole gnome stack would be backported, which is, looking back at previous releases, very unlikely :( I know the feeling, I mostly try to stay on LTS, too, but since I use more and more snaps, I finally broke up with this tradition and upgrade to the small releases too :)

**Comment by fthx** [comment]
Ok thanks!
So I use a GNOME session running Yaru 21.04.1 gtk-theme. Seems fine.
:-p
