### ISSUE TITLE
Update GNOME Software (and maybe GNOME Web) icon based on new upstream

### ISSUE THREAD

**Issue by vitalkanev** [ubuntu/yaru#2752]
I am not using a template so people could discuss stuff I think.

Icon name | Current Yaru icons | New upstream
----|----|----
`webbrowser-app` | ![YaruBrowser](https://user-images.githubusercontent.com/18398761/112866844-eda4fc80-90c2-11eb-9641-8d1c17910acd.png) | ![NuBrowser](https://user-images.githubusercontent.com/18398761/112866926-031a2680-90c3-11eb-8b15-878dcb25e175.png)
`org.gnome.Software` | ![YaruSoftware](https://user-images.githubusercontent.com/18398761/112869621-09f66880-90c6-11eb-9a87-b6e810a8a2df.png) | ![NuSoftware](https://user-images.githubusercontent.com/18398761/112869623-0a8eff00-90c6-11eb-9de4-7924f55c266f.png)

What do you think: should we make new version of above icons? Or do something else?

**Comment by Feichtmeier** [comment]
Since those apps are not pre-installed they are not so super important.
But currently we have a nice set of yaru icons for all core gnome apps except those gnome designers explicetly asked us to remove (podcast app for example :shrug: )
Anyways, since the current ones are fine, and we got much to do anyways, I would rather categorize this as low prio or eventually not do this at all. However, if our icon designers are interested they could eventually create something different here if it makes sense.
Looking at the browser icon, I really think the current classy yaru navigator icon is a pretty damn solid icon. Mimicking upstream without thinking about it is not my cup of tea :tea: :)
The software icon could eventually be yarufied though.

**Comment by clobrano** [comment]
What do you think about dropping the "status: discussion" tag and just converting the bugs into github's discussions?

**Comment by Feichtmeier** [comment]
sounds very good!
