### ISSUE TITLE
Add an option to disable dimming of inactive windows

### ISSUE THREAD

**Issue by jay** [ubuntu/yaru#2788]
**Expected Behavior**

There should be an option to disable dimming of inactive windows

**Actual Behavior**

Inactive window is dimmed

**Steps to Reproduce the Problem**

- Switch to window 1
- Switch to window 2
- Observe window 1, now inactive, has dimmed

**System information**

GNOME Shell 3.36.7
Ubuntu 20.04.2 LTS

**Yaru version**

Package: yaru-theme-gnome-shell
Version: 20.04.10.1

Ref: https://askubuntu.com/questions/1146348/disable-inactive-window-dimming

**Comment by Feichtmeier** [comment]
Do you mean the :backdrop dimming?
This is out gtk styling, which comes from upstream gnome.
We control the backdrop colors in _colors.scss and changed them a little bit from upstream to use rather transparentized white than gray color in the dark theme
Apart from this change we did not change much and follow upstream with the backdrop look.
I am personally very happy with it. We discussed this topic a lot
#2389
#212

If you only talk about a toggle, this is not something we can provide from (s)css, and sounds like a gsetting that does not exist

So in both cases this is either a "won't fix" because we are happy with the design or a "can't fix" :)
