### ISSUE TITLE
Revisit Dark Theme contrast

### ISSUE THREAD

**Issue by qwertychouskie** [ubuntu/yaru#2794]
I just recently upgraded to Ubuntu 21.04 Beta on my system.  Although I'm liking some of the changes here (Dark shell theme by default is a big one, the tweak to the sidebar in Files is quite nice, and I'm always happy to see general refinements), the dark theme subjectively feels much too dark now.  Before, the grays were easy on my eyes, but now, the large contrast between text and background makes it feel much harsher than before, and also makes the now-default dark shell theme integrate less nicely with the default theme.  But perhaps most importantly, it creates a large contrast between dark OS content and whatever light content may be present, especially web pages, rather than acting as an easy transition.

Compare the nicer "gradient" from fulldark to light with Canta-dark (which is more similar to previous Yaru-dark), and the lesser contrans between OS and content:
![image](https://user-images.githubusercontent.com/13989090/114807377-28619280-9d5b-11eb-97f8-baf178daa1b2.png)

Vs. current Yaru-dark, and how there's a much larger contrast between the OS and content:
![image](https://user-images.githubusercontent.com/13989090/114807287-00722f00-9d5b-11eb-825d-a0e9b87ad3f7.png)

I really hate to be "that guy who comes from nowhere just to complain", but I though I'd at least gather feedback and see what others think.  StackExchanges' dark theme implementation blog post might be a good point of reference here: https://stackoverflow.blog/2020/03/31/building-dark-mode-on-stack-overflow/

Thoughts?

**Comment by Feichtmeier** [comment]
Hello there 😊

Nothing is wrong with expressing your opinion.

Ofc the contrast between the white website and the dark window is too high. But it's too high on both cases. That's why extensions like that dark mode extension exists for Firefox and Chrome. Also in this specific case there is the github darktheme toggle which follows the system is you use Firefox.

But I agree on the button to window contrast. After the palette change the accent colours and the BG colours fit better together but there is room for improvement on the $bg_colour Vs $base_colour contrast and also the buttons could be brighter.

We'll work on this next cycle

**Comment by Feichtmeier** [comment]
The contrast is now very nice for gtk4
![](https://user-images.githubusercontent.com/15329494/121771893-7ab00b80-cb72-11eb-903b-134aa0ca4890.png)

**Comment by Muqtxdir** [comment]
hi @qwertychouskie 

the dark theme has gotten so many improvements and fixes since 21.04 and the colors have definitely improved and look well in the recent releases. If you still feel that the dark-theme still needs improvements you are welcome to share your suggestion, in this discussion [2684](https://github.com/ubuntu/yaru/discussions/2684)

Thanks!
