### ISSUE TITLE
missing icons of books, games, podcast, connections, synaptic package manager, okular

### ISSUE THREAD

**Issue by kothekarswaraj** [ubuntu/yaru#2799]
**Icon Request**
gnome's  podcasts, connections, books, games
synaptic package manager
kde okular
icons are missing

**Steps to locate the icon**

**Software where the icon is missing**
I downloaded these apps from 
flathub- gnome's connections, podcasts, okular
ubuntu hirsute repo 21.04- gnome's books, games, synaptic package manager

**Screenshots**
[https://flathub.org/apps/details/org.gnome.Connections](url)
[https://flathub.org/apps/details/org.gnome.Podcasts](url)
[https://flathub.org/apps/details/org.kde.okular](url)

**Comment by Feichtmeier** [comment]
We had Gnome podcasts but gnome designers explicitly asked us to remove it, which we did. I'll link the issue when I find it

**Comment by vitalkanev** [comment]
@Feichtmeier
Looks like this issue https://github.com/ubuntu/yaru/issues/2196

**Comment by Feichtmeier** [comment]
Thanks @vitalkanev :)

**Comment by Feichtmeier** [comment]
hey @bertob 👋 

could you update us on how important it is for the gnome community to not override "unbranded" / rather generic icons like gnome podcasts, games, etc? I mean, thinking of the users, I think they would prefer rather a consistent look rather than the upstream icon. WDYT? No hard feelings, just asking :)

**Comment by kothekarswaraj** [comment]
what is up with those gnome developers?
Yaru's whole theme looks top-notch even windows & mac theme looks faint.
Gnome developers should use yaru on their gnome os and make it official.
Ever saw their windowing theme what is that?
but the gnome project is open so how can they say so?

**Comment by Feichtmeier** [comment]
(((( We appreciate your appreciation <3 But let's please keep the offtopic out of this issue. If upstream wants to use Yaru or not could be asked on their GitLab. ))))

**Comment by kothekarswaraj** [comment]
I am new to GitHub so it might take time for me to get to work. I am learning & puzzled by so many things on this page.
At this point, I can only put issues.

**Comment by bertob** [comment]
Overriding app icons, especially for third party apps, is problematic because It dilutes an app's identity. For example, the icon you see on your desktop is not the same as on documentation/website/Gitlab/blogposts/etc. It also does not scale, because you'd need a ton of resources to keep up with every single third party app, including all the new ones being released continuously. It's a neverending task and there's always going to be stuff that sticks out.

So yes, you should never do it for third party apps. For first-party/preinstalled ones it's a bit easier since there's only a limited number of them that changes very slowly. Custom icons for those tolerated as a kind of compromise, but it's not like upstream people are in favor of that, either.

Fundamentally, if you want all icons to use the same style the only realistic option is to use the upstream ones.

**Comment by Feichtmeier** [comment]
Alright! Thanks for the answer @bertob 
We can close this issue then.
