### ISSUE TITLE
for third party apps(non gnome apps) - window bar width & minimise, maximise, close buttons size

### ISSUE THREAD

**Issue by kothekarswaraj** [ubuntu/yaru#2805]
**Expected Behavior**
width of window bar must be same for all apps including the third party say LibreOffice
also, the spacing & size of minimise, maximise & close icon must be equal for third-party apps as well

**Actual Behavior**
width of window bar is less for third party apps say LibreOffice 
also, the spacing is less & size is small of minimise, maximise & close icon 

**Steps to Reproduce the Problem**
open any gnome app say settings and open say LibreOffice 
keep switching between those two while focusing on the window bar & 3 icons on top right corner u will notice the difference
while comparing to the browser make sure u have turned on the use system title bar & borders turned on & still there is problem.

**Software that presents the issue**

**Yaru version**
yaru used in ubuntu 21.04

**Screenshots**

**Upstream check**

**Comment by Benni3-1415** [comment]
The header bar is larger, because the Gtk feature _Client side window decorations_ is turned on. The height depends on the widgets inside it.
Most Gnome apps (i. e. not [Shotwell](https://wiki.gnome.org/Apps/Shotwell "Gnome wiki")) have buttons in the header bar and require this feature.

Yes, it looks inconsistent, but aligning the heights isn't a real solution either, IMO.

**Comment by Feichtmeier** [comment]
>  width of window bar is less for third party apps say LibreOffice

This is intended and as @Benni3-1415 said - a titlebar is not always a headerbar and a headerbar is not always a titlebar
