### ISSUE TITLE
Suggestion: add depth to GTK4 tabs

### ISSUE THREAD

**Issue by LinuxLlama** [ubuntu/yaru#2892]
This issue is completely subjective and I'm fine if the design team has their own preferences regarding this matter. It's a small, minute detail.

![adwaita](https://user-images.githubusercontent.com/29968331/121227517-8208a980-c840-11eb-99c2-28a6b4187e28.png)

This is how upstream tabs look. In contrast, here's Yaru's tab design.

![yaru](https://user-images.githubusercontent.com/29968331/121227608-99e02d80-c840-11eb-8d2b-281912c69494.png)

In my eyes, these tabs look unpolished. Adwaita has a thin strip flanking each side of the highlight effect to simulate depth, which isn't present in Yaru. It only uses a simple highlight effect. Here's a mock-up which reintroduces the strips in Yaru.

![yaru_alt1](https://user-images.githubusercontent.com/29968331/121227774-ceec8000-c840-11eb-8576-f6c08f500015.png)

I didn't do a perfect job by any means, but doesn't it look a little less flat this way? By no means does this actually fix anything, I think it would just be a nice polish to the interface.

**Comment by Feichtmeier** [comment]
in general we are more flat yes, and this will prbly not change.
however with gtk4 + libadwaita upstream is closer to yaru and yaru is closer to upstream resulting in almost exactly the same look, just a bit less round and no gradient on the headerbar

This specific case has already been addressed in the last PR - the view switcher looks 100% like in upstream. Can post pictures later, or you test it yourself if you have time, @Jupi007 added instructions to build gtk4 in the contribution file :) 

Closing since it is "already fixed" for gtk4

**Comment by LinuxLlama** [comment]
Thanks for the response, @Feichtmeier 

I'll definitely test building GTK4!
