### ISSUE TITLE
Cursor change is a bit radical

### ISSUE THREAD

**Issue by chrisjbillington** [ubuntu/yaru#2920]
Old cursor:

![image](https://user-images.githubusercontent.com/1044087/122625371-d991eb00-d072-11eb-9741-cd99c81ba4b5.png)

New cursor:

![image](https://user-images.githubusercontent.com/1044087/122625318-89b32400-d072-11eb-9669-96ea744f59ab.png)

There isn't much innovation in default cursors anymore, OSs and themes seem to have standardised on an arrow with a stem like Yaru had previously.  (and standardisation on something that basic is a good thing IMHO!)

The new cursor seems to draw inspiration from macos:

https://support.apple.com/en-au/guide/mac-help/mh35695/mac

But macos only excludes the stem when it's displaying extra icons around the cursor. I think that's totally fine, but for the default cursor (when not indicating a special action) to lose the stem I think creates a bit of friction for users of other OSs, that sticking to the standard by including a stem would avoid.

Without a stem the cursor gives vibes of a cursor from a video game rather than an OS.

**Comment by Feichtmeier** [comment]
Hi Chris :wave: 
Yes it is a big change - but we talked and discussed it in several PRs. It looks like we are going to use this cursor now, but considering you often have a good veto, let's have some last opinion round on this topic. CC @ubuntu/yaru-team

**Comment by chrisjbillington** [comment]
Appreciate my subjective opinion being taken seriously :p. If you go for it I will definitely get over it and not flip any tables. But yes, I do think it is a shame to move against the grain on one of the few things that has been standardised across OSs, and it was genuinely jarring when I first saw it. I suspect there'll be a bit more pushback than just me.

I see PR #2868, were there others?

**Comment by Benni3-1415** [comment]
The original PR: #2868

The new design is actually inspired by Adobe (it is used as the default cursor in e. g. Illustrator) and the Yaru cursors with _additions_ (or extra icons).

I expected this argument and I think you get used to the cursor quickly, because you see it every day.

**Comment by ubuntujaggers** [comment]
Having used the new cursor a bit and had time to get used to it, I definitely like the new hands :+1: but I prefer the traditional arrow.

I think my question would be, what does changing the arrow improve?  It didn't look bad and there weren't any usability issues.  For some reason the stemmed arrow draws my eye to the tip of the arrow (where the hotspot is) while the current one draws it more to the centre - perhaps because it's a less uneven shape?  Obviously that's a miniscule effect, but I guess it comes back to: if Windows and MacOS and major Linux themes use a stemmed arrow, what improvement do we achieve by being different?  What's the problem we're solving with this change?

The reasons in the original PR are a) it has fewer irritating details and b) it looks more modern.  I think both are very subjective; I think of the stem as a key part of the arrow symbol rather than a detail - by removing it we make the cursor even more abstract - and I don't think either design looks more modern than the other, personally.

**Comment by madsrh** [comment]
I really thought that this new design would grow on me (I use Adobe applications every day), but it's hasn't.

>  I definitely like the new hands 👍 but I prefer the traditional arrow.

@ubuntujaggers said it 👍

The good thing about this being in master is that more people have been testing it. It hasn't shipped in a release yet and UI freeze isn't until September, so there's plenty of time.

**Comment by Benni3-1415** [comment]
> For some reason the stemmed arrow draws my eye to the tip of the arrow (where the hotspot is) while the current one draws it more to the centre - perhaps because it's a less uneven shape?

This is how it would look corrected:
![left_ptr](https://user-images.githubusercontent.com/73243667/122776067-0a5c6500-d2ab-11eb-9ad2-b10d367d5336.png) ![left_ptr (12px)](https://user-images.githubusercontent.com/73243667/122776445-66bf8480-d2ab-11eb-8325-a9d495f864e5.png "24px")
The 24px version is not pixel perfect on the left.

---

I don't know any good objective reason!

**Comment by elioqoshi** [comment]
If it's helpful, I could go over this with the Brand team over the next meeting tomorrow :)

**Comment by waynecrosby** [comment]
I have to agree with @ubuntujaggers. It's not a good pattern to follow and goes against what is now standard in the OS industry. The removal of the stem in Illustrator and Photoshop is to allow the addition of an icon when interacting with objects, which works well in an application with different menu items but is not adding anything in our OS.

Wether it looks more modern or not is a subjective opinion that should not warrant a change in the UI. The removal of the stem also opens it up to interpretation, it looks more like an arrow used in a navigation systems and becomes a bit ambiguous.

We'll discuss it with the wider team tomorrow to get a few more opinions.
