### ISSUE TITLE
Snap store Update button is indistinguishable 

### ISSUE THREAD

**Issue by thedefectiveram** [ubuntu/yaru#2933]
**Expected Behavior**

I have Sublime Text installed, and a few weeks back version 4 came out and I had noticed that mine was still on version 3 and had not self update. So I fired up Ubuntu Snap store and looked up Sublime Text. Took me a good 10 to 20 seconds and I saw that there was an Update button that would force update.

**Actual Behavior**

The Update button is grey on grey background
**Steps to Reproduce the Problem**

**Software that presents the issue**

Ubuntu Snap Store

**Yaru version**

Version: 21.04.1

**Screenshots**

![ubuntu-snap-store](https://user-images.githubusercontent.com/60362849/123511584-b43f4700-d647-11eb-8811-a86577f8d3ec.png)

**Upstream check**

**Comment by Feichtmeier** [comment]
Since we only color buttons green that use the .suggested-action styleclass they are normally colored.

I mean, agree with you - I am just not a fan of overriding stuff. I don't really know what the future of gnome software, the snap store and Ubuntu is, but eventually you could open up an issue on gitlab / gnome software. Pro tip: use Adwaita as your theme for the screenshot ;)

**Comment by Muqtxdir** [comment]
since the MR is already opened at the correct-place, closing this issue as it isn't Yaru's issue per se
