### ISSUE TITLE
Missing shadow on workspace preview

### ISSUE THREAD

**Issue by LinuxLlama** [ubuntu/yaru#2951]
**GNOME**: 40.1.0
**System**: Fedora 34 (Workstation Edition)
**Yaru**: 21.10.1-4-gb261ee3b

As the title says, there aren't any shadows on the workspace previews unlike the upstream shell theme. Is this intentional?
![Screenshot from 2021-07-13 11-31-58](https://user-images.githubusercontent.com/29968331/125506682-104de19d-7dd4-4559-8bce-4be5d0f55237.png)

**Comment by Jupi007** [comment]
Thanks for the report @LinuxLlama 👍

> As the title says, there aren't any shadows on the workspace previews unlike the upstream shell theme. Is this intentional?

Nope, this isn't intentional at all.

The weirdest things is that we have the `box-shadow` property (and it is exactly the same as upstream):

https://github.com/ubuntu/yaru/blob/b261ee3be3b61d127db1e6d5d09a46ec6fd4a25a/gnome-shell/src/gnome-shell-sass/widgets/_window-picker.scss#L48-L52

Honestly, I don't understand at all what's happening here 🤔

**Comment by Jupi007** [comment]
I receive an update of GS, and the shadow is come back by itself:

![Capture d’écran de 2021-07-16 13-17-40](https://user-images.githubusercontent.com/36476595/125939999-e0346cc0-343e-42f2-9e72-c0ff2eaf43b6.png)

Looks resolved so.
