### ISSUE TITLE
Work with us at Pop!_OS to theme libadwaita

### ISSUE THREAD

**Issue by jackpot51** [ubuntu/yaru#2999]
As many of you know, libadwaita is now hardcoding a stylesheet. In the interest of both Pop!\_OS and Ubuntu being able to ship libadwaita applications with our own themes, I want to work with the Yaru developers to enumerate the changes we make to the Adwaita stylesheet, and request that they are included in libadwaita.

In the meantime, I have opened this issue which, when implemented, will allow libadwaita applications to opt-in to using the default theme. It is expected GNOME core applications (the ones we ship by default) will use this switch:

https://gitlab.gnome.org/GNOME/libadwaita/-/issues/259

If you are interested in theming libadwaita, please send me an email at jeremy at system76 dot com

**Comment by Feichtmeier** [comment]
Hi @jackpot51 👋 

Awesome idea! 👍 

Yaru includes a stylesheet for libadwaita. A github action pulls all changes from their repo. We then curate the changes needed to keep the yaru style (mainly colors in gtk4/libdwaita).

I am currently a little bit unplugged from open source due to IRL stuff (bough a house -.-) but I am slowly recharging my batteries for open source trouble.

In the meantime I am sure @Muqtxdir and @Jupi007 can communicate with you for work to be done!
Thanks for contacting us

**Comment by jackpot51** [comment]
Thanks for the overview! Our process is the same, but actually uses Yaru as the base. I'm just getting off work, but hopefully tomorrow we can come up with some more. In the meantime, I have implemented a way for libadwaita applications to opt-in to the system GTK theme: https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/232

**Comment by jackpot51** [comment]
@Feichtmeier @Muqtxdir could one or both of you please comment on my comment here?

https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/232#note_1262813

> Yes, I will have someone from Ubuntu or Yaru comfirm they want to be ably to apply the Yaru theme to GNOME core applications

**Comment by Feichtmeier** [comment]
Done :)

**Comment by jackpot51** [comment]
Thanks!

**Comment by ItzSwirlz** [comment]
Hello everyone. Just me popping in.. as a cinnamon person confused by this mess. I'm sorry about all this mayhem @jackpot51 . Exactly what apps are we trying to theme/'untheme' here?

**Comment by Muqtxdir** [comment]
Hi @jackpot51 

since the option to swap style-sheets is something that libadwaita won't allow to do, for the `prefer-dark` functionality to work properly without any hassles.  Even though both yaru and pop themes are relatively closer to upstream Adwaita with minor-changes, the newer relatively safer approach based on the discussion we had with libadwaita folks is to just make the Libadwaita's style-sheet be recolored from the vendor palettes. This idea is still WIP and can be tracked in this MR: [!369](https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/369)

Thanks again for everyone involved in this issue!

**Comment by jackpot51** [comment]
Have fun
