### ISSUE TITLE
Change color for selected text

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#307]
The selected text color is current orange. When selecting a lot of text, the current orange is really overwhelming. Lowering the opacity never looks good with orange, so [this light blue from Unity8](https://mir-s3-cdn-cf.behance.net/project_modules/1400/79cff89167887.58df91ab0e4e7.jpg) might be a good solution. I can't find it in the documentation, but here it looks like **#d2effd**

![image](https://user-images.githubusercontent.com/3986894/38198304-844006b0-368c-11e8-98f5-36fd734e72ec.png)

TODO
- [ ]  Adapt LibreOffice text selection to madsblue -> actually open a ticket on Libreoffice about this
- [x] Adapt Firefox text selection to madsblue (in progress)

**Comment by Feichtmeier** [comment]
![screenshot from 2018-04-03 11-53-33](https://user-images.githubusercontent.com/15329494/38242748-e022cc0c-3735-11e8-97d2-2040c17522c2.png)
This could be a solution to GtkTextView but I feel that this is not the right implementation! Also firefox is not affected by this but chrome is :)

`.view,
textview {
  text {
    @extend %view;

    selection { background-color: #d2effd;
      /*&:focus, & { @extend %selected_items; }*/}
  }
}`

**Comment by madsrh** [comment]
My only concern is that this might feel out of place in the theme (if you know what I mean), but that is hard to tell from a screenshot. This looks good to me 👍Can't wait to try it in the real.

@godlyranchdressing or @nana-4 will know how to fix this in Firefox (no pressure :stuck_out_tongue_winking_eye:)

**Comment by Feichtmeier** [comment]
I guess it would be better to not "hardcode" the color code into this class and rather add some color in the colors file. 
Adtionally, I commented the annotation to extend from selected items.

**Comment by clobrano** [comment]
Agree, we can create a text_selection variable in colors.scss.

**Comment by godlyranchdressing** [comment]
Instead of using a hardcoded color I just transparentized the blue in this example:
`$selection_color: transparentize($blue, 0.75);`

![test](https://user-images.githubusercontent.com/27529229/38278046-808cd4ee-3768-11e8-9ac8-43a23e170638.png)

I think instead of putting the usual `background-color: $selection_color; &:backdrop` etc, we could follow the `%selected_items` placeholder and make a `%selected_text` placeholder with the appropriate changes, then just use that wherever we need to. That way we won't have to go about changing multiple lines if we need to make a change.

**Comment by nana-4** [comment]
@godlyranchdressing Using transparentized color looks good idea. However, as shown in the screenshot, for some reason some selected text color (in the screenshot, top and bottom lines) gets darker than others. Maybe `mix($blue, $base_color, 25%)` is better to avoid the bug.

**Comment by clobrano** [comment]
Can we merge the branch about this? If there's something left to be checked, we can open a new ticket later

**Comment by NusiNusi** [comment]
Selected text is on libreoffice still orange.

**Comment by Feichtmeier** [comment]
Open a new ticket pease @NusiNusi 
I'm getting lost already

**Comment by NusiNusi** [comment]
I can do that but i am wrong here? This ticket is already for selected text color.

**Comment by Feichtmeier** [comment]
Never mind, thought this is a PR -.-
too much emails

**Comment by godlyranchdressing** [comment]
Should we use a different shade of orange as discussed in #289 or stick to the blue? Right now selected text if it isn't in an entry field (which has an orange highlight):
![entry](https://user-images.githubusercontent.com/27529229/38680973-946200e2-3e35-11e8-9588-141b97d8426a.png)

![image](https://user-images.githubusercontent.com/27529229/38680984-9d632f18-3e35-11e8-9ad7-1bfb9c19f7f3.png)

Entry with lighter orange:

![entry2](https://user-images.githubusercontent.com/27529229/38681072-e2991728-3e35-11e8-9502-251d94fd3db8.png)

**Comment by NusiNusi** [comment]
@godlyranchdressing The lighter orange looks more like salmon. At least on my display. Or a soft pink. I do not recognize orange at all. Pretty sure this depends on the display used. Had the same problem before it was changed to blue. Only on libreoffice it looks orange.

**Comment by madsrh** [comment]
@godlyranchdressing Orange and blue isn't the perfect solution, but I really like the blue inside Gedit, Firefox,...

A less "clashing" color might be gray. We're already using gray for hovering.

![image](https://user-images.githubusercontent.com/3986894/38708202-5fccf046-3eb5-11e8-811e-8f67a40683e3.png)

**Comment by NusiNusi** [comment]
I like the gray but couldn't it be too much gray?

**Comment by Feichtmeier** [comment]
Grey text looks inactive to me.
I would totally go with the current blue
Looks fresh and does but draw too much attention

**Comment by godlyranchdressing** [comment]
I don't think it's too much gray but the gray does look a little strange. We could just remove the orange glow altogether and change the caret color to blue when the entry field is active. 

![entry](https://user-images.githubusercontent.com/27529229/38896756-9ee893c0-4261-11e8-844c-e99f4af09da3.gif)

**Comment by NusiNusi** [comment]
The state so far:

selection-color in PDFs:
![bildschirmfoto von 2018-04-22 21-46-35](https://user-images.githubusercontent.com/36449926/39099441-9e4a04c6-467b-11e8-9f0f-18d0bbc8cf9e.png)

selection-color in gedit:
![bildschirmfoto von 2018-04-22 21-47-30](https://user-images.githubusercontent.com/36449926/39099445-a9a71020-467b-11e8-95a5-6bce2a3c6afe.png)

selection-color in nautilus:
![bildschirmfoto von 2018-04-22 22-01-18](https://user-images.githubusercontent.com/36449926/39099474-fde04d46-467b-11e8-8ddf-64c987df2afb.png)

selection-color in libreoffice:
![bildschirmfoto von 2018-04-22 21-47-57](https://user-images.githubusercontent.com/36449926/39099494-514a0bd4-467c-11e8-8edc-6a44e013d1ad.png)

selection-color in firefox:
![bildschirmfoto von 2018-04-22 22-02-12](https://user-images.githubusercontent.com/36449926/39099503-6bef972e-467c-11e8-86e0-b1df2a444141.png)

I am pretty sure you will agree when i say: at the moment there is no consistency.

How about giving the use of the selection-color a system, some kind of logic:
**Unity8-blue for selected content** (all kind of texts in office or the browser, files in nautilus etc.)
**Orange for selected parts/elements of the system** (nautilus-sidebar, stackswitcher, shell-topbar etc.)
Is this even possible?

**Comment by madsrh** [comment]
I don't think that you can compare selecting files in Nautilus with selecting text in a texteditor @NusiNusi - they are two different things IMO.

The other inconsistencies I'll let @clobrano and @godlyranchdressing comment on, but isn't issue here that #95420 is the fallback selection color?

**Comment by clobrano** [comment]
I agree that we should talk about "text" selection here, that is not labels.
So, only pdf and libreoffice are a problem of consistency to me

**Comment by NusiNusi** [comment]
yes, they are two different things but have one thing in common: they are content. But try it with text only.

**Comment by clobrano** [comment]
How do you define content?

**Comment by Feichtmeier** [comment]
Hmmm, not only because of a consistency (because consistency is only applicable to things which fit together) problem but because the orange under orange is indeed quiet glowy I like @madsrh idea of light blue text selection everywhere it could be applied. Even on the selected labels under the folders. But maybe we should increase the blue in to be more intense then. Comparable to @NusiNusi 's issue with glowing orange I need to "abuse" my father again as an example of people who have rather problems with very light colors. I think some people might consider the light blue as too light for the folder selection.

**Comment by NusiNusi** [comment]
@clobrano Maybe i am not right, but i think content means everything that is not the system itself. Imagine your apartment is the system. That means the walls, the windows, the doors. Your furniture would be the content. You can change it, remove it and it is inside of your apartment. Not sure if i could make myself clear. For me it seems logic but i lack the right vocabulary to explain what i mean.
This is a technical question: isn't it more difficult to make **only** the text-selection blue? If so wouldn't it be a good reason to make all selection of content blue? I know this ticket is only for text-selection but this option should be thought about. If it is not complicated at all to change the text-selection-color we can talk about this another time. 
I think @Feichtmeier idea making the blue more intense + using it even for files selection would be great. Maybe he can show us some screenshots after his "test" with his father ;)

**Comment by clobrano** [comment]
> I know this ticket is only for text-selection but this option should be thought about

We are thinking about it. I agree with @madsrh, orange and this light blue do not fit together, even making the blue more intense. It just make everything too heavy to me. Not even considering that at some point, a dark blue would require the selected text to be white, or it becomes invisible

**Comment by godlyranchdressing** [comment]
>Unity8-blue for selected content (all kind of texts in office or the browser, files in nautilus etc.)
Orange for selected parts/elements of the system (nautilus-sidebar, stackswitcher, shell-topbar etc.)
Is this even possible?

@NusiNusi yeah that's possible. I actually came here to post about testing the theme with those changes for a bit.

![a](https://user-images.githubusercontent.com/27529229/39134864-a500b32c-46e5-11e8-8987-3340c4fadb35.png)
![c](https://user-images.githubusercontent.com/27529229/39134861-a4b10746-46e5-11e8-91d8-a9b70ba4f3cc.png)
![b](https://user-images.githubusercontent.com/27529229/39134863-a4e222cc-46e5-11e8-8d6f-190968999b39.png)

I'm not sure about using blue for selected treeview elements (Begga in the second screenshot) but I decided to put it there just for feedback. I think with so much orange removed we should be okay bringing back the orange bar and orange close button :wink:

**Comment by madsrh** [comment]
Great work @godlyranchdressing 
I'm on my phone at the moment, but I had something else in mind for the folders/nautilus - I'll post something later 😀

**Comment by Feichtmeier** [comment]
Uhh, this is how nautilus selection looks on my machine after latest merge:

![image](https://user-images.githubusercontent.com/15329494/39137603-5098c4da-471e-11e8-8549-156325ecd107.png)

**Comment by NusiNusi** [comment]
Same problem here.

**Comment by Feichtmeier** [comment]
@godlyranchdressing there are several problems now
- nautilus label selection has the wrong text and background color
- several elements are now affected which we didn't discuss, like the gtkiconview in the setting app background selection dialog
@madsrh to what extend do you want the blue selection? There are many things you can select in gtk

**Comment by Luxamman** [comment]
Yes it is very mixed up at the moment, I also like the light blue, but it seems to be too light/transparent (hardly visible in the wallpaper selection window). 

Overall I think this is also something that we are used to (the orange selection) but again it would be nicer to have on color for everything. But even Win10 uses different shades of blue for files / text selection, maybe also because the color is not working everywhere. 

Like posted before, a (theoretical, complimentary) good start point for a blue should be #1C6595 and lighter steps in #37759D and #5A92B6. This should harmonize with the orange, but maybe is not working in every circumstance either. 

I could imagine (shades of) blue for every selection or blue for text and orange for files only. Definitely, it should look a little different (lighter?) than the blue we use for volume and so on, which is again not easy...

**Comment by Luxamman** [comment]
@Feichtmeier - that looks aggressive^^ 
If it is possible, maybe the same selection like in Files (Bookmarked folders on the left), a orange border on the left and maybe a light grey? 
Or is this just adapting the selection color on the whole selected element?

**Comment by Luxamman** [comment]
Copytext from 363:
If we like to go for the blue selection, we should go for the blue selection.
Also like said before, I would still like the blue to be more saturated because the contrast to white is sometimes not big enough (will make problems on cheaper displays, sunlight and so on).

**Comment by Feichtmeier** [comment]
So we changed it to light orange for now:

![image](https://user-images.githubusercontent.com/15329494/39463956-367f6704-4d1b-11e8-957d-114112d16036.png)

The contrast is missing a bit if we keep this.
Just tagging you again into this correct issue here (since we talked about this in the weirdest places):
@madsrh @godlyranchdressing

**Comment by madsrh** [comment]
> This back and forth has been going on for too long though. It's Ubuntu, it's orange. At this point I say we rollback using blue for selected text as it's only since then that the use of blue has started to seem incoherent

One week later: Do you still feel this way @godlyranchdressing ? Returning to orange, I actually don't have that "coming home" feeling I was expecting.
What do you (everyone) think about the suggestion to return to blue (slightly dark) for editable text (as @clobrano calls it) only? No sidebars, treeviews, icons, [selections](https://user-images.githubusercontent.com/15329494/39197158-1eae6bca-47e4-11e8-8289-9b4318af5144.png), etc...
This means we would keep blue for: 

- sliders
- spinners
- text links
- selection text (like Gedit, Firefox, ...)

**Comment by clobrano** [comment]
> What do you (everyone) think about the suggestion to return to blue (slightly dark) for editable text (as @clobrano calls it) only?

+1

**Comment by godlyranchdressing** [comment]
@madsrh we can try again, but use more blue. My two main issues are that the distinction between where the blue is used and where it isn't, won't be immediately obvious to an everyday user, especially with widgets like the treeview (one of the places I think we should try using blue). Then there's the entry fields using orange instead of something more "color agnostic" to show focus while highlighted text inside the entry field uses blue. 

But then when we use more blue, won't the orange start to seem as it's being overridden? We DO have enough time to fine-tune the colors though, so we can just make a PR and work through the issues as we are with the light Shell dialogs. 

Maybe we can take a look at Pop and see how and where they use their two highlight colors before we try anything?

**Comment by ya-d** [comment]
> Maybe we can take a look at Pop and see how and where they use their two highlight colors before we try anything?

They originally laid out use of color in ["Making Ubuntu Pop"](http://blog.system76.com/post/160209210968/making-ubuntu-pop), but the theme has gone through [several](http://blog.system76.com/post/163797553013/popos-weekly-update-new-ux-architect) [revisions](http://blog.system76.com/post/168696685638/popos-update-v3-of-pop-theme-released-and) since than.

**Comment by madsrh** [comment]
# Okay! Here we go again 😃 

_Short version_: Can we try #**dd501e**? 🎨 

I'm not satisfied with the current color. I would almost prefer the full orange (#95420), but it's really hard on the eyes 👀 because it's so bright. Here's a description for my suggestion/testing list:

* I think #d74d1d is the full orange darkened 8% - it appears slightly brown which looks weird when there's a orange next to it.
* I would like to suggest **#dd501e**! This is the full orange darkened 5%, it's not as hard on the eyes, but still hard to tell apart from the full orange
* E95420 full orange - well...
* #2ab7eb is the slider color
* #c4e4f0 is (close to)[ the old highlight](https://github.com/ubuntu/gtk-communitheme/issues/307#issuecomment-386251056)
* #355280 is another one that feel good on the eyes, but again looks like we've had an accident with the color palette 🙄 This is from the NEW Unity8 color palette (the Google docs).
* #2292bc 🤷‍♂️ 

![untitled-1](https://user-images.githubusercontent.com/3986894/39865628-b9937b88-544d-11e8-81a1-3286fc24c4a3.png)

**Comment by Feichtmeier** [comment]
@madsrh thanks for this nice color overview. The darker orange could work. 
#2ab7eb looks also very nice with a white text-color but yes the backlash for "blue" could be yet great again :|

**Comment by Feichtmeier** [comment]
![screenshot from 2018-05-11 16-29-34](https://user-images.githubusercontent.com/15329494/39929509-8aacbeec-5538-11e8-8ef3-80d91e1d3473.png)
![screenshot from 2018-05-11 16-28-37](https://user-images.githubusercontent.com/15329494/39929510-8b1f8c60-5538-11e8-86e8-fd796b2ce94a.png)
![screenshot from 2018-05-11 16-27-12](https://user-images.githubusercontent.com/15329494/39929513-8c4a9652-5538-11e8-8656-98fa51bace7c.png)
![screenshot from 2018-05-11 16-26-47](https://user-images.githubusercontent.com/15329494/39929514-8c6eb97e-5538-11e8-976b-dc6c02b24543.png)
![screenshot from 2018-05-11 16-26-24](https://user-images.githubusercontent.com/15329494/39929516-8c8d8430-5538-11e8-96ac-01c3cfed47b6.png)

@madsrh since no-one else answered yet, what about purple, regular blue or inkstone? ;D

**Comment by clobrano** [comment]
> EDIT: I've checked the contrast ratio and not many of these pass the test disappointed

which ones pass it?

**Comment by Feichtmeier** [comment]
That light blue looks great

**Comment by madsrh** [comment]
> #dd501e (it doesn't seem to change much, IMHO)

No, it's very subtle, but it's not as shiny/bright as e95420 and it's not as brown looking as d74d1d

> which ones pass it?

@clobrano Actually, the light blue you liked c4e4f0 but we're going in circles because it's the one we had earlier 😆 

The light blue is good, but do we agree that it's only for text? @godlyranchdressing [do you still want blue for treeview too](https://github.com/ubuntu/gtk-communitheme/issues/307#issuecomment-383608720), because IMHO I think we can have both - orange for treeview and blue for text.
But we will still have this:

![image](https://user-images.githubusercontent.com/3986894/39940875-06cd16bc-555b-11e8-86dd-f45ff096707d.png)

**Comment by Feichtmeier** [comment]
Yes we would run in circles but imho this would be the best solution: light blue for text selection, orange for row selection! And then don't get sidetracked because there is no consistency needed between a selection of a control element and the selection/highlight of text! :peace_symbol:

**Comment by clobrano** [comment]
I've totally fogot this, sorry. I'll try to have a PR for this week

**Comment by Feichtmeier** [comment]
@clobrano  I don't know if I find time for this today so if you want you can do it.  And don't panic about firefox we can ignorethat because I opened a firefox bug for this

**Comment by clobrano** [comment]
Sorry, I took for granted the simpler rule "editable text" :)

**Comment by Feichtmeier** [comment]
Nothing to be sorry about this is really confusing

**Comment by madsrh** [comment]
@clobrano @Feichtmeier @godlyranchdressing 
I know that Firefox is still work in progress, but this still feels a bit odd to me, so I was just wondering if we could change the selection for GtkEntry to orange **again** and then keep blue for large selections (chrome, firefox, gedit,...)???

![image](https://user-images.githubusercontent.com/3986894/40972930-ad06b112-68c2-11e8-9253-7a05ee50b493.png)

**Comment by Feichtmeier** [comment]
The combination of the orange selection and the blue text looks indeed somehow out of place.
This topic is really one of the hardest part of the whole theming so far xD No really, it's just a hard decision.
Maybe we should check different shades of light orange again. Like the one libreoffice is hardcoding:
![image](https://user-images.githubusercontent.com/15329494/40973344-36db38a8-68c4-11e8-8620-b0cd1584bab3.png)

**Comment by madsrh** [comment]
@Feichtmeier We already have a mix atm, so I don't think bringing salmon back would help.
Besides the comboboxes in Libre is using a solid orange.

![image](https://user-images.githubusercontent.com/3986894/40996782-fb2239d0-6902-11e8-9c75-816ac8053781.png)

You don't think this would makes more sense than the current use of blue❓ 
IMHO solid orange is better than pink.

Would there actually be places where something like this mockup would happen?
![image](https://user-images.githubusercontent.com/3986894/40997153-fa6df212-6903-11e8-8c80-08c73756d342.png)

Any change you @Feichtmeier could make a PR for me and others to test this idea?

**Comment by Feichtmeier** [comment]
Sure I can!
So orange for GtkEntries and light blue for larger selections like in chrome ((( [sorry firefox!](https://community.ubuntu.com/t/firefox-theming/5920) ))) or GtkTextView ?

**Comment by clobrano** [comment]
closed by #517

**Comment by madsrh** [comment]
There's a big with some text being bold like Nana4 commented in the top of this issue (can't post a link from my phone)

**Comment by Feichtmeier** [comment]
- [ ]  Adapt LibreOffice text selection to madsblue
- [ ] Adapt Firefox text selection to madsblue (in progress)

**Comment by clobrano** [comment]
hey @Feichtmeier, do you know whether "adapt LibreOffice" is doable? Or we might try to reach them and ask?

**Comment by Feichtmeier** [comment]
I think the only way to do it is to style view blue and then unstyle it for every application where view should have an orange selection. Maybe it's better to reach out. I believe some dude here was from libre office. Can't remember his name but his avatar was a small man with a hat and sunglasses :D

**Comment by madsrh** [comment]
Could that be you @fitojb ? 😁

**Comment by charakterziffer** [comment]
I’m I the only one that thinks blue feels a little bit alien to Ubuntu? If I understand that correctly it was choosen because a lighter orange looks like salmon. Yes it does, if you just change the brightness and ignore the relationship of red and yellow. To get a lighter shade of orange you have to change the hue, too. Because the yellow gets to much lighter compared to the red if you boost the brightness or lower saturation, you have to give back some yellow and take away some red.

I’ve made an example scale. You see that not only the brightness changes but also saturation and hue. Not the mathematical way to make the orange brighter is correct but the percepted one.

![orange-getting-lighter](https://user-images.githubusercontent.com/7194876/43968896-c77ccf10-9cc8-11e8-84bb-d394d658fab0.png)

This is only an example, but maybe keeping orange as a selection colour would be considered again?

**Comment by charakterziffer** [comment]
Thank you for the link, Fechtmeier! I see that in this GTK Theme there’s also a lot of blue (in my opinion way too much for Ubuntu, if it was violet at least). But of course colours are a very opinionated topic.

I just wanted to show that lowering opacity without compensating the hue gives you a different colour, especially when the original colour is mixed from two components which differ in brightness (here: red and yellow). It’s the same with violet which becomes pinker, less with petrol which gets slightly bluer when brightening it.

**Comment by clobrano** [comment]
Thanks @charakterziffer, it would be good to actually try this orange with entries? What do you think?

**Comment by clobrano** [comment]
At the end we decided to keep current text highlight colors. Thanks anyway for the info!
