### ISSUE TITLE
vim icon request

### ISSUE THREAD

**Issue by kothekarswaraj** [ubuntu/yaru#3073]
**Icon Request**
vim package in ubuntu repo

**Steps to locate the icon**

**Software where the icon is missing**

**Screenshots**

**Comment by Muqtxdir** [comment]
Hi @kothekarswaraj 

Since Vim is not a GNOME-core application and more a third-party application that isn't even shipped by default on ubuntu-desktop. It would require an approval permission from the maintainers (_please see: [stopthemingmyapp](https://stopthemingmy.app)_). 

That being said closing this issue as the icon provided by Vim is pretty great and I don't think other icon-contributors here, have the time or motivation to re-base Vim's icon-identity to Yaru's fullcolor icon-guidelines.
