### ISSUE TITLE
Add a High Contrast variant of Yaru

### ISSUE THREAD

**Issue by Jupi007** [ubuntu/yaru#3090]
Todo list for adding a High Contrast variant of Yaru:

- [ ] Get HC files upstream with our Github Actions ;
- [ ] Add HC variant to Gtk3/4 ;
- [ ] Maybe fix HC variant of Gnome-Shell ;
- [ ] Add an icon variant for HC ;
- [ ] Adapt meson build.

Will be also required:

- [ ] Patch Gnome-Shell ;
- [ ] Patch Gnome-Control-Center accessibility page.

**Comment by Feichtmeier** [comment]
I think the current shell upstream scss is made in a way that the HC variant uses many files from the normal variant

**Comment by Jupi007** [comment]
Yes, and our one does in the same way. Imo we just need to add some HC colors.

**Comment by Muqtxdir** [comment]
@Jupi007  I think it has do with upstream just using `$variant: 'dark';` for **high_contrast** unlike yaru using `$variant: 'hc';`

**Comment by Muqtxdir** [comment]
since with #3416 other variants are being implementing, the `hc` would need to be provided for all of them. which in itself is a huge work and would require more contrast testing than regular, it's better to avoid adding `hc` for all of them and stick to GNOME's  `hc` stylesheet.

Also since libadwaita provides `hc` and `hc-dark` strictly for `hc` needs. yaru's-hc wouldn't be used at all and become unnecessary to include `hc` variants.
