### ISSUE TITLE
Added icon for swift file type

### ISSUE THREAD

**Issue by apy7hst** [ubuntu/yaru#3656]
for .swift files ( swift programming language ), the icon that appears is of c-source code ( text-x-c.svg ). To change that, I have made an icon for swift file type. Here is the icon :-

![text-x-swift](https://user-images.githubusercontent.com/101340385/177313052-df3cb037-6c81-480f-878f-5d2a6ea86423.svg)

Will this icon be given any priority? I am still researching on the mime type of swift.

**Comment by ItzSwirlz** [comment]
There is an icon process - look for the md file or whatever and then I'd open a PR but make sure of course you keep in mind symbolics and stuff.

(If using Swift I would  personally use Xcode and not Linux, but go ahead)

**Comment by Jupi007** [comment]
Hi @apy7hst and thanks :)
it looks like your SVG is broken when I open it with inkscape:

![image](https://user-images.githubusercontent.com/36476595/178537388-796fa7bb-682e-4fc6-87d1-4054d290b0aa.png)

And also before open a PR to include this new icon, you indeed have to find the correct mimetype for swift files.
But I'm afraid it doesn't exist in Ubuntu, because on my 22.04 computer, a `.swift` file comes with `text/plain` mimetype...

Ofc, if you can find it, we'll add your icon to Yaru!

**Comment by Jupi007** [comment]
Hi @apy7hst, any news on this?

**Comment by apy7hst** [comment]
Wherever I research on this, the websites say that swift mimetype is "application/octet-stream" and "text/plain" mimetype. Maybe it can exist as the icon for .m (Objective-C) or .mm (Objective-C++) for now.

**Comment by Jupi007** [comment]
> Wherever I research on this, the websites say that swift mimetype is "application/octet-stream" and "text/plain" mimetype.

**Comment by Jupi007** [comment]
> Wherever I research on this, the websites say that swift mimetype is "application/octet-stream" and "text/plain" mimetype.

Sadly, without a correct mimetype, we can't add a new icon. I'm sorry.

> Maybe it can exist as the icon for .m (Objective-C) or .mm (Objective-C++) for now.

What do you mean?

**Comment by apy7hst** [comment]
> What do you mean?

Ubuntu supports Objective-C mimetype, and swift is just the alternative of Objective-C. Since there isn't any mimetype available for swift in ubuntu (Available in MacOS however), this icon can exist for objective-c files

**Comment by Jupi007** [comment]
But isn't there a logo for Objective-C?
