### ISSUE TITLE
GDM username field not centered when disable-user-list=true

### ISSUE THREAD

**Issue by MAccadia** [ubuntu/yaru#3737]
**Expected Behavior**

GDM username field should be centered when user list is disabled.

**Actual Behavior**

GDM username field is not centered when user list is disabled.

**Steps to Reproduce the Problem**

1. Follow the [GNOME administration doc to disable GDM user list](https://help.gnome.org/admin/system-admin-guide/stable/login-userlist-disable.html.en)
2. Restart GDM

**System information**

GNOME Shell 42.4
Ubuntu 22.04.1 LTS

Also affects GDM on Ubuntu 20.04.

**Yaru version**

Package: yaru-theme-gnome-shell
Version: 22.04.4

**Screenshots**

![gdm_no_user_list_login](https://user-images.githubusercontent.com/14163894/191747539-1fde5476-74b2-40f7-9ec0-88606fa028e3.png)

**Upstream check**
Adwaita upstream theme also affected.

**Notes**
Disabling user list is a common configuration in enterprise context (eg. LDAP ; AD).

**Comment by Jupi007** [comment]
Hi  @MAccadia,
thanks a lot for the report!

Sadly, as you noticed the upstream theme (Adwaita) is also affected. As we are based on, so we can't fix this problem here.
I advice you to do the same report here: https://gitlab.gnome.org/GNOME/gnome-shell

Thanks again :)

_**Note:** I let this issue open to track the advancement of the resolution of this problem_

**Comment by MAccadia** [comment]
Sorry...
I copied this issue report upstream : https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5905

**Comment by Jupi007** [comment]
Don't be sorry :)
Thanks a lot !

**Comment by madsrh** [comment]
Thanks @MAccadia 
I'll close this issue as it is not related to this theme ☺️
