### ISSUE TITLE
Looking glass hints not readable using light theme

### ISSUE THREAD

**Issue by fthx** [ubuntu/yaru#3881]
Hi,

Here is the issue. No problem using dark theme.

![image](https://user-images.githubusercontent.com/23138504/228757098-b5d28e43-a55f-4fd1-95d5-176b429c3566.png)

**Comment by Feichtmeier** [comment]
I know it will be a hard trip but we really need to upstream the light theme
I've constantly fixed the theme in many releases to work with the light theme
I've been in this specific style class here many times before. 
@3v1n0 do you think you could upstream the light theme?

**Comment by Jupi007** [comment]
@fthx I can confirm the problem :+1: 

@Feichtmeier This will be very complicated because as you know, their design team will need to validate it.
And I don't think they will agree to maintain something they don't use just for us...
But it could be a good idea, to be honest I considered many time to open an issue there.
