### ISSUE TITLE
Ubiquity improvements

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#676]
@madsrh Mock-ups:

![eca2f44151f954f5bd43049a2291e5a3ea619191](https://user-images.githubusercontent.com/15329494/43423556-0a90a8f0-944d-11e8-935c-c6858998d5d3.jpg)

![32ecf286bea8f685eec9c9db5c153741ed12349a](https://user-images.githubusercontent.com/15329494/43423555-0a716a44-944d-11e8-8e49-238a272ab237.jpg)

![48dd7ca455e4aca9648dffd4c12d5122ee7ff0dc](https://user-images.githubusercontent.com/15329494/43423554-0a55228a-944d-11e8-867c-9320408013db.jpg)

![fefbbd5fce21f52d08a2a049d37ec9a8b3f6c8e8](https://user-images.githubusercontent.com/15329494/43423551-0a244214-944d-11e8-825d-2af7d6d9b80b.jpg)

Basic ideas:

- [ ] make the titlebar also purple
- [x] make it purple with an image or a gradient 
- [x] don't use blue progress dots, use white progress dots
- [x] use white text

____

Progress so far:

![photo_2018-07-30_18-08-14](https://user-images.githubusercontent.com/15329494/43423706-6423d180-944d-11e8-8ea2-51d76c3714e7.jpg)

![photo_2018-07-30_21-18-05](https://user-images.githubusercontent.com/15329494/43423708-643de41c-944d-11e8-9591-213d632843c1.jpg)

**Comment by didrocks** [comment]
I find the aubergine to be a little bit garish (a little bit with the new proposed gradient for gdm). Anyway to revisit with darker colors? (Maybe it's only the image rendering doing this?)

**Comment by madsrh** [comment]
> I find the aubergine to be a little bit garish...

If so @didrocks, I think it's because that a huge part of the screen is white and only a bit is purple in [the Canonical design](https://ubuntucommunity.s3-us-east-2.amazonaws.com/original/2X/b/bc413d4e059ec4804d29e7e3786f2c43c6ef8b65.jpg) (which I really like). So yes, this one might feel too garish because of that ratio 🤷‍♂️ 

> ...Anyway to revisit with darker colors?

Well, IMHO [the current](https://ubuntucommunity.s3-us-east-2.amazonaws.com/original/2X/c/cfd28166ded2d5c75fb3ca86441667dfd16e2172.png) is too dark / heavy / ?
The dark top and bottom just seems unnecessary to me - look at [PopOS](https://pop.system76.com/docs/install-pop-os/). I would like to brighten it up. Perhaps something like this:

![new_mockup](https://user-images.githubusercontent.com/3986894/43449484-d8d1c740-94b0-11e8-826a-33efd57b4495.jpg)


Or with very minimal purple:

![new_mockup2](https://user-images.githubusercontent.com/3986894/43449426-b2f261ec-94b0-11e8-9378-d655338f2060.jpg)

**Comment by Feichtmeier** [comment]
![43449426-b2f261ec-94b0-11e8-9378-d655338f2060](https://user-images.githubusercontent.com/15329494/43449858-c62d5b94-94b1-11e8-9ab5-3b6c9f1a2ce0.jpg)

This one is also a good idea (but I like the purple, too)
but from our design logic we used so far, the progress dots should not be green in the progress. Maybe when all are full.

**Comment by eaglersdeveloper** [comment]
@Feichtmeier, looks too boring.

**Comment by madsrh** [comment]
> but from our design logic we used so far, the progress dots should not be green in the progress. 

I know, I just didn't want too many colors or I cheated a bit, but you're right.

![image](https://user-images.githubusercontent.com/3986894/43451128-8878b818-94b4-11e8-9975-6dc3a84446e1.png)

**Comment by eaglersdeveloper** [comment]
Cool! But there are empty places.

![ubiquity-empty-places](https://user-images.githubusercontent.com/40228953/43457335-9700565c-94d7-11e8-92a5-df5f664b3a51.png)

**Comment by madsrh** [comment]
@eaglersdeveloper I guess something like below would be better, but I don't know if moving anything is possible just by theming alone - @Feichtmeier? 
As mentioned earlier, I deliberately didn't move anything - just working with the colors here. 

![image](https://user-images.githubusercontent.com/3986894/43457737-0d50d4d6-94c8-11e8-8e77-8b385de16446.png)

**Comment by Feichtmeier** [comment]
Depends how the code did the layout. But I think removing the lower area is not possible.

I would still go for the purple up and down. @didrocks the electron installer mock-up shows a very similar design. The screenshot with the gradient I posted was just the cheap replacement for the image Mads used in his mock-up.

**Comment by clobrano** [comment]
Probably the gradient becomes too bright in fact. What about no gradient? too dull?

**Comment by Feichtmeier** [comment]
No the gradient was just crap sorry, I didn't even upload it to the branch =]

**Comment by Feichtmeier** [comment]
@eaglersdeveloper I prefer a purple bottom =D

Fixed some dialog strangeness:
![screenshot from 2018-07-31 16-42-13](https://user-images.githubusercontent.com/15329494/43467045-257151a8-94e1-11e8-979e-30a008655a2d.png)
![screenshot from 2018-07-31 16-45-17](https://user-images.githubusercontent.com/15329494/43467046-25b16f2c-94e1-11e8-9d66-a7463d32b378.png)

**Comment by matthewpaulthomas** [comment]
👋 Hi, Ubiquity designer here. It’s great to see people interested in improving the visual design!

> I find the aubergine to be a little bit garish

> I think it's because that a huge part of the screen is white and only a bit is purple in the Canonical design

I think how much bright colors are appropriate for a UI depends on:
- how small it is (for example, [bikesheds are often colorful](http://bikeshed.com/), but skyscrapers are usually grey)
- how lighthearted the situation is, or people want it to be (for example, picnic cutlery is often colorful, dining room cutlery usually isn’t)
- how often you’ll be using it (less important than the other two, but you can get tired of garish things).

Phone apps are often brightly-colored partly to help you distinguish them (since you don’t have title bars or always-visible app switchers), and partly because they’re small, lighthearted, and used for only a few seconds. But for a desktop operating system installer, none of that applies: you can tell what app it is from the title bar, it’s much larger than a phone screen, it’s Serious Business, and you’ll be staring at it for several minutes.

> but from our design logic we used so far, the progress dots should not be green in the progress

> Cool! But there are empty places.

> I don't know if moving anything is possible just by theming alone

Those dots are not in [the design spec](https://docs.google.com/document/d/1bZ4yQIVgGaUGSYu3qiUHnQt3ieBZoqunP_DcleHCr3I/edit), and I don’t think they should exist. Regardless of how they’re colored, they look like something you have to wait for. So if you’re happy to dive into the code, I would just get rid of them.

**Comment by Feichtmeier** [comment]
![screenshot from 2018-08-01 12-24-46](https://user-images.githubusercontent.com/15329494/43652940-e9ed349a-9746-11e8-88ae-1e0ef5345228.png)

This would be the current ubiquity without style changes (apart from the dialogue fixing, which is quiet a no-brainer).

I can not say that it looks bad, since it fully consists of elements we already styled globally, but why I prefer the purple one, is that it is something special, something more than just "another dialogue". Same thing for the login screen and the boot screen. It makes somehow stands that they use purple, as we only use purple for "special" things. I would really be sad to see mads initial idea with full purple go

**Comment by matthewpaulthomas** [comment]
> I wasn't referring to phone apps in general, but specifically [this Ubuntu installer](https://www.omgubuntu.co.uk/2015/09/new-look-ubuntu-installer-coming-soon)

Ok, but that was different from Ubiquity in three important ways:

- It wasn’t actually an installer: it assumed that Ubuntu Touch was already installed on the device. This meant you would have spent much less time using it, reducing garishness. (Specifically, there was an extra “Insert SIM” step, but no “Try or Install”, “Keyboard layout”, “Updates and other software”, “Turn Off Secure Boot”, “Installation type”, “Allocate disk space”, or “Where are you?” steps. As far as I can tell, my former colleagues never spelled out what would happen to those choices.)
- It assumed that this was a single-user device (no “Who are you?” step), further shortening the time you’d use it.
- It was mocked up as a full-screen app (without a title bar), so no risk of clashing with a title bar or surrounding UI, whereas Ubiquity is deliberately not full-screen (see [discussion from 2005](https://wiki.ubuntu.com/UbuntuExpress/GnomeUserInterface?action=recall&rev=20#Discussion)).

All of those made colorfulness more reasonable.

> I understand that you don't think the [all purple idea](https://user-images.githubusercontent.com/15329494/43423551-0a244214-944d-11e8-825d-2af7d6d9b80b.jpg) is a good choice - and I agree that it's a bit too much - but what about the [less purple](https://user-images.githubusercontent.com/40228953/43459284-15bc9888-94de-11e8-9bcd-2fc6d57157e8.png) (without the dots), or [almost no purple](https://user-images.githubusercontent.com/3986894/43457834-5f4feb00-94c8-11e8-8127-218d16a05e25.png) (without the dots) or just [keep the old design](https://ubuntucommunity.s3-us-east-2.amazonaws.com/optimized/2X/0/0ca4aab848d55307b8e59fcbf010ef3ac7f9140c_1_690x523.png)?

The current design has too much black for my taste (though removing the progress indicator area would help a lot). And even if you think it’s about right, purple is brighter than black, which to me suggests there should be less of it.

But the only option that has less purple than the previous black — out of those three — just makes the headings purple, which looks a bit arbitrary.

> why I prefer the purple one, is that it is something special, something more than just "another dialogue"

That’s fair. But there are subtler ways of using purple, for example:
- only for a divider line between the heading and the contents
- [a lighter tint](https://design.ubuntu.com/brand/colour-palette/), or an origami pattern using lighter tints
- purple headings on a white background, rather than a grey background.

It would be good to get rid of the dotted pattern, too — we’ve phased out dots elsewhere since 2013 or so.

**Comment by madsrh** [comment]
> there are subtler ways of using purple, for example:  
> - only for a divider line between the heading and the contents 
> - purple headings on a white background, rather than a grey background.

I like the white background in the top here: It looks light and fresh.

![image](https://user-images.githubusercontent.com/3986894/43711552-6d170656-9973-11e8-9b1d-254cb0377a30.png)


![image](https://user-images.githubusercontent.com/3986894/43710143-165a2cf2-996f-11e8-94e0-06a0c92bca52.png)



@Feichtmeier Is there a fixed window height or can we simply cut off the bottom where the progress dots are atm and have a different height for the slideshow part? I know this will involve someone editing the code.

For all changes we **have** to keep downstream distros in mind!

![image](https://user-images.githubusercontent.com/3986894/43709745-f3c6569e-996d-11e8-8d73-c3ffcfa45f0e.png)

And then for the slideshow, use this one:

![image](https://user-images.githubusercontent.com/3986894/43709904-68cef572-996e-11e8-90ac-ae27f96223df.png)

**Comment by Feichtmeier** [comment]
Okay guys since the gradient border is not possible and the removal of the bottom section would mean that there is no progress bar when the installation starts, I'd say let's go with this one:

![image](https://user-images.githubusercontent.com/15329494/43735321-990f6d4c-99ba-11e8-9157-d14e1ca13d51.png)

@madsrh  @matthewpaulthomas everything else would mean to change the code of ubiquity and I'd say this is a bit out of this project.

**Comment by madsrh** [comment]
It's better but this one still feels too garish to me @Feichtmeier - sorry.
I tried a lot of options and IMO we should just surrender and take the easy way, which in this case is finetune the current design 😢 
We can always teamup with a Python developer for 19.04, if we want to revisit this 📅 

![image](https://user-images.githubusercontent.com/3986894/43741642-5fb2f932-99cf-11e8-9291-784997ae8245.png)

I'm still in doubt about the color of the dots. I know that blue fits with the theme, but it looks really weird here. Can we go with white? How much can we [style these progress indicators](https://cdn.dribbble.com/users/22608/screenshots/1473565/progress-bar_1x.png) besides the color?

How about [the slideshow](https://bazaar.launchpad.net/~ubiquity-slideshow/ubiquity-slideshow-ubuntu/html/files) - is Canonical planning to update that? It would need new screenshots too.

**Comment by matthewpaulthomas** [comment]
> everything else would mean to change the code of ubiquity and I'd say this is a bit out of this project.

Yes, I think most things that would improve Ubiquity’s appearance involve digging into the code. For example, the “You may wish to read the release notes” area looks, well, desolate. And it’s weird that “Back” is the same width as “Quit” (which shouldn’t even exist, anyway) rather than being the same width as “Continue”.

But is it really not possible to give the header area and footer area different styles without touching the code? (For example, purple text on white for the header, dark grey on light grey for the footer?)

> How about the slideshow - is Canonical planning to update that? It would need new screenshots too.

That is certainly something anyone could contribute, without being a Python programmer — [they’re just Gimp files](https://bazaar.launchpad.net/~ubiquity-slideshow/ubiquity-slideshow-ubuntu/html/files/head:/images-source/ubuntu/).

**Comment by Feichtmeier** [comment]
> But is it really not possible to give the header area and footer area different styles without touching the code? (For example, purple text on white for the header, dark grey on light grey for the footer?)

Totally possible. Everything that is colour is possible and a little margin here and there like I did to the dialogue.

Could you make another mock-up with color only chabges?

**Comment by Feichtmeier** [comment]
> Can we go with white? How much can we style these progress indicators besides the color?

I need to take a look but maybe they can be tweaked with border radius

**Comment by Feichtmeier** [comment]
I tried the purple fonts and the light bg:

![image](https://user-images.githubusercontent.com/15329494/43774129-6afae7a4-9a48-11e8-8e2f-559e90fb497d.png)

![image](https://user-images.githubusercontent.com/15329494/43774148-7aed30a4-9a48-11e8-85ab-b30a8aac1c29.png)

![image](https://user-images.githubusercontent.com/15329494/43774163-88ad6cc2-9a48-11e8-9a03-2c2284520f58.png)

_____

That's just too much whitespace.
And since removing the bottom  element is not a good idea as long as the last ("installing") step includes it's installing-progressbar inside that element, we could use the headerbar color for the bottom:

![image](https://user-images.githubusercontent.com/15329494/43774260-d52cb152-9a48-11e8-8cdc-e456deba5d22.png)

Or with a border:

![image](https://user-images.githubusercontent.com/15329494/43774308-f2a419b4-9a48-11e8-86b8-0361d06aabce.png)

**Comment by madsrh** [comment]
> ...we could use the headerbar color for the bottom

> ...purple headings on a white background, rather than a grey background.

![image](https://user-images.githubusercontent.com/3986894/43779170-f8758dd2-9a57-11e8-933c-f758ee125d5a.png)

**Comment by Feichtmeier** [comment]
Updated the PR with the last screenshots but without the pruple line bottom.

The white heading above the gray middle looks a bit too stripy.

**Comment by clobrano** [comment]
As written by mistake in the PR, I like purple gradient, however it might clash with usual wallpaper picture like the one below

![image](https://user-images.githubusercontent.com/2883614/43795044-6fc56010-9a80-11e8-9ba6-b4278d09d367.png)

**Comment by madsrh** [comment]
⚠️ very rude mockups ahead! 

Good point @clobrano 👍 

I know that we can redesign the slideshow part too, but again isn't that's out of scope? So, IMO there are some options _(that work for the full colored background and the text based wizard)_:

1. ~~White/light top and bottom~~
2. Headerbar colored top and bottom
3. Purple top and bottom
4. Dark purple top and bottom

## 1. 

When considering that wallpaper background, my [earlier favorite for the wizard part](https://user-images.githubusercontent.com/3986894/43779170-f8758dd2-9a57-11e8-933c-f758ee125d5a.png) with white header would look really bad on that slide. I think it looks disconnected somehow 🗑 

![install_white](https://user-images.githubusercontent.com/3986894/43866807-5ee03fe4-9b67-11e8-9dc8-ae788e365581.jpg)

## 2. 

Here using the headerbar color for top and bottom like we saw in @Feichtmeier [post](https://community.ubuntu.com/t/progress-on-yaru-as-default-for-cosmic-18-10/7238/17) 

![installll_headerbar-color](https://user-images.githubusercontent.com/3986894/43866763-34d82914-9b67-11e8-8e46-8245ff1fa5ba.jpg)

## 3. 

This one is like the initial mockup (yeah, the _garish_ ones 😉 ) except for the headerbar.

![installll-clashing-colors](https://user-images.githubusercontent.com/3986894/43866872-9088af68-9b67-11e8-85f2-6879b81ed4d2.jpg)



## 4.

This is almost what @Feichtmeier tried [here](https://github.com/ubuntu/yaru/issues/676#issuecomment-410814519), but this one is slightly darker. It keeps the dark top and bottom like option 2, but adds a bit of color 🎨 

![installl_darker](https://user-images.githubusercontent.com/3986894/43866599-94a3f19e-9b66-11e8-98f8-a672675ce26e.jpg)

**Comment by Feichtmeier** [comment]
Valid argument with that slide show. I vote for 2. i.e. current one BUT with the "new" transparent blue dots instead of the gray empty ones :)

**Comment by clobrano** [comment]
I agree with  @Feichtmeier, but I'd like to see how the "origami" shadows work there

**Comment by Feichtmeier** [comment]
I can push that when I revert back to black. What box shadow did you use

**Comment by madsrh** [comment]
@matthewpaulthomas 

> That is certainly something anyone could contribute, without being a Python programmer — they’re just Gimp files.

I would love to, but could you address these questions:

- How / when can I get the 18.10 wallpaper?
- Who decides or creates the text for these (or is this not something we can change because of translation e.g.)?
- Do I need to work with Launchpad to contribute 😩 ?


Thanks!

**Comment by madsrh** [comment]
@matthewpaulthomas @didrocks @8none1 

The daily build is **STILL** using the old screenshots (Ambiance theme). Is anybody at Canonical working on this? We're kind of in the dark here 🤷‍♂️ We would love to help!

![image](https://user-images.githubusercontent.com/3986894/45230501-53dd9000-b2c9-11e8-9e5c-af4bae9a4390.png)

**Comment by Feichtmeier** [comment]
Also, the icons are old. Rhythmbox has a new suru icon, libre office has new icons. And I don't know if there aren't any better apps which we could promote in that screenshots. Maybe we can also talk about this? :)

**Comment by 8none1** [comment]
The slideshow won't get updated until after UI freeze at the earliest.

If you want to make a start and capture some similar screenshots, I can put them together as soon as UI freeze is past.

**Comment by madsrh** [comment]
@8none1 Any update on this? 

I came across [this one](https://code.launchpad.net/~3v1n0/ubiquity/+git/ubiquity/+merge/354135) and was wondering if you know who this task is assigned to?

I'm happy to upload the files to Github, but Launchpad is... out of my comfort zone 😉

**Comment by 8none1** [comment]
Slideshow updates are being tracked here:  https://bugs.launchpad.net/ubuntu/+source/ubiquity-slideshow-ubuntu/+bug/1794822

(I've done the screenshots now, I just need to edit them and push a branch)

**Comment by Feichtmeier** [comment]
I think there were more improvements in mads Two ideas: light or dark
He fixed the links being orange on an orange wallpaper
+ he removed this dot grid and added those nice translucent boxes instead
Any chance to include this?
I bet mads can provide links to his work via dropbox/gdrive

**Comment by madsrh** [comment]
I've uploaded the "[light](http://madsrosendahl.dk/test_bright/)" version to [Github here](https://github.com/madsrh/ubiquity-slideshow-ubuntu). Because of the symlinks, I had to change the folder structure a bit, but you can grab the images and CSS from there.

**Comment by Feichtmeier** [comment]
Isn't this fixed? @madsrh

**Comment by madsrh** [comment]
@Feichtmeier well, sort of. The title of this issue is kind of vauge but yes, the suru icons and the CSS colors (link and header) landed. I would still like to see:

- Flash removed from _supported software_ list (doesn't make much sense in 2019)
- Background dots removed
- Screenshots with no wallpaper (window cut-out) like I did [here](http://madsrosendahl.dk/test_bright/) or [here](http://madsrosendahl.dk/test_bg/)

@8none1 What is the best way to move forward with this? A Launchpad bug + patch? 
Is this too low priority because of @didrocks work on the new installer?

I'll close this issue for now since the above changes isn't exclusively related to Yaru.

**Comment by 8none1** [comment]
Flash - yeah, makes sense to remove it.
Background dots / screenshots - we can change the style of those for disco and see how it looks.

But yeah, generally, I dont think we should invest too much time and energy in the slideshow.  That said, these changes are pretty low impact.  If you want to open a LP bug go ahead, and I will look at making these changes when I re do the slideshow for D.
