### ISSUE TITLE
Add official Dark Theme variant

### ISSUE THREAD

**Issue by jbicha** [ubuntu/yaru#732]
Please add a dark theme variant. For instance, GNOME provides _Adwaita_ and _Adwaita-dark_

It's fairly easy to add this since Yaru already supports a dark version for the apps that opt into it. But the idea here is to let people use _GNOME Tweaks_ to select the dark version for all apps.

This was requested in #653 but I'm splitting this out into a separate targeted bug.

## Specifications

- Ubuntu 18.10
- yaru-theme 18.10.2

**Comment by Feichtmeier** [comment]
Yes we need to change the meson build for this. I think @didrocks wanted to tackle this but if it's easy feel free to handle this @jbicha

**Comment by Feichtmeier** [comment]
Ah the gtk2 theme was the "blocker":
https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/1369?u=frederik-f

@paz-it didn't you somehow manage to add a dark theme for gtk2?

**Comment by Paz-it** [comment]
I have some more work to do : 
-   Assets should be recoloured - help with it will be much appreciated
.   More work tuning similarity to gtk3.
-  some fixes to the light theme.

couldn't fix LibreOffice.
qt apps show some glitches - especially with check/radio bottoms.

**Comment by jbicha** [comment]
Where would the gtk2 theme be used for LibreOffice? I thought we were gtk3 only now there.

**Comment by Feichtmeier** [comment]
Libreoffice uses gtk3

@Paz-it as you know me and @clobrano are very inexperienced with gtk2.
Apart from Qt-apps who will use the gtk2 theme soon, there are not many apps left that use gtk2. Gimp and inkscape come to my mind, and gimp uses gtk3 soon, too. But if you come up with a solution great. If you still don't feel very comfortable with git, then please open an issue and paste the code in there but please do it as structured as you can with a description on what you are doing. 

So I'd say we could fix this issue here individually with or without the gtk2 fix. I don't think that the missing gtk2 dark theme should stop us from providing the dark theme for now. Don't know what others think though. 
I think the UI-Freeze is soon, so we should really settle this one out fast.

**Comment by Paz-it** [comment]
If the gtk2 is a blocker and thinking of it as something that going to die out soon, maybe we should do something a bit different to tackle it. Since we already have Adwaita/ Adwaita-dark that are working well with all Gtk2 apps, again - MAYBE we can  default Gtk2 apps to use Adwaita theme to each variant separately. Just an idea. I'm working on it in my free time and not sure I can handle the freeze pressure.  
My mistake about the LibreOffice - I tried to see if I can fix some of it but it's NOT relevant to the discussion here.

**Comment by taciturasa** [comment]
I think the work that has gone into gtk2 support is completely adequate as it is. I think the goal should be to make it relatively fit with the system, as it is in fact legacy software. Plenty of things are moving over to gtk3 now, like gimp and electron. i don't think some minor issues like no dark them are going to be a problem; i think a easily understandable and consistent desktop would be more important for the typical end user than complete perfect support, which i'm not sure adwaita even provides anyways.

**Comment by clobrano** [comment]
I agree with @taciturasa, in any case I'm adding gtk2 label to this issue to let anyone interested in tackling gtk2 issues to have a look into this as well

**Comment by didrocks** [comment]
Here is the current state of affairs: https://community.ubuntu.com/t/yaru-dark-variant/7936/2
