### ISSUE TITLE
Google Drive Folder with Insync and task bar icons for Enpass and insync

### ISSUE THREAD

**Issue by bg15407** [ubuntu/yaru#759]
![screenshot from 2018-08-30 20-14-39](https://user-images.githubusercontent.com/24629113/44859422-ba432c80-ac91-11e8-8139-63097e254a49.png)
![screenshot from 2018-08-30 20-14-55](https://user-images.githubusercontent.com/24629113/44859424-ba432c80-ac91-11e8-8c9c-c9ffa2075961.png)

Insync (Google drive client) folder does not have a icon in this theme as well the top bar icon is kind of out of place with other icons

Enpass password manager task bar icon is also not align with the other icons.

Kindly check above issues 

Thank you

**Comment by Feichtmeier** [comment]
Hi there, I use insync myself and do not like the look of the folder, neither.

But until now we use an unmodified version of https://github.com/snwh/suru-icon-theme which explicitly excludes third party apps from providing icons due to copyright conflicts. 

Since we have some super minor issues with the upstream icon set ourselves sometimes, we could put this on a super low prio and see if our team agrees on minor modifications of the suru icon theme and put this on the list, but don't keep your hopes high. We will prbly close this due to the listed reason :)

Do not hesitate to report further issues!

**Comment by clobrano** [comment]
Being a sync folder, what about using the share folder in the meantime? I actually don't know if it's feasible, but...

**Comment by Feichtmeier** [comment]
@bg15407 could you communicate with insync if they are 100% okay if we would provide a Suru/Yaru icon for the folder? 
Before this isn't checked I can't do this.

**Comment by Feichtmeier** [comment]
Contacted insync
They are interested and wanted to see how it could look so I've sent them this one:
![image](https://user-images.githubusercontent.com/15329494/48511863-3e03c280-e858-11e8-9c4e-bdfb144bca12.png)
Waiting for their answer

**Comment by Feichtmeier** [comment]
Insync is golden with that folder we are allowed to add it :)

"Hi Frederik,

You have blessing from the team. Go ahead and change the colour of the folder to fit your theme. blush

All the best,
Nikki"

**Comment by Feichtmeier** [comment]
@snwh  are you interested in this for your upstream repo? If yes I apply the PR for you additionally (I just remember that you are not a fan of stuff like this)
