### ISSUE TITLE
Different style of similar items in different programs

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/yaru#774]
Ubuntu 18.04. Yaru from snap stable.

I've noticed there's different decoration for "tabs" in (for example) Gnome Software (top) and Calendar (bottom). Not sure if it makes sense to use different styles for what looks like similar UI element.

![tabs_example](https://user-images.githubusercontent.com/1629120/44991759-08577900-af8d-11e8-9b48-fcc5bcacca1c.png)

**Comment by Feichtmeier** [comment]
No this is a different element

It is actually the other way round: Gnome uses different UI elements for the same function.

One element is a simple GtkButtonBox and the other element which we styled with the orange underline is a GtkStackSwitcher with which you can switch between stacks.

We don't know why gnome-software still uses the buttonbox, but when we fake styled the buttonbox to match the stackswitchers it had very big negative side effects because buttonbox is used NORMALLY for other things than faking a stackswitcher.

Thus we changed it and we like the stackswitchers like they are.

But there is a big discussion about this somewhere in the closed issues please read it.

**Comment by Feichtmeier** [comment]
@mivoligo yes, that's okay. On the other side it is a bit strange to somehow fake a stackswitcher with a buttonbox because from my experiences with GTK it makes everything a lot more complicated. 
Gtk already has the stackswitcher and the stacks and you can swap the stacks around with the stackswitcher's signals (similar to what event listeners are in languages like java) but there must be a reason for not using it in gnome software so :man_shrugging: 
Yet, we didn't want to ruin our nice looking stackswitchers because they are used in many apps (todo, music, rhythmbox, calendar, clocks... basically ALL newer gnome apps)
