### ISSUE TITLE
New app grid icon (yes, again)

### ISSUE THREAD

**Issue by eaglersdeveloper** [ubuntu/yaru#796]
Already very soon to UI Freeze, the September of 13th, and we still haven't decided what the app grid icon will look like. The current icon looks boring and old-fashioned.

I suggest two options:
- White icon in the Suru style with a black pictogram.
- White round icon with a black pictogram.

**Comment by clobrano** [comment]
see also #584 
considering the function of the button, I find the current app grid fine

**Comment by eaglersdeveloper** [comment]
Tell at least what variant you like. I will try to do this as soon as possible.

@clobrano, 
> considering the function of the button, I find the current app grid fine
> The current icon looks boring and old-fashioned.

**Comment by clobrano** [comment]
It doesn't look boring to me and I already like it, this does not mean I will fight against the change ;)

**Comment by Feichtmeier** [comment]
Well it was the best we had until now. It was @tacituras himself who canceled his proposal, because he was not satisfied with his implementation (please correct me, but this is how I remember it).

It is also pretty much like minimalism, too. We could consider other shapes for the dots, but all white backgrounds looked pretty heavy to me. 

Any change to the grid should be postponed after 18.10 in my opinion, before we ship something buggy.

**Comment by taciturasa** [comment]
@snwh also clarified suru guidelines that meant we couldn't go forward with what I had. I had other ideas that didn't quite work when implemented. Perhaps Sam could do something, but I'm unsure

**Comment by snwh** [comment]
This would be a needless change and change for change's sake. "Boring and old-fashioned" means the icon works. Functional icons (which all the symbolic system icons are) are not meant to be any more exciting than text on a page and ought to convey things as simply and clearly as possible.

**Comment by Feichtmeier** [comment]
Personally I can live with the upstream icon as it is pretty neutral.
Looks like you have a lot to discuss since you three didn't didn't find a consensus.
Maybe better discuss this on the Suru repo. Closing this since we basically discussed this several times.
Was a bit wrong from my side to motivate you (though it didn't bring any progress ;))

**Comment by eaglersdeveloper** [comment]
Let's reopen this issue.

App drawer now looks outdated.
How about icon below?

![screenshot_2019-03-03-17-15-11 01](https://user-images.githubusercontent.com/40228953/53695722-8d0a3f00-3dd8-11e9-91cc-a27c2da2ca6c.png)

**Comment by eaglersdeveloper** [comment]
@Feichtmeier, @ubuntujaggers, @clobrano, @madsrh, do you like this icon? Can we replace the symbolic icon with it?

**Comment by clobrano** [comment]
I think current icon is perfectly fine

**Comment by Austinuity** [comment]
I like the idea of a circular app icon, but definitely feel that making it look like an app icon is the wrong traction
