### ISSUE TITLE
Dark theme breaks some GTK 2 apps

### ISSUE THREAD

**Issue by vitalkanev** [ubuntu/yaru#827]
## Expected Behavior

It should look like as wanted

<details><summary>Light theme screenshot</summary>

![2018-09-13 20-51-52](https://user-images.githubusercontent.com/18398761/45506071-e0d78c00-b796-11e8-9db6-b3fc7ada02fa.png)

I think padding issue is actually known
</details>

## Actual Behavior

<details><summary>Theme broken - press here for screenshot</summary>

![2018-09-13 20-50-37](https://user-images.githubusercontent.com/18398761/45505999-b259b100-b796-11e8-98fc-4bc57448b94a.png)

</details>

## Steps to Reproduce the Problem

  1. Install and open any gtk 2.0 app - *audacious* is a great example
  2. Switch to dark theme (Recommended using *Tweaks* app)

## Specifications

```sh
$ git describe
18.10.4-9-gfe6a55f4
$ lsb_release -a # Just in case
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

```

Software that presents the issue:
- Name: Audacious
- Version: 3.9

**Comment by Feichtmeier** [comment]
You have build it from source right?

**Comment by vitalkanev** [comment]
Yup четверг, 13 сентября 2018г., 21:09 +03:00 от Feichtmeier  notifications@github.com :

**Comment by Feichtmeier** [comment]
The dark gtk2 is simply not there yet =)
This is all quiet new and we didnt even announce it yet. 
That's why yaru-dark is not in the .deb theme in cosmic and not in the communitheme snap yet.

Until then meson will produce the yaru-dark but as you noticed, the dark gtk2 is not there yet =)

Thanks for reporting, closing this since it is not unexpected. Keep up reporting issues

**Comment by chrisjbillington** [comment]
I just upgraded to Ubuntu 18.10, and the option to select "yaru-dark" is there in gnome-tweaks, resulting in the above for gtk2 apps.

Is is possible to make gtk2 apps continue to use the light theme, even if the dark theme is selected in gnome-tweaks, until the gtk2 dark theme is ready? (like, just aliasing the gtk2 dark theme to point to the gtk2 light theme?) Since the option is there in gnome-tweaks in Ubuntu 18.10, people are going to use it, resulting in a few apps looking pretty ugly.

**Comment by godlyranchdressing** [comment]
@chrisjbillington You could make a symbolic link or just copy and paste the gtk-2.0 folder from regular Yaru into the dark variant's folder. The symbolic link option would be

`cd /usr/share/themes/Yaru && sudo ln -s -r gtk-2.0/ ../Yaru-dark`

Or you can pull from the PR that the dark GTK2 theme is being (actively) worked on:

https://github.com/ubuntu/yaru/pull/852#issuecomment-431132769
