### ISSUE TITLE
Nautilus notebook tabs

### ISSUE THREAD

**Issue by CDrummond** [ubuntu/yaru#829]
## Expected Behavior

Base line of tabs should extend full width of window, and there should be a gap between tabs - to be consistent with all other tabs (e.g. terminal, gedit)

## Actual Behavior

As can be seen in the screenshot the 'base line' of the tabs does not stretch fully to the left (or indeed fully to the right):

![tabline](https://user-images.githubusercontent.com/1141694/45544449-423b4180-b80f-11e8-9e6b-c1580ba8949d.png)

And, the following shows that the nautlilus tabs have no gap (the hovered tab is right next to the active tab):

![tabgap](https://user-images.githubusercontent.com/1141694/45544484-597a2f00-b80f-11e8-9227-8606301b9096.png)

## Specifications

I you installed from the sources, go the Yaru folder and copy the output of the following terminal command instead

    `$ git describe`

18.10.4-9-gfe6a55f4

**Comment by madsrh** [comment]
Thanks @CDrummond 
This was actually mentioned https://github.com/ubuntu/yaru/pull/745 but I forgot about it - sorry!

**Comment by clobrano** [comment]
This is actually easier to fix than I though. Sorry in advance for the long post, but it needs to be told :D
Initially, Nautilus had a lot of custom code for notebook and the issue above was even more visible because it was in between tabs, so I reduced the padding to zero to "mitigate it". In the latest code review, we even reduced the Nautilus custom code but the issue was apparently still there. Only now I tried to remove completely the custom code and that fixes it XD
