### ISSUE TITLE
Add Non-Symbolic Action Icons

### ISSUE THREAD

**Issue by AGitBoy** [ubuntu/yaru#831]
Many non-GNOME applications don't use the symbolic version of icons provided for actions. Unfortunately this theme only provides symbolic action icons. To increase compatibility with these applications, we would need to have non symbolic variations of our existing icons.

**Comment by Feichtmeier** [comment]
Ah, you mean like in toolbars?

**Comment by AGitBoy** [comment]
Yes.

**Comment by CDrummond** [comment]
Related to this, Qt apps are using duplicate icons for "Open", "Save", and "Revert" (possibly others too). 

I _think_ this is because Yaru has a `document` icon but no `document-save`. When Qt looks for the icon `document-save` it cant find it so looks for `document` (again, this is how I think the icon naming spec is supposed to work).

See kid3-qt:

![kid3](https://user-images.githubusercontent.com/1141694/45816880-dbb59800-bcd4-11e8-8d1d-162695de9632.png)

**Comment by AGitBoy** [comment]
I found a perfect example of this in the Additional Printer Settings dialog (GNOME Settings -> Devices -> Printers -> Additional Printer Settings...)
![symboliciconsproblem](https://user-images.githubusercontent.com/30708886/46509564-718f0e00-c811-11e8-8574-d78781505c06.png)

**Comment by Feichtmeier** [comment]
There is also an upstream issue for this
https://github.com/snwh/suru-icon-theme/issues/82
@ubuntujaggers maybe you find time to help upstream with this rather huge task :)
However would be cool if we could discuss this upstream
