### ISSUE TITLE
Update Wiki or Delete wiki?

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#841]
Update with up-to-date screenshots

**Comment by dvkndn** [comment]
Hi @Feichtmeier , can this issue be done by someone outside? I don't see the "help wanted" label here but this seems to be the most possible to me..

**Comment by Feichtmeier** [comment]
Wow! @dvkndn 
I would love help there!

Can you update the wiki with pull requests? I am note sure :thinking:

**Comment by dvkndn** [comment]
It's not really straightforward for non-member of the repo: https://gist.github.com/larrybotha/10650410. It requires more work from you than merging a code PR :(

Another solution is to have the readme/docs/wiki as source code of a website (I mean like putting it in "docs" and host it with github pages).

**Comment by clobrano** [comment]
> I think if the wiki (which is a git itself) is supposed to be changed only by 1 or 2 people then we will be fine with this. Otherwise, the manual merging process will be unnecessary complex.

This has been the current workflow indeed (and actually, most of the work has been made by just 1 person). However, this way we make very hard contributing to the documentation which is also important.

**Comment by dvkndn** [comment]
For the first approach, it looks pretty good for vscode-wiki: https://github.com/Microsoft/vscode-wiki

This means many people can contribute to the wiki (which will be hosted at https://github.com/ubuntu/yaru-wiki for example) via PRs. After a few weeks one of you guys (Yaru's team) will sync the wiki.

It seems that the syncing would not be too difficult because it's only a fast-forward pull from: `https://github.com/ubuntu/yaru-wiki.git` to `https://github.com/ubuntu/yaru.wiki.git`, while all the collaboration work happens at `yaru-wiki` only.

<hr />

In other words, the procedure should look like:

1. A member of Yaru will clone https://github.com/ubuntu/yaru.wiki.git to their local
    - This will have an `origin` remote pointed to `yaru.wiki.git`
2. Create another remote for it, let's say `public`, at https://github.com/ubuntu/yaru-wiki.git
    - The community should fork and PR to this public `yaru-wiki` repo only
    - The `master` of `yaru-wiki` should reflect the upcoming changes to `yaru.wiki`
3. Occasionally, member of Yaru should do a git pull from `yaru-wiki/master` (the `public` remote) into `yaru.wiki/master` (the `origin` remote) and push it to update the actual wiki

**Comment by Feichtmeier** [comment]
@madsrh @clobrano 
Personally I don't feel very motivated to update the wiki
Now after the refresh, is there anything needed besides our palette? Which is reviewed by @clobrano it seems https://github.com/ubuntu/yaru/issues/1522
We could also just remove it if you are not emotionally attached to it

**Comment by Feichtmeier** [comment]
Updated the Wiki:

- made it clear that it mostly refers to yaru 1.0
- linked a presentation for how we came to the Yaru 2.0 theme
