### ISSUE TITLE
Inconsistent rounded corners for file icons

### ISSUE THREAD

**Issue by matthewpaulthomas** [ubuntu/yaru#866]
yaru-theme-* 18.10.4, Ubuntu Cosmic

The generic icons for various file types have rounded corners.

![icon for text file](https://user-images.githubusercontent.com/19801137/45941961-5c77db00-bfd8-11e8-8c3e-5cfae429a66e.png) ![icon for mp3](https://user-images.githubusercontent.com/19801137/45942023-ab257500-bfd8-11e8-9570-9a85eb28077a.png)

When a file has no single visual representation, such as a sound file, a font, or a database, this doesn’t really matter one way or another. But when a file does have a well-known visual representation, such as an image, movie, or PDF, it’s inconsistent.

One example of this inconsistency is that the shape of an image icon differs depending merely on whether Files is able to show a thumbnail of it.

![icons for mona lisa image](https://user-images.githubusercontent.com/19801137/45943625-f5a9f000-bfde-11e8-854e-833aadf21e44.png)

Another example is that a LibreOffice Writer document has an icon with rounded corners, but if you save the document as a PDF, suddenly its corners become square — when really they were square all along.

![icons for test document](https://user-images.githubusercontent.com/19801137/45943665-2853e880-bfdf-11e8-92d8-ffb8e6e26002.png)

App icons in this theme have rounded corners. But that is, if anything, another reason for document icons _not_ to have rounded corners, to help distinguish between apps and documents.

[[Originally reported in the Yaru forum](https://discourse.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/1750).]

**Comment by Feichtmeier** [comment]
I really don't see where the problem is. These rounded corners are everywhere in our theme and look very sexy to me.
Thumbnails/previews of the real file like with PDF and images are just that a preview and that's why they don't have a round corner because the original neither has rounded corners

**Comment by matthewpaulthomas** [comment]
A common issue with consistency is being consistent with the wrong things. In general, it’s better to be consistent with things nearby or more closely related, than with things far away or more distantly related, because it reduces mental load.

For example, it’s more important for document icons of the same type to be consistent with each other than with other document icons. And it’s more important for document icons in general to be consistent with each other than to be consistent with app icons or other parts of the theme.

If no document icons had thumbnails, this would be less of an issue. But given that many _do_ have thumbnails (which is a good thing!), it’s better for non-thumbnail icons to be consistent in style with thumbnail icons than to be consistent with app icons.

For example, in iOS Files, document icons have very slightly rounded corners, the same radius regardless of whether they have thumbnails or not. It’s much smaller than the rounded corners for app icons.

![](https://user-images.githubusercontent.com/19801137/45947731-3c064b80-bfed-11e8-90fb-75b329312b4c.png)

Similarly in Android 7.1, [circular icons are used specifically for apps](https://developer.android.com/about/versions/nougat/android-7.1#circular-icons), not for documents.

**Comment by Feichtmeier** [comment]
I have to admit that I would really prefer the current styling :see_no_evil: 
I don't know how others feel though
@madsrh @clobrano @godlyranchdressing

**Comment by Feichtmeier** [comment]
I'd like to add something ...

The content view in nautilus shows thumbnails for PDFs, videos and pictures.
But only after a certain zoom threshold is passed. Before it has the regular mime-type icon.

Imho having a thumbnail is a valid exception for the round icons, since it is a thumbnail and you don't want it to be cut. A symbol on the other side needs brain work anyways since your brain needs to decode that symbols. :haircut_man: 

I think those different looking icon shapes of the OSX icons look far worse and chaotic. Almost like you mixed icon themes.

![peek 2018-11-07 13-03](https://user-images.githubusercontent.com/15329494/48130658-ac131d00-e28d-11e8-97da-04ea59c558a7.gif)
![peek 2018-11-07 13-02](https://user-images.githubusercontent.com/15329494/48130660-ac131d00-e28d-11e8-92d5-5e4edf5a9eb6.gif)

**Comment by clobrano** [comment]
> App icons in this theme have rounded corners. But that is, if anything, another reason for document icons not to have rounded corners, to help distinguish between apps and documents.

document icons are taller than app icons, so I don't see the problem here.

I agree on the preview file issue, I think it would be better to have the same size and format for both mime types and preview, but trying to keep the current rounded format

**Comment by madsrh** [comment]
> I think it would be better to have the same size and format for both mime types and preview, but trying to keep the current rounded format

So shrink the preview or make the mime icons larger?
 
![image](https://user-images.githubusercontent.com/3986894/48131826-b3d4c080-e291-11e8-9ad8-f9d7fe11ef08.png)

**Comment by Feichtmeier** [comment]
I agree that the thumbnails are too big, but cutting the edges might not even be possible (not with CSS I think). It also looks a bit weird to me. 
Also, I don't know if shrinking the thumbnails is possible from our side.
This is adwaita by the way:

![image](https://user-images.githubusercontent.com/15329494/48132154-d74c3b00-e292-11e8-9008-563363de3314.png)

**Comment by clobrano** [comment]
> So shrink the preview or make the mime icons larger?

yes, that would be cool

> I agree that the thumbnails are prbly too big, but cutting the edges might not even be possible (not with CSS I think).

I agree, I think it's a Nautilus thing. If so, it would be complex, since Nautilus should work accordingly to the Theme, which is not supposed to do, I believe.

A simpler solution would be to just adapt the size of the preview, instead of the full shape. It's probably a Nautilus thing as well, but easier to fix

Finally, I always though Android file managers are not good enough, compared to desktop ones, I would mind OSX better :)

**Comment by Feichtmeier** [comment]
Yeah from the upstream/downstream perspective this is not a good idea since hopefully Ubuntu uses 100% of the up-to-date gnome apps in the future without any modifications.

(I don't like that Android file manager neither, I just wanted to point out that Suru mime types are not the only ones with rounded icon backgrounds)

So what shall we do?

**Comment by clobrano** [comment]
I'll ask Nautilus team about it
