### ISSUE TITLE
Outline color for green and red buttons could be white

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#880]
![image](https://user-images.githubusercontent.com/15329494/46260314-8ce1dc80-c4e4-11e8-8387-b81fc00f2a98.png)
![image](https://user-images.githubusercontent.com/15329494/46260336-d8948600-c4e4-11e8-80e5-dba8fd32738e.png)

Something like this

![image](https://user-images.githubusercontent.com/15329494/46260326-b4d14000-c4e4-11e8-960b-a770931176d5.png)

**Comment by madsrh** [comment]
@Feichtmeier Do you think there is time to fix this and push a freeze exception?

Can the same be applied here:
![image](https://user-images.githubusercontent.com/3986894/46507580-7bc50280-c839-11e8-8102-06a312dea57d.png)

**Comment by Feichtmeier** [comment]
I have time for sure. 
I am still confused by these UIFe
I thought we passed this UIFe deadline last Monday? 
@didrocks please enlighten me and sorry for being slow again

**Comment by didrocks** [comment]
UIF is passed for a long time already, have a look at the calender (that I linked many times btw…): https://wiki.ubuntu.com/CosmicCuttlefish/ReleaseSchedule.
We requested for an UIFe (https://wiki.ubuntu.com/FreezeExceptionProcess#UserInterfaceFreeze_Exceptions), which is a one time grand to "break" the exception (read the wiki page again that I linked: https://wiki.ubuntu.com/UserInterfaceFreeze).

We did the upload corresponding with the UIFe content last Monday, before beta. I hope this time, I won't get asked once more what the UIF process is TBH, I'm under the impression to have linked those pages a lot of times and they weren't read, hence your confusion. :/

However, we can still do some small uploads with fixes until Final Freeze (see the release schedule). I think we should aim making a final Yaru upload next Wednesday, just before Final Freeze. Those uploads (since FF and UIF) are for bug fixes only (and so, very minor changes, which won't really impact documentation). I suggest this particular fix is one of those and can be merged thus, without an UIFe.

**Comment by Feichtmeier** [comment]
I did read it but why does it need less hassle to merge AFTER a freeze point than before? This just doesn't make sense to me.

Pre freeze date xyz:
Merge what you like
Post freeze date xzy:
Make request with a big why report
Two weeks later:
Merge without the report again

???

**Comment by madsrh** [comment]
Because this is considered a bug fix

**Comment by didrocks** [comment]
No, you didn't understand me :/

```
Pre freeze date xyz:
Merge what you like
```
The above is correct ^

```
Post freeze date xzy:
* Make request with a big why report *if there a noticeable UI change* (see the wiki page on what qualifies as an UIF breakage)
* For fixes (changes we can't really notice if I give you 2 screenshots), merge as before
```
And we are here, and that PR is considered as a fix.

**Comment by didrocks** [comment]
Thanks @madsrh! I'm not as unclear thus ;)

**Comment by Feichtmeier** [comment]
Well in my "other" job we have those freeze points too.

But even a bug fix needs these big talks.

**Comment by didrocks** [comment]
Not in ubuntu until Final Freeze, where yes, every uploads needs to be lenghtly discussed.

**Comment by Feichtmeier** [comment]
Aha ok
Then I PR this later

**Comment by didrocks** [comment]
Thanks!

**Comment by Feichtmeier** [comment]
Yoyo

**Comment by Feichtmeier** [comment]
It's still unlogical. 
An icon can do literally nothing to the stability of your software.
In opposite of CSS code.
But hey, we only want the best for Yaru right? Thus I follow your orders :thinking:

**Comment by didrocks** [comment]
@Feichtmeier: on your comment you removed about this being unlogical versus code safety.

We are not talking about crashers, here, but taking again definition of https://wiki.ubuntu.com/UserInterfaceFreeze:
> The user interface must be stabilized at some point, so that documentation writers and translators can work on a fixed target that doesn't obsolete screenshots or documentation.

-> It's about what can you notice in the documentation or screenshot that changes? The icon to start an application can be confused versus documentation. A simple "highlight" selector is not that noticeable.

**Comment by didrocks** [comment]
Seems there is a build failure due to gtk-common-themes, looking at it…

**Comment by didrocks** [comment]
@Feichtmeier Ok, it worked, please merge your branch with master to get the fix, then, it should pass again (apart if we get other snaprevs udpate fails).
