### ISSUE TITLE
Settings icon in status menu is different in cosmic

### ISSUE THREAD

**Issue by Eskander** [ubuntu/yaru#894]
This is the settings button from the status menu in Ubuntu Cosmic beta:

![222](https://user-images.githubusercontent.com/11521400/46545371-19faac00-c8be-11e8-9389-2f7f19f511b5.png)

and this is it when using the snap:

![screenshot-shell](https://user-images.githubusercontent.com/11521400/46545372-1a934280-c8be-11e8-94f1-6a4fc48bbae3.jpg)

is this intentional?

**Comment by eskander** [comment]
'Yaru' is set as icon theme, the deb version is 18.10.5

**Comment by Feichtmeier** [comment]
@eskander thanks for the info!

@madsrh can you confirm this on your cosmic daily installation(s)?

**Comment by madsrh** [comment]
Sadly, yes

**Comment by Feichtmeier** [comment]
That's very strange! I guess the icon name changed in upstream shell? :thinking:

**Comment by madsrh** [comment]
@clobrano Do you have any idea what's going on here?

I also discovered this when hovering over the menu:
![untitled-1](https://user-images.githubusercontent.com/3986894/46634781-4b8ba580-cb52-11e8-9320-f5a0f8c6b8fb.gif)

**Comment by clobrano** [comment]
@madsrh I cannot reproduce the volume icon issue, but it's something I saw from time to time also years ago. No clue what the reason is

**Comment by Paz-it** [comment]
@madsrh ..I have the some issue suddenly with the volume icon but in bionic..

**Comment by Feichtmeier** [comment]
I installed https://github.com/keeferrourke/la-capitaine-icon-theme

As you can see here is that the icon is somehow hardcoded, since it does not change when selecting la capitaine, unlike the other icons in the popup;
![image](https://user-images.githubusercontent.com/15329494/48555298-199ff880-e8e1-11e8-94d7-f2734ae4f2fc.png)

I guess this is yet again something for upstream or maybe it is ubuntu only? Then it would be something for launchpad =)

**Comment by clobrano** [comment]
Maybe it's just different the icon-name
