### ISSUE TITLE
Gtk2 treeview, header and scrollbar double lines 

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/yaru#908]
Good but half solution .  When you look at the top headerbar double-line is drown -one for header and one for the window frame. on the right top side, the last separator is just there hanging and the top line above the scrollbar is thinner . that way it looks unfinished imo.
![drawisland](https://user-images.githubusercontent.com/37431503/46287419-21067f00-c58b-11e8-87de-2cf57d720e5a.png)
Another thing I think did is to remove the handle line the is way too much here, imo again :smile: 
![drawisland-1](https://user-images.githubusercontent.com/37431503/46288260-d3d7dc80-c58d-11e8-81ae-38a70304100b.png)

I did it by going into the main.rc file and changed the value from 9 to 2. 
 GtkPaned::handle-size = 2
  GtkHPaned::handle-size = 2
  GtkVPaned::handle-size = 2

_Originally posted by @Paz-it in https://github.com/ubuntu/yaru/pull/878#issuecomment-425882843_

**Comment by clobrano** [comment]
@Paz-it sorry, I edited the title to make it more informative.

About the issue, gtk2 is not adaptive like gtk3, so the scrollbar space cannot disappear when it is not necessary, so that space (and lines) will always been drawn, if we keep it, or won't ever be visible (even when necessary) if we remove it

**Comment by Paz-it** [comment]
@clobrano , We probably misunderstand each other...
Picture better then words :smile: 
![screenshot from 2018-10-11 21-30-35](https://user-images.githubusercontent.com/37431503/46825816-26d73e00-cd9d-11e8-9c17-3fc12cc8d1d4.png)

**Comment by clobrano** [comment]
Oh, I understand now, however, I don't think it's a good idea: scrollbar seems disconnected from the view and missing the frame

**Comment by Paz-it** [comment]
OK, @clobrano, Does it look better now? 
![screenshot from 2018-10-12 20-00-28](https://user-images.githubusercontent.com/37431503/46883175-e1c51180-ce59-11e8-883c-b6fcf4845fc6.png)

**Comment by clobrano** [comment]
The target is always to look as similar as possible to GTK3

![image](https://user-images.githubusercontent.com/2883614/46888471-e214db00-ce60-11e8-8aa6-004f9ac746db.png)

so to be honest, even the thin line I kept is not really conform, however, in some cases the scrollbar is actually outside the treeview and a border is needed

**Comment by Paz-it** [comment]
Each scrolled window have a border around it and the scrollbar is within that border, not outside of it. I did not change your file. the thin left border of the scrollbar is still present. The change is that in GTK-3 the scrollbar is not always present. We can not change that, unfortunately :( 
Maybe you can see it better in this larger image with a bit dark background: 
![screenshot from 2018-10-12 23-55-40](https://user-images.githubusercontent.com/37431503/46894028-a63b3f00-ce7b-11e8-9ffd-14318b421fa5.png)
There is no way to make exactly the same as gtk3 but at least we can try to make it cleaner as we can and almost more or less the same.

**Comment by clobrano** [comment]
> almost more or less the same.

Yes, that's why I think the thick grey line between treeview and the scrollbar doesn't work. There should be no line at all

**Comment by Paz-it** [comment]
Not sure I understand which thick grey line you refer to.. :confused: :question: 

I tried my best so far : 
If you see The current muster 
![current master](https://user-images.githubusercontent.com/37431503/46910169-90e01680-cf48-11e8-8b32-f6b1c85f9e51.png)
Compared with my configs 
![aftermyconfig](https://user-images.githubusercontent.com/37431503/46910182-d13f9480-cf48-11e8-96ec-5af1ce5154fd.png)
I think it is, at least look better. in my  humble opinion (I must add o.c)

**Comment by clobrano** [comment]
> Not sure I understand which thick grey line you refer to..

the one on the left of the scrollbar

![image](https://user-images.githubusercontent.com/2883614/46914897-2d83d200-cfa4-11e8-830f-79bb5552668c.png)

to make it more like gtk3, that line shouldn't exist at all, I think

One more thing, when taking screenshot of the result, could you not select the first row of files? The orange selection prevent to see how treeview header is :smile: 

e.g. in the picture above, instead of selecting `.cache` select `.compiz` or something below

**Comment by Paz-it** [comment]
Ha ha! - I see what you mean now :smile: 
The all scrolled windows & scrollbars are a bit tricky. they al not all the some. first it is per application and second it's even different at the same application. Some are three-view scrolling windows the others are just scrolling windows. 
some examples : 
Gpick
![screenshot from 2018-10-14 15-19-27](https://user-images.githubusercontent.com/37431503/46916866-2c18d080-cfc9-11e8-8e9c-b7af13df6cae.png)
![screenshot from 2018-10-14 15-20-19](https://user-images.githubusercontent.com/37431503/46916867-2cb16700-cfc9-11e8-9b02-95522a6407ab.png)
Gimp
![screenshot from 2018-10-14 15-30-31](https://user-images.githubusercontent.com/37431503/46916872-48b50880-cfc9-11e8-8372-608168ca3beb.png)
![screenshot from 2018-10-14 15-38-25](https://user-images.githubusercontent.com/37431503/46916873-48b50880-cfc9-11e8-8b69-567af1388062.png)
And file chooser again for your request
![screenshot from 2018-10-14 15-43-37](https://user-images.githubusercontent.com/37431503/46916913-9b8ec000-cfc9-11e8-84d3-681a12e1fc22.png)

**Comment by clobrano** [comment]
that's because the scrolledbar is independent from the view. It can be attached to different views, not just treeviews.

**Comment by Paz-it** [comment]
> that's because the scrolledbar is independent from the view. It can be attached to different views, not just treeviews.

Exactly! - that way you can decide if you want the scrollbars inside the view or out side configuring it mainly with the "window spacing" and "within the bevel" values in the main.rc file. 
The "thick-grey-line" :smile:  is not part of the scroll bar. it is the the left border of the entire window.

**Comment by clobrano** [comment]
> The "thick-grey-line" smile is not part of the scroll bar. it is the right border of the entire window.

No, it's not, I can make it red if I want :smile: 

![image](https://user-images.githubusercontent.com/2883614/46934803-67fb7680-d059-11e8-89f1-6e49f5efdc0e.png)

it's a svg picture inside light/gtk-2.0/assets.svg called `scrollbar-vert-trough`

**Comment by Paz-it** [comment]
Oh, my bad ![faint](https://user-images.githubusercontent.com/37431503/46944083-d6503100-d079-11e8-8dd4-1cfbeb30eaef.gif) You said on the left and I'm seeing *RIGHT*. Maybe we need to comment it out and see if it's not breaking anything.

**Comment by Feichtmeier** [comment]
*necromancing*
@clobrano @Paz-it what's the status of this?

**Comment by clobrano** [comment]
To sum up.

The svg of this widget is called `treeview-header-button`

![image](https://user-images.githubusercontent.com/2883614/50512158-dfee1000-0a90-11e9-86ab-f2eb9504c5da.png)

the image is taller than large but it's stretched to accomodate each header, this means that the thick grey line on the right can be both the separator between two column headers and the border of the whole treeview

![treeview-headerbar-button-indication](https://user-images.githubusercontent.com/2883614/50512615-52f88600-0a93-11e9-862a-d6645d1d99f2.png)

For this reason we can't get rid of the right border.
The top border seems to be removable instead. The only place where it seems to be necessary is `a widget factory`

![image](https://user-images.githubusercontent.com/2883614/50513552-c94bb700-0a98-11e9-8a06-7cb90503da26.png)

but most of the other examples I can find, the top border is already provided by the container

![image](https://user-images.githubusercontent.com/2883614/50513593-f4cea180-0a98-11e9-8bff-313b43dbe330.png)

![image](https://user-images.githubusercontent.com/2883614/50515097-e1c0cf00-0aa2-11e9-828a-39a9272a759f.png)

This latter is also another example to why we can't remove the right border. In "Places" it's redundant, but not in the treeview with all the files because in that case on the right there's the handle and not a border

EDIT:
however, replacing the pixmap function `box` with `shadow` the glitch is reduced (I took this idea from [here](https://wiki.gnome.org/Attic/GnomeArt/Tutorials/GtkEngines/PixmapEngine))

![image](https://user-images.githubusercontent.com/2883614/50515657-51848900-0aa6-11e9-9d0f-58f0ef951b65.png)

**Comment by clobrano** [comment]
I agree, however I like the space between the two panes and I saw that reducing the handle-size to 8 is enough to remove the line
