### ISSUE TITLE
Ticks in gdm do not show

### ISSUE THREAD

**Issue by 8none1** [ubuntu/yaru#917]
## Expected Behavior

At the login screen (gdm) the a11y menu has a number of options, such as large text, screen reader etc.  If you turn on screen reader you can then hover over the menu items and they will be read to you.

If you hover over an option that is enabled, the screen reader will tell you, for example:

`Screen reader. TICKED`

The entry in the menu item should have a tick next to it.

This is what happens using the default GNOME theme.

## Actual Behavior

Tick is not shown next to checked items.

## Steps to Reproduce the Problem

  1. Boot Ubuntu Cosmic
  1. Enable the screen reader from the a11y menu top right
  1. Hover over the screen reader menu item
  1. Listen to the speech and make sure it says TICKED
  1. See that the menu option shows no tick

**Comment by didrocks** [comment]
The issue is that toggle-on and toggle-off svg aren't shipped in `/usr/share/gnome-shell/themes` but in the Yaru subdirectory. gdm3.css symlink is in `/usr/share/gnome-shell/themes`.

I think the correct patch would be to modify GNOME Shell to point to the realize the symlink, so that we are referring the real path and relative directories.

**Comment by didrocks** [comment]
I'll fix it in GNOME Shell itself. See https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1798747 for the SRU.

Keeping the bug opened here until the SRU is in to avoid duplicates (as people will likely target Yaru)

**Comment by didrocks** [comment]
This is fixed.
