### ISSUE TITLE
GDM login screen

### ISSUE THREAD

**Issue by DarthWound** [ubuntu/yaru#964]
Hello,

Congrats on all the improvements! I didn't use Ubuntu since 10.10, but I'll probably come back to it.

Yaru is incredibly beautiful while being subtle, however GDM theme is ugly and hurt eyes, not only for me when I read forums, reddit, etc... This pink/purple gradient looks like there's a visual glitch. Maybe just go plain black or dark grey?

_PS: I'm aware that we can tweak that ourselves in CSS or use gdm-alternatives_

**Comment by madsrh** [comment]
Hi @DarthWound 

We did some mockups with black and dark gray earlier in the process and found it to be too dull / cold, but I do agree with you that the current GDM isn't perfect.

We are bound by a lot of technical limitations here (no slanting gradient, no blur, no images, ...), so if it makes you feel better, you can think of the current GDM theme as a placeholder, while we wait for the new version to arrive: 
https://blogs.gnome.org/aday/2018/05/09/redesigning-the-lock-screen/ _(although that's still very much work in progress)._

Thanks for the kind words! 😃 

I will close this issue for now, but @clobrano @godlyranchdressing @Feichtmeier feel free to reopen if you think otherwise.

**Comment by godlyranchdressing** [comment]
I think it could do with a couple tweaks. I did this a while ago, modeling it after the current Ubuntu site. We don't know how long it'll be till that mockup becomes a reality.

![gdmtest](https://user-images.githubusercontent.com/27529229/48427461-2389f600-e73f-11e8-8634-b140073154d3.png)

I haven't touched the buttons yet though, obviously. Reopening for discussion.

**Comment by Feichtmeier** [comment]
I think that's a cool idea - especially considering that we want to be a bit different in 19.4!

**Comment by DarthWound** [comment]
It's still a bit "agressive" IMO ^^ but seems better than what we currently have anyway.

Don't get me wrong, I know that Ubuntu has to keep a branding and a strong identity, but the problem here I think is that you've achieved that quite brillantly with a good Yaru theme but GDM is messed up and looks like a bug from the 90's. And, most important, GNOME' voluntary limitations are what they are so we can't easily apply another color or even an image, like some other DEs or even Windows. When default wallpapers are ugly, well, it's unfortunate but not a major issue, download another one and change it. Here it's a different story...

Working on a GNOME base is already difficult and [will be even harder soon](https://blogs.gnome.org/aday/2018/10/09/farewell-application-menus/). They remove things everyday. They have their vision, and I liked GNOME3 until recently, honestly I don't know how much time it will be possible to please almost everyone with this DE, even with patches/hacks/extensions.

I distro-hop since 10.10 but always keeped an eye on Ubuntu and installed it on my family/friends computers. Since Unity's end I put Kubuntu and tweak it for them instead, I would have to tweak the GNOME desktop more than KDE nowadays, kinda ironic when GNOME devs tell us that they're simplifying stuff huh.

Ubuntu was THE distribution for beginners and people who wanted sane defaults, something usable almost immediatly after install. It shouldn't lose that.

I'm sorry, I digress badly. I guess it's natural when we love(d) something.

**Comment by eaglersdeveloper** [comment]
Too dark.

How about this background? 👇

![login_background svg](https://user-images.githubusercontent.com/40228953/48477930-4c33ed80-e81c-11e8-8b2c-dd79455099bb.png)

**Comment by clobrano** [comment]
@eaglersdeveloper, GNOME shell lock screen does not support images.

**Comment by eaglersdeveloper** [comment]
I managed to use a picture as a background (background-image).

**Comment by clobrano** [comment]
sorry, I meant login screen. Did you manage to change the login screen? That would be cool, could you share how?

**Comment by Feichtmeier** [comment]
I think mads also thought about something like these graphical approach for ubiquity.
Where is a link to the old issue? I think I remember that those images do not scale with the resolution and therefor can not be used but I could be wrong.

**Comment by eaglersdeveloper** [comment]
Same as in CSS
`background-image: url(/home/.../login-background.svg)`

> I think I remember that those images do not scale with the resolution and therefor can not be used but I could be wrong.

This is a vector picture.

**Comment by Feichtmeier** [comment]
That'd should work then

**Comment by Feichtmeier** [comment]
We can't use the snaps ATM because the CI build is not working but
Could you push the branch so I could test it on my development VM? @eaglersdeveloper

**Comment by eaglersdeveloper** [comment]
OK, tomorrow

**Comment by godlyranchdressing** [comment]
@Feichtmeier Sure, even with my mockup there's this weird left to right banding effect that's noticeable. Hopefully it'll fix that too.

**Comment by Feichtmeier** [comment]
That could look great!

**Comment by Feichtmeier** [comment]
Oh then I misunderstood!
Well at least you came here and shared your opinion which is good since we need opinions :)

**Comment by Luxamman** [comment]
Still hoping for the new login screen, not sure if the new one makes it into the 3.32 release. Hopefully we can use background pictures then, or even blur. The actual one didn't get much love because we knew it will be gone soon... but not soon enough^^ 

I remember that there wasn't a lot of options to work with, also there is still time like @Feichtmeier said. 

However, I was just jumping back to the two color idea - one with gradient with the original colors and a second one with a overlay radial gradient (for more focus to the login). Both with also darker variations. 

![custom 1](https://user-images.githubusercontent.com/20417555/48769612-64908600-ecbc-11e8-983e-a47e6ceaf65b.png)
![custom 2](https://user-images.githubusercontent.com/20417555/48769616-665a4980-ecbc-11e8-8c19-9e30c17cebfa.png)
![custom 3](https://user-images.githubusercontent.com/20417555/48769624-68240d00-ecbc-11e8-8781-1583684d9cc9.png)
![custom 4](https://user-images.githubusercontent.com/20417555/48769628-69edd080-ecbc-11e8-9dc4-ab559252d98c.png)

**Comment by eaglersdeveloper** [comment]
@Feichtmeier, test it: #976

**Comment by Feichtmeier** [comment]
Some fast alternatives inspired by @godlyranchdressing and the ubuntu site he linked
![image](https://user-images.githubusercontent.com/15329494/48774666-2cdd0a80-eccb-11e8-8177-befef55b9827.png)
![image](https://user-images.githubusercontent.com/15329494/48774687-38303600-eccb-11e8-866b-e0c900af291e.png)

![image](https://user-images.githubusercontent.com/15329494/48774746-59912200-eccb-11e8-8aa5-7c42b2b7e2a7.png)
![image](https://user-images.githubusercontent.com/15329494/48774754-60b83000-eccb-11e8-87af-c06bb8d1db28.png)

![image](https://user-images.githubusercontent.com/15329494/48774903-c2789a00-eccb-11e8-905b-ddc07fec2c4b.png)
![image](https://user-images.githubusercontent.com/15329494/48774808-847b7600-eccb-11e8-8510-cf8bf82bf8e5.png)

![image](https://user-images.githubusercontent.com/15329494/48775000-0cfa1680-eccc-11e8-821c-c6943ac52d90.png)
![image](https://user-images.githubusercontent.com/15329494/48775016-18e5d880-eccc-11e8-91ec-12ec9eea5334.png)

**Comment by eaglersdeveloper** [comment]
No, it already looks like pure GNOME, which is what we don't need.

**Comment by godlyranchdressing** [comment]
I very much like the inkstone to jet and the solid colors, @Feichtmeier. The solid jet background in particular gives off really a luxurious vibe, but the light button works better with Inkstone. Those mockups are making me start to lean on scrapping the gradient and just using a solid color so in my case I'll +1 the inkstone lockscreen.

@eaglersdeveloper I did want it the lockscreen to be "different" for Yaru, but being different for the sake of it isn't always a good thing. In this case especially, it's a lockscreen where you want the design to be subtle and we also just don't have that many options right now.

**Comment by clobrano** [comment]
Silly question. Isn't the original noise dark background an option anymore? Maybe with a jet color?

**Comment by Feichtmeier** [comment]
Well, it would not be bad but personally it wouldn't be my favourite neither  
I could live with many backgrounds as long as we don't go back to 3d buttons *evil face* :D
It's up to you but maybe we need to see more ideas (we are sadly really limited :/ )

**Comment by madsrh** [comment]
> ...the original noise dark background...

If [this ](http://www.omgubuntu.co.uk/wp-content/uploads/2017/09/ubuntu-1710-gdm-login-screen-default.jpg)is the one you are referring to, then I reallllllyyyy hope we can finde a better solution. 

![image](https://user-images.githubusercontent.com/3986894/48807432-c9c89380-ed1d-11e8-9ce9-a59e9b2416df.png)
If in doubt, I'm **-1** for the noise texture.

I like @Feichtmeier's ideas, but the gradients still has visible, so perhaps a solid color would be best?
no gradient

**Comment by taciturasa** [comment]
Honestly, and I feel like I've said this before, but I really like that use of $jet. Sure, it's not exactly bright and splashy, but it doesn't look washed out and it looks bold, and considering that this will be servicing both the login screen AND lock screen, it sort of acts like a layer underneath the system. 

The jet is pleasant on the eyes when waking up the computer in the middle of the night, or when starting the computer. Think of it like a sunrise - You're going from dark to slightly lighter to the vibrant colors of the default desktop as you get warmed up for the computer and everything wakes up for both you and the computer. 

We could go lighter, but my issue with that is that whenever such colors are used in the theme, it's sparingly and not in black blocks. As such it looks a little pale and maybe a little ill. It would require a new color entirely imo and that's not a fantastic idea.

I'm also a fan of the wallpaper provided by @eaglersdeveloper as a secondary option

**Comment by DarthWound** [comment]
Solid $jet version is awesome. Blends well with Yaru and gives a good impression.



---

> But since some people do not like the gradients, I don't know what to do 😆 (and the issue was made because the OP does not like gradients)

It's not that I don't like gradients, it's just that the current login screen is really disturbing and shouldn't be used on a first-class distro like Ubuntu, it fits something like HannahMontanaLinux better.

> In the end we should better not change our mind every X months. There is always someone who does not like this or that.

As I said in my "issue", look at Reddit, forums... a lot of people are asking how to change this screen. If it would be for me, I wouldn't care as I know how to tweak my distros. I've opened an issue because we should have a better default GDM and it's not only me.

---

> being different for the sake of it isn't always a good thing.

+1000

---



I know that desktop isn't main target of Ubuntu/Canonical anymore, but providing something that works and that is looking nice should be a priority anyway, because it's what made Ubuntu popular back in the days.

**Comment by DarthWound** [comment]
> We are not from canonical. And please stop that offtopic drama in your posts, it's kind of unproductive :)

I know that, and there's no drama, I'm just giving my reasoning because you think that I opened this issue only because I dislike the GDM screen. I use Ubuntu since 9.04 (and distro-hopped like a freak since 10.10 but not because I hate this or that). Instead of drama, take it as motivation, that's all.

I'll keep silent now :no_mouth:

**Comment by Feichtmeier** [comment]
I wonder, if the light to medium purple gradient looks too much "hannamontana" (.... Jesus) to you, how about a solid dark purple? @darthwound

**Comment by DarthWound** [comment]
> I wonder, if the light to medium purple gradient looks too much "hannamontana" (.... Jesus) to you, how about a solid dark purple? @DarthWound

Something like [what we had in 17.10](https://i.stack.imgur.com/XT9Or.png)? Why not. Seems very acceptable imo. Cosmic' GDM theme is widely rejected but I didn't read a lot of complaints against it when Artful was released.

I repeat myself but I'm not against gradients. @godlyranchdressing [mockup](https://github.com/ubuntu/yaru/issues/964#issuecomment-438336006) is fine. Just look at [current Yaru GDM theme](https://static.cnbetacdn.com/article/2018/0801/d9e39945a493a95.jpg) and compare.

**Comment by ubuntujaggers** [comment]
I'm only just getting to see the current login screen - until today I had a white box on flat purple.  I uninstalled the Communitheme snap because it hasn't worked for me for a while, and I seem to have magically got a different login screen!

I think it's actually nice - especially given the limited design options here.  The orange selection when you hover over the user to select it is a bit jarring because it's such a large area of orange.  I think I'd slightly prefer to use the same shape as a white opacity (similar to the one when you hover on a launcher icon) rather than solid orange.  But I'm not strongly averse.

All IMO as ever:

When I boot my PC, I see...

- A blank purple screen
- The exact same purple with "Ubuntu" and the five orange dots
- The login screen.

Given the limited options available, I think my personal preference is probably to use the same flat purple a third time on the login screen, for maximum continuity (power on --> login) and general Ubuntu feeling.  I don't mind the gradient at all (and I like the mockup by @godlyranchdressing), but if it's divisive or has banding then you could just use the flat purple from previous screens.

The dark greys (jet etc.) are a nice choice in general design terms, but I think grey might look a bit "unthemed" after all the purple leading up to the login screen?  And it would be a shame to de-purple the earlier screens because I think they're bold and branded, in a good way.  The second the screen first flashes purple, it's really obvious that you're not booting into Windows.  I can imagine someone thinking (in a good way): "Oho - this is a bit different!"  Obviously, not everyone loves purple.  But I feel like Ubuntu made a decision long ago to have a bold, fun look that some people would love, rather than going for a neutral look that no one would mind? 

Aside from that, I feel like the grey options are smart and attractive but a bit cold and dark.  To me, it looks like a distro for serious techies.  IMO, one of Ubuntu's assets is the really fresh, friendly feel of Yaru.  I think a Linux newbie would look at the default desktop and think, "wow, this is lovely."  I'm not averse to grey, but it's not my personal favourite.

One thing I've never liked much is the default texture (the "noise") which early versions of the login screen inherited from default Gnome.  It looks out of place to me because it doesn't appear anywhere else in the boot-up sequence or the desktop itself.  I would say my strongest opinion on the login screen is preferring it to be noise-free.  Other than that I'm fairly relaxed.  I wouldn't be upset if it even stayed as it is, because it feels like you have limited scope to do much with this screen currently.

**Comment by Feichtmeier** [comment]
@ubuntujaggers tbh, I think you nailed it. +1 for solid purple

**Comment by real-amano** [comment]
I think we should always go for maximum coherence for the boot up. If we opt for new visual styles, GRUB, Plymouth and all possible splashes should be adapted as well. 

In my case the boot up is still not flicker-free thus I would prefer black as the background color personally.

**Comment by Paz-it** [comment]
If one of @Luxamman options is not feasible I'll vote for solid purple then...

**Comment by Luxamman** [comment]
You made some good points, overall black is way too much for me and maybe also grey is too much of a visual glitch - what after all is the point of discussing this here. Even if the grey can work, but also depends on what grey it is, same for the "solid purple". 

For me it don't have to be a perfect fit to the boot process, because it is not part of it and when hibernating, there is no boot process. It should welcome the user with a nice, fresh, or cool touch - every time when unlocking. 

Like the rest of the system - content is king. So maybe the way to go is to be darker, but not black or grey, to still have some accents, but not to unfocus the login form. 

So a stong purple could unfocus the important login part, black could be too nerdy and grey not playful enough. The actual gradient is also too bright on second thought, maybe we can find a doable and feasible solution here to fit the system better.

**Comment by Feichtmeier** [comment]
Pushed the same color as Grub uses in Ubuntu which you can test here https://github.com/ubuntu/yaru/pull/994

So it will be:

Booting - purple
Login - same purple + GDM entry/buttons

Gradients just do not work without strange effects. @vanvugt said some math could help, but I am not able to provide that math and I am not sure this math can be provided via CSS

So, since the new upstream login screen is on the horizon, my opinion is, that we should get over this topic now and wait for the upstream changes. :man_shrugging:

**Comment by taciturasa** [comment]
Sounds reasonable to me!

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/49306531-b44c2a00-f4d2-11e8-9df0-9d971d92f174.png)
(https://design.ubuntu.com/brand/colour-palette/)
Chose =)
