### ISSUE TITLE
Replace the Activities Button with an icon.

### ISSUE THREAD

**Issue by snydox** [ubuntu/yaru#995]
## Icon Request

I strongly believe that the Activities button should be removed in favour of an icon. My OCD an't stand that the word "Activities" is longer than the dock.

On the example below I just replaced the word Activities with 4 squares: **▮▮▮▮** But anything than the word Activities will do it. Maybe a transparent box similar to what Microsoft uses to show the Desktop could work as well.

Thank you.
 
![desktop](https://user-images.githubusercontent.com/13590875/49288800-bfba3980-f46f-11e8-9f8c-b16b9ccbb0d5.png)

**Comment by clobrano** [comment]
Hi @snydox,

thanks for contributing :)
The activity button has been discussed quite a lot in the [Ubuntu HUB](https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545) (I understand, it's a very long thread) and we decided to adhere to upstream GNOME in this regards. Then, the best chance you have to see your proposal accepted is to talk with GNOME team itself
 
(consider that in other languages, the situation is even worse :D)

**Comment by Feichtmeier** [comment]
I agree and some others also agree, but upstream disagrees. 
There is a biiiiiiiiiiiig discussion issue about this somewhere here or on the old communitheme shell repo.
We use the gnome DE and are somehow dependant on upstream design decisions.
I"d say make an issue on the time gitlab repo because we agreed that we don't want to diverge from upstream there.
They were okay with a logo beside the word activities but that was not really good looking with different resolutions.
Thus I'm closing this now, since we went already through this discussion.
Thanks for contributing!

**Comment by Feichtmeier** [comment]
@snydox
Don't argue that the word overlaps the dock, because vanilla gnome does not have a dock ;) just a tip
